/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck
/*
 * This file exports the `AwesomeTag` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from '@prisma/client/runtime/client'

import type * as $Enums from '../enums'
import type * as Prisma from '../internal/prismaNamespace'

/**
 * Model AwesomeTag
 * Awesome 的标签
 */
export type AwesomeTagModel = runtime.Types.Result.DefaultSelection<Prisma.$AwesomeTagPayload>

export type AggregateAwesomeTag = {
  _count: AwesomeTagCountAggregateOutputType | null
  _avg: AwesomeTagAvgAggregateOutputType | null
  _sum: AwesomeTagSumAggregateOutputType | null
  _min: AwesomeTagMinAggregateOutputType | null
  _max: AwesomeTagMaxAggregateOutputType | null
}

export type AwesomeTagAvgAggregateOutputType = {
  index: number | null
}

export type AwesomeTagSumAggregateOutputType = {
  index: number | null
}

export type AwesomeTagMinAggregateOutputType = {
  id: string | null
  index: number | null
  label: string | null
  desc: string | null
  color: string | null
  icon: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type AwesomeTagMaxAggregateOutputType = {
  id: string | null
  index: number | null
  label: string | null
  desc: string | null
  color: string | null
  icon: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type AwesomeTagCountAggregateOutputType = {
  id: number
  index: number
  label: number
  desc: number
  color: number
  icon: number
  createdAt: number
  updatedAt: number
  _all: number
}

export type AwesomeTagAvgAggregateInputType = {
  index?: true
}

export type AwesomeTagSumAggregateInputType = {
  index?: true
}

export type AwesomeTagMinAggregateInputType = {
  id?: true
  index?: true
  label?: true
  desc?: true
  color?: true
  icon?: true
  createdAt?: true
  updatedAt?: true
}

export type AwesomeTagMaxAggregateInputType = {
  id?: true
  index?: true
  label?: true
  desc?: true
  color?: true
  icon?: true
  createdAt?: true
  updatedAt?: true
}

export type AwesomeTagCountAggregateInputType = {
  id?: true
  index?: true
  label?: true
  desc?: true
  color?: true
  icon?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type AwesomeTagAggregateArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Filter which AwesomeTag to aggregate.
   */
  where?: Prisma.AwesomeTagWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   *
   * Determine the order of AwesomeTags to fetch.
   */
  orderBy?: Prisma.AwesomeTagOrderByWithRelationInput | Prisma.AwesomeTagOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   *
   * Sets the start position
   */
  cursor?: Prisma.AwesomeTagWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Take `±n` AwesomeTags from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Skip the first `n` AwesomeTags.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   *
   * Count returned AwesomeTags
   **/
  _count?: true | AwesomeTagCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   *
   * Select which fields to average
   **/
  _avg?: AwesomeTagAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   *
   * Select which fields to sum
   **/
  _sum?: AwesomeTagSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   *
   * Select which fields to find the minimum value
   **/
  _min?: AwesomeTagMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   *
   * Select which fields to find the maximum value
   **/
  _max?: AwesomeTagMaxAggregateInputType
}

export type GetAwesomeTagAggregateType<T extends AwesomeTagAggregateArgs> = {
  [P in keyof T & keyof AggregateAwesomeTag]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateAwesomeTag[P]>
    : Prisma.GetScalarType<T[P], AggregateAwesomeTag[P]>
}

export type AwesomeTagGroupByArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  where?: Prisma.AwesomeTagWhereInput
  orderBy?:
    | Prisma.AwesomeTagOrderByWithAggregationInput
    | Prisma.AwesomeTagOrderByWithAggregationInput[]
  by: Prisma.AwesomeTagScalarFieldEnum[] | Prisma.AwesomeTagScalarFieldEnum
  having?: Prisma.AwesomeTagScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: AwesomeTagCountAggregateInputType | true
  _avg?: AwesomeTagAvgAggregateInputType
  _sum?: AwesomeTagSumAggregateInputType
  _min?: AwesomeTagMinAggregateInputType
  _max?: AwesomeTagMaxAggregateInputType
}

export type AwesomeTagGroupByOutputType = {
  id: string
  index: number | null
  label: string
  desc: string | null
  color: string | null
  icon: string | null
  createdAt: Date
  updatedAt: Date
  _count: AwesomeTagCountAggregateOutputType | null
  _avg: AwesomeTagAvgAggregateOutputType | null
  _sum: AwesomeTagSumAggregateOutputType | null
  _min: AwesomeTagMinAggregateOutputType | null
  _max: AwesomeTagMaxAggregateOutputType | null
}

export type GetAwesomeTagGroupByPayload<T extends AwesomeTagGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<AwesomeTagGroupByOutputType, T['by']> & {
      [P in keyof T & keyof AwesomeTagGroupByOutputType]: P extends '_count'
        ? T[P] extends boolean
          ? number
          : Prisma.GetScalarType<T[P], AwesomeTagGroupByOutputType[P]>
        : Prisma.GetScalarType<T[P], AwesomeTagGroupByOutputType[P]>
    }
  >
>

export type AwesomeTagWhereInput = {
  AND?: Prisma.AwesomeTagWhereInput | Prisma.AwesomeTagWhereInput[]
  OR?: Prisma.AwesomeTagWhereInput[]
  NOT?: Prisma.AwesomeTagWhereInput | Prisma.AwesomeTagWhereInput[]
  id?: Prisma.StringFilter<'AwesomeTag'> | string
  index?: Prisma.IntNullableFilter<'AwesomeTag'> | number | null
  label?: Prisma.StringFilter<'AwesomeTag'> | string
  desc?: Prisma.StringNullableFilter<'AwesomeTag'> | string | null
  color?: Prisma.StringNullableFilter<'AwesomeTag'> | string | null
  icon?: Prisma.StringNullableFilter<'AwesomeTag'> | string | null
  createdAt?: Prisma.DateTimeFilter<'AwesomeTag'> | Date | string
  updatedAt?: Prisma.DateTimeFilter<'AwesomeTag'> | Date | string
  underAwesomes?: Prisma.AwesomeItemListRelationFilter
}

export type AwesomeTagOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  index?: Prisma.SortOrderInput | Prisma.SortOrder
  label?: Prisma.SortOrder
  desc?: Prisma.SortOrderInput | Prisma.SortOrder
  color?: Prisma.SortOrderInput | Prisma.SortOrder
  icon?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  underAwesomes?: Prisma.AwesomeItemOrderByRelationAggregateInput
}

export type AwesomeTagWhereUniqueInput = Prisma.AtLeast<
  {
    id?: string
    AND?: Prisma.AwesomeTagWhereInput | Prisma.AwesomeTagWhereInput[]
    OR?: Prisma.AwesomeTagWhereInput[]
    NOT?: Prisma.AwesomeTagWhereInput | Prisma.AwesomeTagWhereInput[]
    index?: Prisma.IntNullableFilter<'AwesomeTag'> | number | null
    label?: Prisma.StringFilter<'AwesomeTag'> | string
    desc?: Prisma.StringNullableFilter<'AwesomeTag'> | string | null
    color?: Prisma.StringNullableFilter<'AwesomeTag'> | string | null
    icon?: Prisma.StringNullableFilter<'AwesomeTag'> | string | null
    createdAt?: Prisma.DateTimeFilter<'AwesomeTag'> | Date | string
    updatedAt?: Prisma.DateTimeFilter<'AwesomeTag'> | Date | string
    underAwesomes?: Prisma.AwesomeItemListRelationFilter
  },
  'id'
>

export type AwesomeTagOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  index?: Prisma.SortOrderInput | Prisma.SortOrder
  label?: Prisma.SortOrder
  desc?: Prisma.SortOrderInput | Prisma.SortOrder
  color?: Prisma.SortOrderInput | Prisma.SortOrder
  icon?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.AwesomeTagCountOrderByAggregateInput
  _avg?: Prisma.AwesomeTagAvgOrderByAggregateInput
  _max?: Prisma.AwesomeTagMaxOrderByAggregateInput
  _min?: Prisma.AwesomeTagMinOrderByAggregateInput
  _sum?: Prisma.AwesomeTagSumOrderByAggregateInput
}

export type AwesomeTagScalarWhereWithAggregatesInput = {
  AND?:
    | Prisma.AwesomeTagScalarWhereWithAggregatesInput
    | Prisma.AwesomeTagScalarWhereWithAggregatesInput[]
  OR?: Prisma.AwesomeTagScalarWhereWithAggregatesInput[]
  NOT?:
    | Prisma.AwesomeTagScalarWhereWithAggregatesInput
    | Prisma.AwesomeTagScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<'AwesomeTag'> | string
  index?: Prisma.IntNullableWithAggregatesFilter<'AwesomeTag'> | number | null
  label?: Prisma.StringWithAggregatesFilter<'AwesomeTag'> | string
  desc?: Prisma.StringNullableWithAggregatesFilter<'AwesomeTag'> | string | null
  color?: Prisma.StringNullableWithAggregatesFilter<'AwesomeTag'> | string | null
  icon?: Prisma.StringNullableWithAggregatesFilter<'AwesomeTag'> | string | null
  createdAt?: Prisma.DateTimeWithAggregatesFilter<'AwesomeTag'> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<'AwesomeTag'> | Date | string
}

export type AwesomeTagCreateInput = {
  id?: string
  index?: number | null
  label: string
  desc?: string | null
  color?: string | null
  icon?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  underAwesomes?: Prisma.AwesomeItemCreateNestedManyWithoutTagsInput
}

export type AwesomeTagUncheckedCreateInput = {
  id?: string
  index?: number | null
  label: string
  desc?: string | null
  color?: string | null
  icon?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  underAwesomes?: Prisma.AwesomeItemUncheckedCreateNestedManyWithoutTagsInput
}

export type AwesomeTagUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  index?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  label?: Prisma.StringFieldUpdateOperationsInput | string
  desc?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  color?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  icon?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  underAwesomes?: Prisma.AwesomeItemUpdateManyWithoutTagsNestedInput
}

export type AwesomeTagUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  index?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  label?: Prisma.StringFieldUpdateOperationsInput | string
  desc?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  color?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  icon?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  underAwesomes?: Prisma.AwesomeItemUncheckedUpdateManyWithoutTagsNestedInput
}

export type AwesomeTagCreateManyInput = {
  id?: string
  index?: number | null
  label: string
  desc?: string | null
  color?: string | null
  icon?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type AwesomeTagUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  index?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  label?: Prisma.StringFieldUpdateOperationsInput | string
  desc?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  color?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  icon?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type AwesomeTagUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  index?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  label?: Prisma.StringFieldUpdateOperationsInput | string
  desc?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  color?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  icon?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type AwesomeTagCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  index?: Prisma.SortOrder
  label?: Prisma.SortOrder
  desc?: Prisma.SortOrder
  color?: Prisma.SortOrder
  icon?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type AwesomeTagAvgOrderByAggregateInput = {
  index?: Prisma.SortOrder
}

export type AwesomeTagMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  index?: Prisma.SortOrder
  label?: Prisma.SortOrder
  desc?: Prisma.SortOrder
  color?: Prisma.SortOrder
  icon?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type AwesomeTagMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  index?: Prisma.SortOrder
  label?: Prisma.SortOrder
  desc?: Prisma.SortOrder
  color?: Prisma.SortOrder
  icon?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type AwesomeTagSumOrderByAggregateInput = {
  index?: Prisma.SortOrder
}

export type AwesomeTagListRelationFilter = {
  every?: Prisma.AwesomeTagWhereInput
  some?: Prisma.AwesomeTagWhereInput
  none?: Prisma.AwesomeTagWhereInput
}

export type AwesomeTagOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type AwesomeTagCreateNestedManyWithoutUnderAwesomesInput = {
  create?:
    | Prisma.XOR<
        Prisma.AwesomeTagCreateWithoutUnderAwesomesInput,
        Prisma.AwesomeTagUncheckedCreateWithoutUnderAwesomesInput
      >
    | Prisma.AwesomeTagCreateWithoutUnderAwesomesInput[]
    | Prisma.AwesomeTagUncheckedCreateWithoutUnderAwesomesInput[]
  connectOrCreate?:
    | Prisma.AwesomeTagCreateOrConnectWithoutUnderAwesomesInput
    | Prisma.AwesomeTagCreateOrConnectWithoutUnderAwesomesInput[]
  connect?: Prisma.AwesomeTagWhereUniqueInput | Prisma.AwesomeTagWhereUniqueInput[]
}

export type AwesomeTagUncheckedCreateNestedManyWithoutUnderAwesomesInput = {
  create?:
    | Prisma.XOR<
        Prisma.AwesomeTagCreateWithoutUnderAwesomesInput,
        Prisma.AwesomeTagUncheckedCreateWithoutUnderAwesomesInput
      >
    | Prisma.AwesomeTagCreateWithoutUnderAwesomesInput[]
    | Prisma.AwesomeTagUncheckedCreateWithoutUnderAwesomesInput[]
  connectOrCreate?:
    | Prisma.AwesomeTagCreateOrConnectWithoutUnderAwesomesInput
    | Prisma.AwesomeTagCreateOrConnectWithoutUnderAwesomesInput[]
  connect?: Prisma.AwesomeTagWhereUniqueInput | Prisma.AwesomeTagWhereUniqueInput[]
}

export type AwesomeTagUpdateManyWithoutUnderAwesomesNestedInput = {
  create?:
    | Prisma.XOR<
        Prisma.AwesomeTagCreateWithoutUnderAwesomesInput,
        Prisma.AwesomeTagUncheckedCreateWithoutUnderAwesomesInput
      >
    | Prisma.AwesomeTagCreateWithoutUnderAwesomesInput[]
    | Prisma.AwesomeTagUncheckedCreateWithoutUnderAwesomesInput[]
  connectOrCreate?:
    | Prisma.AwesomeTagCreateOrConnectWithoutUnderAwesomesInput
    | Prisma.AwesomeTagCreateOrConnectWithoutUnderAwesomesInput[]
  upsert?:
    | Prisma.AwesomeTagUpsertWithWhereUniqueWithoutUnderAwesomesInput
    | Prisma.AwesomeTagUpsertWithWhereUniqueWithoutUnderAwesomesInput[]
  set?: Prisma.AwesomeTagWhereUniqueInput | Prisma.AwesomeTagWhereUniqueInput[]
  disconnect?: Prisma.AwesomeTagWhereUniqueInput | Prisma.AwesomeTagWhereUniqueInput[]
  delete?: Prisma.AwesomeTagWhereUniqueInput | Prisma.AwesomeTagWhereUniqueInput[]
  connect?: Prisma.AwesomeTagWhereUniqueInput | Prisma.AwesomeTagWhereUniqueInput[]
  update?:
    | Prisma.AwesomeTagUpdateWithWhereUniqueWithoutUnderAwesomesInput
    | Prisma.AwesomeTagUpdateWithWhereUniqueWithoutUnderAwesomesInput[]
  updateMany?:
    | Prisma.AwesomeTagUpdateManyWithWhereWithoutUnderAwesomesInput
    | Prisma.AwesomeTagUpdateManyWithWhereWithoutUnderAwesomesInput[]
  deleteMany?: Prisma.AwesomeTagScalarWhereInput | Prisma.AwesomeTagScalarWhereInput[]
}

export type AwesomeTagUncheckedUpdateManyWithoutUnderAwesomesNestedInput = {
  create?:
    | Prisma.XOR<
        Prisma.AwesomeTagCreateWithoutUnderAwesomesInput,
        Prisma.AwesomeTagUncheckedCreateWithoutUnderAwesomesInput
      >
    | Prisma.AwesomeTagCreateWithoutUnderAwesomesInput[]
    | Prisma.AwesomeTagUncheckedCreateWithoutUnderAwesomesInput[]
  connectOrCreate?:
    | Prisma.AwesomeTagCreateOrConnectWithoutUnderAwesomesInput
    | Prisma.AwesomeTagCreateOrConnectWithoutUnderAwesomesInput[]
  upsert?:
    | Prisma.AwesomeTagUpsertWithWhereUniqueWithoutUnderAwesomesInput
    | Prisma.AwesomeTagUpsertWithWhereUniqueWithoutUnderAwesomesInput[]
  set?: Prisma.AwesomeTagWhereUniqueInput | Prisma.AwesomeTagWhereUniqueInput[]
  disconnect?: Prisma.AwesomeTagWhereUniqueInput | Prisma.AwesomeTagWhereUniqueInput[]
  delete?: Prisma.AwesomeTagWhereUniqueInput | Prisma.AwesomeTagWhereUniqueInput[]
  connect?: Prisma.AwesomeTagWhereUniqueInput | Prisma.AwesomeTagWhereUniqueInput[]
  update?:
    | Prisma.AwesomeTagUpdateWithWhereUniqueWithoutUnderAwesomesInput
    | Prisma.AwesomeTagUpdateWithWhereUniqueWithoutUnderAwesomesInput[]
  updateMany?:
    | Prisma.AwesomeTagUpdateManyWithWhereWithoutUnderAwesomesInput
    | Prisma.AwesomeTagUpdateManyWithWhereWithoutUnderAwesomesInput[]
  deleteMany?: Prisma.AwesomeTagScalarWhereInput | Prisma.AwesomeTagScalarWhereInput[]
}

export type AwesomeTagCreateWithoutUnderAwesomesInput = {
  id?: string
  index?: number | null
  label: string
  desc?: string | null
  color?: string | null
  icon?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type AwesomeTagUncheckedCreateWithoutUnderAwesomesInput = {
  id?: string
  index?: number | null
  label: string
  desc?: string | null
  color?: string | null
  icon?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type AwesomeTagCreateOrConnectWithoutUnderAwesomesInput = {
  where: Prisma.AwesomeTagWhereUniqueInput
  create: Prisma.XOR<
    Prisma.AwesomeTagCreateWithoutUnderAwesomesInput,
    Prisma.AwesomeTagUncheckedCreateWithoutUnderAwesomesInput
  >
}

export type AwesomeTagUpsertWithWhereUniqueWithoutUnderAwesomesInput = {
  where: Prisma.AwesomeTagWhereUniqueInput
  update: Prisma.XOR<
    Prisma.AwesomeTagUpdateWithoutUnderAwesomesInput,
    Prisma.AwesomeTagUncheckedUpdateWithoutUnderAwesomesInput
  >
  create: Prisma.XOR<
    Prisma.AwesomeTagCreateWithoutUnderAwesomesInput,
    Prisma.AwesomeTagUncheckedCreateWithoutUnderAwesomesInput
  >
}

export type AwesomeTagUpdateWithWhereUniqueWithoutUnderAwesomesInput = {
  where: Prisma.AwesomeTagWhereUniqueInput
  data: Prisma.XOR<
    Prisma.AwesomeTagUpdateWithoutUnderAwesomesInput,
    Prisma.AwesomeTagUncheckedUpdateWithoutUnderAwesomesInput
  >
}

export type AwesomeTagUpdateManyWithWhereWithoutUnderAwesomesInput = {
  where: Prisma.AwesomeTagScalarWhereInput
  data: Prisma.XOR<
    Prisma.AwesomeTagUpdateManyMutationInput,
    Prisma.AwesomeTagUncheckedUpdateManyWithoutUnderAwesomesInput
  >
}

export type AwesomeTagScalarWhereInput = {
  AND?: Prisma.AwesomeTagScalarWhereInput | Prisma.AwesomeTagScalarWhereInput[]
  OR?: Prisma.AwesomeTagScalarWhereInput[]
  NOT?: Prisma.AwesomeTagScalarWhereInput | Prisma.AwesomeTagScalarWhereInput[]
  id?: Prisma.StringFilter<'AwesomeTag'> | string
  index?: Prisma.IntNullableFilter<'AwesomeTag'> | number | null
  label?: Prisma.StringFilter<'AwesomeTag'> | string
  desc?: Prisma.StringNullableFilter<'AwesomeTag'> | string | null
  color?: Prisma.StringNullableFilter<'AwesomeTag'> | string | null
  icon?: Prisma.StringNullableFilter<'AwesomeTag'> | string | null
  createdAt?: Prisma.DateTimeFilter<'AwesomeTag'> | Date | string
  updatedAt?: Prisma.DateTimeFilter<'AwesomeTag'> | Date | string
}

export type AwesomeTagUpdateWithoutUnderAwesomesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  index?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  label?: Prisma.StringFieldUpdateOperationsInput | string
  desc?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  color?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  icon?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type AwesomeTagUncheckedUpdateWithoutUnderAwesomesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  index?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  label?: Prisma.StringFieldUpdateOperationsInput | string
  desc?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  color?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  icon?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type AwesomeTagUncheckedUpdateManyWithoutUnderAwesomesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  index?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  label?: Prisma.StringFieldUpdateOperationsInput | string
  desc?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  color?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  icon?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

/**
 * Count Type AwesomeTagCountOutputType
 */

export type AwesomeTagCountOutputType = {
  underAwesomes: number
}

export type AwesomeTagCountOutputTypeSelect<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  underAwesomes?: boolean | AwesomeTagCountOutputTypeCountUnderAwesomesArgs
}

/**
 * AwesomeTagCountOutputType without action
 */
export type AwesomeTagCountOutputTypeDefaultArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the AwesomeTagCountOutputType
   */
  select?: Prisma.AwesomeTagCountOutputTypeSelect<ExtArgs> | null
}

/**
 * AwesomeTagCountOutputType without action
 */
export type AwesomeTagCountOutputTypeCountUnderAwesomesArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  where?: Prisma.AwesomeItemWhereInput
}

export type AwesomeTagSelect<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = runtime.Types.Extensions.GetSelect<
  {
    id?: boolean
    index?: boolean
    label?: boolean
    desc?: boolean
    color?: boolean
    icon?: boolean
    createdAt?: boolean
    updatedAt?: boolean
    underAwesomes?: boolean | Prisma.AwesomeTag$underAwesomesArgs<ExtArgs>
    _count?: boolean | Prisma.AwesomeTagCountOutputTypeDefaultArgs<ExtArgs>
  },
  ExtArgs['result']['awesomeTag']
>

export type AwesomeTagSelectCreateManyAndReturn<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = runtime.Types.Extensions.GetSelect<
  {
    id?: boolean
    index?: boolean
    label?: boolean
    desc?: boolean
    color?: boolean
    icon?: boolean
    createdAt?: boolean
    updatedAt?: boolean
  },
  ExtArgs['result']['awesomeTag']
>

export type AwesomeTagSelectUpdateManyAndReturn<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = runtime.Types.Extensions.GetSelect<
  {
    id?: boolean
    index?: boolean
    label?: boolean
    desc?: boolean
    color?: boolean
    icon?: boolean
    createdAt?: boolean
    updatedAt?: boolean
  },
  ExtArgs['result']['awesomeTag']
>

export type AwesomeTagSelectScalar = {
  id?: boolean
  index?: boolean
  label?: boolean
  desc?: boolean
  color?: boolean
  icon?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type AwesomeTagOmit<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = runtime.Types.Extensions.GetOmit<
  'id' | 'index' | 'label' | 'desc' | 'color' | 'icon' | 'createdAt' | 'updatedAt',
  ExtArgs['result']['awesomeTag']
>
export type AwesomeTagInclude<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  underAwesomes?: boolean | Prisma.AwesomeTag$underAwesomesArgs<ExtArgs>
  _count?: boolean | Prisma.AwesomeTagCountOutputTypeDefaultArgs<ExtArgs>
}
export type AwesomeTagIncludeCreateManyAndReturn<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {}
export type AwesomeTagIncludeUpdateManyAndReturn<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {}

export type $AwesomeTagPayload<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  name: 'AwesomeTag'
  objects: {
    underAwesomes: Prisma.$AwesomeItemPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<
    {
      id: string
      index: number | null
      label: string
      desc: string | null
      color: string | null
      icon: string | null
      createdAt: Date
      updatedAt: Date
    },
    ExtArgs['result']['awesomeTag']
  >
  composites: {}
}

export type AwesomeTagGetPayload<S extends boolean | null | undefined | AwesomeTagDefaultArgs> =
  runtime.Types.Result.GetResult<Prisma.$AwesomeTagPayload, S>

export type AwesomeTagCountArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = Omit<AwesomeTagFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
  select?: AwesomeTagCountAggregateInputType | true
}

export interface AwesomeTagDelegate<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
  GlobalOmitOptions = {},
> {
  [K: symbol]: {
    types: Prisma.TypeMap<ExtArgs>['model']['AwesomeTag']
    meta: { name: 'AwesomeTag' }
  }
  /**
   * Find zero or one AwesomeTag that matches the filter.
   * @param {AwesomeTagFindUniqueArgs} args - Arguments to find a AwesomeTag
   * @example
   * // Get one AwesomeTag
   * const awesomeTag = await prisma.awesomeTag.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends AwesomeTagFindUniqueArgs>(
    args: Prisma.SelectSubset<T, AwesomeTagFindUniqueArgs<ExtArgs>>
  ): Prisma.Prisma__AwesomeTagClient<
    runtime.Types.Result.GetResult<
      Prisma.$AwesomeTagPayload<ExtArgs>,
      T,
      'findUnique',
      GlobalOmitOptions
    > | null,
    null,
    ExtArgs,
    GlobalOmitOptions
  >

  /**
   * Find one AwesomeTag that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {AwesomeTagFindUniqueOrThrowArgs} args - Arguments to find a AwesomeTag
   * @example
   * // Get one AwesomeTag
   * const awesomeTag = await prisma.awesomeTag.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends AwesomeTagFindUniqueOrThrowArgs>(
    args: Prisma.SelectSubset<T, AwesomeTagFindUniqueOrThrowArgs<ExtArgs>>
  ): Prisma.Prisma__AwesomeTagClient<
    runtime.Types.Result.GetResult<
      Prisma.$AwesomeTagPayload<ExtArgs>,
      T,
      'findUniqueOrThrow',
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >

  /**
   * Find the first AwesomeTag that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AwesomeTagFindFirstArgs} args - Arguments to find a AwesomeTag
   * @example
   * // Get one AwesomeTag
   * const awesomeTag = await prisma.awesomeTag.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends AwesomeTagFindFirstArgs>(
    args?: Prisma.SelectSubset<T, AwesomeTagFindFirstArgs<ExtArgs>>
  ): Prisma.Prisma__AwesomeTagClient<
    runtime.Types.Result.GetResult<
      Prisma.$AwesomeTagPayload<ExtArgs>,
      T,
      'findFirst',
      GlobalOmitOptions
    > | null,
    null,
    ExtArgs,
    GlobalOmitOptions
  >

  /**
   * Find the first AwesomeTag that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AwesomeTagFindFirstOrThrowArgs} args - Arguments to find a AwesomeTag
   * @example
   * // Get one AwesomeTag
   * const awesomeTag = await prisma.awesomeTag.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends AwesomeTagFindFirstOrThrowArgs>(
    args?: Prisma.SelectSubset<T, AwesomeTagFindFirstOrThrowArgs<ExtArgs>>
  ): Prisma.Prisma__AwesomeTagClient<
    runtime.Types.Result.GetResult<
      Prisma.$AwesomeTagPayload<ExtArgs>,
      T,
      'findFirstOrThrow',
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >

  /**
   * Find zero or more AwesomeTags that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AwesomeTagFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all AwesomeTags
   * const awesomeTags = await prisma.awesomeTag.findMany()
   *
   * // Get first 10 AwesomeTags
   * const awesomeTags = await prisma.awesomeTag.findMany({ take: 10 })
   *
   * // Only select the `id`
   * const awesomeTagWithIdOnly = await prisma.awesomeTag.findMany({ select: { id: true } })
   *
   */
  findMany<T extends AwesomeTagFindManyArgs>(
    args?: Prisma.SelectSubset<T, AwesomeTagFindManyArgs<ExtArgs>>
  ): Prisma.PrismaPromise<
    runtime.Types.Result.GetResult<
      Prisma.$AwesomeTagPayload<ExtArgs>,
      T,
      'findMany',
      GlobalOmitOptions
    >
  >

  /**
   * Create a AwesomeTag.
   * @param {AwesomeTagCreateArgs} args - Arguments to create a AwesomeTag.
   * @example
   * // Create one AwesomeTag
   * const AwesomeTag = await prisma.awesomeTag.create({
   *   data: {
   *     // ... data to create a AwesomeTag
   *   }
   * })
   *
   */
  create<T extends AwesomeTagCreateArgs>(
    args: Prisma.SelectSubset<T, AwesomeTagCreateArgs<ExtArgs>>
  ): Prisma.Prisma__AwesomeTagClient<
    runtime.Types.Result.GetResult<
      Prisma.$AwesomeTagPayload<ExtArgs>,
      T,
      'create',
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >

  /**
   * Create many AwesomeTags.
   * @param {AwesomeTagCreateManyArgs} args - Arguments to create many AwesomeTags.
   * @example
   * // Create many AwesomeTags
   * const awesomeTag = await prisma.awesomeTag.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *
   */
  createMany<T extends AwesomeTagCreateManyArgs>(
    args?: Prisma.SelectSubset<T, AwesomeTagCreateManyArgs<ExtArgs>>
  ): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many AwesomeTags and returns the data saved in the database.
   * @param {AwesomeTagCreateManyAndReturnArgs} args - Arguments to create many AwesomeTags.
   * @example
   * // Create many AwesomeTags
   * const awesomeTag = await prisma.awesomeTag.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *
   * // Create many AwesomeTags and only return the `id`
   * const awesomeTagWithIdOnly = await prisma.awesomeTag.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   *
   */
  createManyAndReturn<T extends AwesomeTagCreateManyAndReturnArgs>(
    args?: Prisma.SelectSubset<T, AwesomeTagCreateManyAndReturnArgs<ExtArgs>>
  ): Prisma.PrismaPromise<
    runtime.Types.Result.GetResult<
      Prisma.$AwesomeTagPayload<ExtArgs>,
      T,
      'createManyAndReturn',
      GlobalOmitOptions
    >
  >

  /**
   * Delete a AwesomeTag.
   * @param {AwesomeTagDeleteArgs} args - Arguments to delete one AwesomeTag.
   * @example
   * // Delete one AwesomeTag
   * const AwesomeTag = await prisma.awesomeTag.delete({
   *   where: {
   *     // ... filter to delete one AwesomeTag
   *   }
   * })
   *
   */
  delete<T extends AwesomeTagDeleteArgs>(
    args: Prisma.SelectSubset<T, AwesomeTagDeleteArgs<ExtArgs>>
  ): Prisma.Prisma__AwesomeTagClient<
    runtime.Types.Result.GetResult<
      Prisma.$AwesomeTagPayload<ExtArgs>,
      T,
      'delete',
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >

  /**
   * Update one AwesomeTag.
   * @param {AwesomeTagUpdateArgs} args - Arguments to update one AwesomeTag.
   * @example
   * // Update one AwesomeTag
   * const awesomeTag = await prisma.awesomeTag.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   *
   */
  update<T extends AwesomeTagUpdateArgs>(
    args: Prisma.SelectSubset<T, AwesomeTagUpdateArgs<ExtArgs>>
  ): Prisma.Prisma__AwesomeTagClient<
    runtime.Types.Result.GetResult<
      Prisma.$AwesomeTagPayload<ExtArgs>,
      T,
      'update',
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >

  /**
   * Delete zero or more AwesomeTags.
   * @param {AwesomeTagDeleteManyArgs} args - Arguments to filter AwesomeTags to delete.
   * @example
   * // Delete a few AwesomeTags
   * const { count } = await prisma.awesomeTag.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   *
   */
  deleteMany<T extends AwesomeTagDeleteManyArgs>(
    args?: Prisma.SelectSubset<T, AwesomeTagDeleteManyArgs<ExtArgs>>
  ): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more AwesomeTags.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AwesomeTagUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many AwesomeTags
   * const awesomeTag = await prisma.awesomeTag.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   *
   */
  updateMany<T extends AwesomeTagUpdateManyArgs>(
    args: Prisma.SelectSubset<T, AwesomeTagUpdateManyArgs<ExtArgs>>
  ): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more AwesomeTags and returns the data updated in the database.
   * @param {AwesomeTagUpdateManyAndReturnArgs} args - Arguments to update many AwesomeTags.
   * @example
   * // Update many AwesomeTags
   * const awesomeTag = await prisma.awesomeTag.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *
   * // Update zero or more AwesomeTags and only return the `id`
   * const awesomeTagWithIdOnly = await prisma.awesomeTag.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   *
   */
  updateManyAndReturn<T extends AwesomeTagUpdateManyAndReturnArgs>(
    args: Prisma.SelectSubset<T, AwesomeTagUpdateManyAndReturnArgs<ExtArgs>>
  ): Prisma.PrismaPromise<
    runtime.Types.Result.GetResult<
      Prisma.$AwesomeTagPayload<ExtArgs>,
      T,
      'updateManyAndReturn',
      GlobalOmitOptions
    >
  >

  /**
   * Create or update one AwesomeTag.
   * @param {AwesomeTagUpsertArgs} args - Arguments to update or create a AwesomeTag.
   * @example
   * // Update or create a AwesomeTag
   * const awesomeTag = await prisma.awesomeTag.upsert({
   *   create: {
   *     // ... data to create a AwesomeTag
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the AwesomeTag we want to update
   *   }
   * })
   */
  upsert<T extends AwesomeTagUpsertArgs>(
    args: Prisma.SelectSubset<T, AwesomeTagUpsertArgs<ExtArgs>>
  ): Prisma.Prisma__AwesomeTagClient<
    runtime.Types.Result.GetResult<
      Prisma.$AwesomeTagPayload<ExtArgs>,
      T,
      'upsert',
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >

  /**
   * Count the number of AwesomeTags.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AwesomeTagCountArgs} args - Arguments to filter AwesomeTags to count.
   * @example
   * // Count the number of AwesomeTags
   * const count = await prisma.awesomeTag.count({
   *   where: {
   *     // ... the filter for the AwesomeTags we want to count
   *   }
   * })
   **/
  count<T extends AwesomeTagCountArgs>(
    args?: Prisma.Subset<T, AwesomeTagCountArgs>
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], AwesomeTagCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a AwesomeTag.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AwesomeTagAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
   **/
  aggregate<T extends AwesomeTagAggregateArgs>(
    args: Prisma.Subset<T, AwesomeTagAggregateArgs>
  ): Prisma.PrismaPromise<GetAwesomeTagAggregateType<T>>

  /**
   * Group by AwesomeTag.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AwesomeTagGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   *
   **/
  groupBy<
    T extends AwesomeTagGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: AwesomeTagGroupByArgs['orderBy'] }
      : { orderBy?: AwesomeTagGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<
      Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>
    >,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
      ? `Error: "by" must not be empty.`
      : HavingValid extends Prisma.False
        ? {
            [P in HavingFields]: P extends ByFields
              ? never
              : P extends string
                ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
                : [Error, 'Field ', P, ` in "having" needs to be provided in "by"`]
          }[HavingFields]
        : 'take' extends Prisma.Keys<T>
          ? 'orderBy' extends Prisma.Keys<T>
            ? ByValid extends Prisma.True
              ? {}
              : {
                  [P in OrderFields]: P extends ByFields
                    ? never
                    : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
                }[OrderFields]
            : 'Error: If you provide "take", you also need to provide "orderBy"'
          : 'skip' extends Prisma.Keys<T>
            ? 'orderBy' extends Prisma.Keys<T>
              ? ByValid extends Prisma.True
                ? {}
                : {
                    [P in OrderFields]: P extends ByFields
                      ? never
                      : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
                  }[OrderFields]
              : 'Error: If you provide "skip", you also need to provide "orderBy"'
            : ByValid extends Prisma.True
              ? {}
              : {
                  [P in OrderFields]: P extends ByFields
                    ? never
                    : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
                }[OrderFields],
  >(
    args: Prisma.SubsetIntersection<T, AwesomeTagGroupByArgs, OrderByArg> & InputErrors
  ): {} extends InputErrors ? GetAwesomeTagGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
  /**
   * Fields of the AwesomeTag model
   */
  readonly fields: AwesomeTagFieldRefs
}

/**
 * The delegate class that acts as a "Promise-like" for AwesomeTag.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__AwesomeTagClient<
  T,
  Null = never,
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
  GlobalOmitOptions = {},
> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: 'PrismaPromise'
  underAwesomes<T extends Prisma.AwesomeTag$underAwesomesArgs<ExtArgs> = {}>(
    args?: Prisma.Subset<T, Prisma.AwesomeTag$underAwesomesArgs<ExtArgs>>
  ): Prisma.PrismaPromise<
    | runtime.Types.Result.GetResult<
        Prisma.$AwesomeItemPayload<ExtArgs>,
        T,
        'findMany',
        GlobalOmitOptions
      >
    | Null
  >
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(
    onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null,
    onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null
  ): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(
    onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null
  ): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}

/**
 * Fields of the AwesomeTag model
 */
export interface AwesomeTagFieldRefs {
  readonly id: Prisma.FieldRef<'AwesomeTag', 'String'>
  readonly index: Prisma.FieldRef<'AwesomeTag', 'Int'>
  readonly label: Prisma.FieldRef<'AwesomeTag', 'String'>
  readonly desc: Prisma.FieldRef<'AwesomeTag', 'String'>
  readonly color: Prisma.FieldRef<'AwesomeTag', 'String'>
  readonly icon: Prisma.FieldRef<'AwesomeTag', 'String'>
  readonly createdAt: Prisma.FieldRef<'AwesomeTag', 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<'AwesomeTag', 'DateTime'>
}

// Custom InputTypes
/**
 * AwesomeTag findUnique
 */
export type AwesomeTagFindUniqueArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the AwesomeTag
   */
  select?: Prisma.AwesomeTagSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AwesomeTag
   */
  omit?: Prisma.AwesomeTagOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AwesomeTagInclude<ExtArgs> | null
  /**
   * Filter, which AwesomeTag to fetch.
   */
  where: Prisma.AwesomeTagWhereUniqueInput
}

/**
 * AwesomeTag findUniqueOrThrow
 */
export type AwesomeTagFindUniqueOrThrowArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the AwesomeTag
   */
  select?: Prisma.AwesomeTagSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AwesomeTag
   */
  omit?: Prisma.AwesomeTagOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AwesomeTagInclude<ExtArgs> | null
  /**
   * Filter, which AwesomeTag to fetch.
   */
  where: Prisma.AwesomeTagWhereUniqueInput
}

/**
 * AwesomeTag findFirst
 */
export type AwesomeTagFindFirstArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the AwesomeTag
   */
  select?: Prisma.AwesomeTagSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AwesomeTag
   */
  omit?: Prisma.AwesomeTagOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AwesomeTagInclude<ExtArgs> | null
  /**
   * Filter, which AwesomeTag to fetch.
   */
  where?: Prisma.AwesomeTagWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   *
   * Determine the order of AwesomeTags to fetch.
   */
  orderBy?: Prisma.AwesomeTagOrderByWithRelationInput | Prisma.AwesomeTagOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   *
   * Sets the position for searching for AwesomeTags.
   */
  cursor?: Prisma.AwesomeTagWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Take `±n` AwesomeTags from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Skip the first `n` AwesomeTags.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   *
   * Filter by unique combinations of AwesomeTags.
   */
  distinct?: Prisma.AwesomeTagScalarFieldEnum | Prisma.AwesomeTagScalarFieldEnum[]
}

/**
 * AwesomeTag findFirstOrThrow
 */
export type AwesomeTagFindFirstOrThrowArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the AwesomeTag
   */
  select?: Prisma.AwesomeTagSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AwesomeTag
   */
  omit?: Prisma.AwesomeTagOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AwesomeTagInclude<ExtArgs> | null
  /**
   * Filter, which AwesomeTag to fetch.
   */
  where?: Prisma.AwesomeTagWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   *
   * Determine the order of AwesomeTags to fetch.
   */
  orderBy?: Prisma.AwesomeTagOrderByWithRelationInput | Prisma.AwesomeTagOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   *
   * Sets the position for searching for AwesomeTags.
   */
  cursor?: Prisma.AwesomeTagWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Take `±n` AwesomeTags from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Skip the first `n` AwesomeTags.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   *
   * Filter by unique combinations of AwesomeTags.
   */
  distinct?: Prisma.AwesomeTagScalarFieldEnum | Prisma.AwesomeTagScalarFieldEnum[]
}

/**
 * AwesomeTag findMany
 */
export type AwesomeTagFindManyArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the AwesomeTag
   */
  select?: Prisma.AwesomeTagSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AwesomeTag
   */
  omit?: Prisma.AwesomeTagOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AwesomeTagInclude<ExtArgs> | null
  /**
   * Filter, which AwesomeTags to fetch.
   */
  where?: Prisma.AwesomeTagWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   *
   * Determine the order of AwesomeTags to fetch.
   */
  orderBy?: Prisma.AwesomeTagOrderByWithRelationInput | Prisma.AwesomeTagOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   *
   * Sets the position for listing AwesomeTags.
   */
  cursor?: Prisma.AwesomeTagWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Take `±n` AwesomeTags from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Skip the first `n` AwesomeTags.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   *
   * Filter by unique combinations of AwesomeTags.
   */
  distinct?: Prisma.AwesomeTagScalarFieldEnum | Prisma.AwesomeTagScalarFieldEnum[]
}

/**
 * AwesomeTag create
 */
export type AwesomeTagCreateArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the AwesomeTag
   */
  select?: Prisma.AwesomeTagSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AwesomeTag
   */
  omit?: Prisma.AwesomeTagOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AwesomeTagInclude<ExtArgs> | null
  /**
   * The data needed to create a AwesomeTag.
   */
  data: Prisma.XOR<Prisma.AwesomeTagCreateInput, Prisma.AwesomeTagUncheckedCreateInput>
}

/**
 * AwesomeTag createMany
 */
export type AwesomeTagCreateManyArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * The data used to create many AwesomeTags.
   */
  data: Prisma.AwesomeTagCreateManyInput | Prisma.AwesomeTagCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * AwesomeTag createManyAndReturn
 */
export type AwesomeTagCreateManyAndReturnArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the AwesomeTag
   */
  select?: Prisma.AwesomeTagSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the AwesomeTag
   */
  omit?: Prisma.AwesomeTagOmit<ExtArgs> | null
  /**
   * The data used to create many AwesomeTags.
   */
  data: Prisma.AwesomeTagCreateManyInput | Prisma.AwesomeTagCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * AwesomeTag update
 */
export type AwesomeTagUpdateArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the AwesomeTag
   */
  select?: Prisma.AwesomeTagSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AwesomeTag
   */
  omit?: Prisma.AwesomeTagOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AwesomeTagInclude<ExtArgs> | null
  /**
   * The data needed to update a AwesomeTag.
   */
  data: Prisma.XOR<Prisma.AwesomeTagUpdateInput, Prisma.AwesomeTagUncheckedUpdateInput>
  /**
   * Choose, which AwesomeTag to update.
   */
  where: Prisma.AwesomeTagWhereUniqueInput
}

/**
 * AwesomeTag updateMany
 */
export type AwesomeTagUpdateManyArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * The data used to update AwesomeTags.
   */
  data: Prisma.XOR<
    Prisma.AwesomeTagUpdateManyMutationInput,
    Prisma.AwesomeTagUncheckedUpdateManyInput
  >
  /**
   * Filter which AwesomeTags to update
   */
  where?: Prisma.AwesomeTagWhereInput
  /**
   * Limit how many AwesomeTags to update.
   */
  limit?: number
}

/**
 * AwesomeTag updateManyAndReturn
 */
export type AwesomeTagUpdateManyAndReturnArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the AwesomeTag
   */
  select?: Prisma.AwesomeTagSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the AwesomeTag
   */
  omit?: Prisma.AwesomeTagOmit<ExtArgs> | null
  /**
   * The data used to update AwesomeTags.
   */
  data: Prisma.XOR<
    Prisma.AwesomeTagUpdateManyMutationInput,
    Prisma.AwesomeTagUncheckedUpdateManyInput
  >
  /**
   * Filter which AwesomeTags to update
   */
  where?: Prisma.AwesomeTagWhereInput
  /**
   * Limit how many AwesomeTags to update.
   */
  limit?: number
}

/**
 * AwesomeTag upsert
 */
export type AwesomeTagUpsertArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the AwesomeTag
   */
  select?: Prisma.AwesomeTagSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AwesomeTag
   */
  omit?: Prisma.AwesomeTagOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AwesomeTagInclude<ExtArgs> | null
  /**
   * The filter to search for the AwesomeTag to update in case it exists.
   */
  where: Prisma.AwesomeTagWhereUniqueInput
  /**
   * In case the AwesomeTag found by the `where` argument doesn't exist, create a new AwesomeTag with this data.
   */
  create: Prisma.XOR<Prisma.AwesomeTagCreateInput, Prisma.AwesomeTagUncheckedCreateInput>
  /**
   * In case the AwesomeTag was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.AwesomeTagUpdateInput, Prisma.AwesomeTagUncheckedUpdateInput>
}

/**
 * AwesomeTag delete
 */
export type AwesomeTagDeleteArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the AwesomeTag
   */
  select?: Prisma.AwesomeTagSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AwesomeTag
   */
  omit?: Prisma.AwesomeTagOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AwesomeTagInclude<ExtArgs> | null
  /**
   * Filter which AwesomeTag to delete.
   */
  where: Prisma.AwesomeTagWhereUniqueInput
}

/**
 * AwesomeTag deleteMany
 */
export type AwesomeTagDeleteManyArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Filter which AwesomeTags to delete
   */
  where?: Prisma.AwesomeTagWhereInput
  /**
   * Limit how many AwesomeTags to delete.
   */
  limit?: number
}

/**
 * AwesomeTag.underAwesomes
 */
export type AwesomeTag$underAwesomesArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the AwesomeItem
   */
  select?: Prisma.AwesomeItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AwesomeItem
   */
  omit?: Prisma.AwesomeItemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AwesomeItemInclude<ExtArgs> | null
  where?: Prisma.AwesomeItemWhereInput
  orderBy?:
    | Prisma.AwesomeItemOrderByWithRelationInput
    | Prisma.AwesomeItemOrderByWithRelationInput[]
  cursor?: Prisma.AwesomeItemWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.AwesomeItemScalarFieldEnum | Prisma.AwesomeItemScalarFieldEnum[]
}

/**
 * AwesomeTag without action
 */
export type AwesomeTagDefaultArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the AwesomeTag
   */
  select?: Prisma.AwesomeTagSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AwesomeTag
   */
  omit?: Prisma.AwesomeTagOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AwesomeTagInclude<ExtArgs> | null
}
