/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck
/*
 * This file exports the `OARobotProfile` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from '@prisma/client/runtime/client'

import type * as $Enums from '../enums'
import type * as Prisma from '../internal/prismaNamespace'

/**
 * Model OARobotProfile
 * OA 机器人档案
 */
export type OARobotProfileModel =
  runtime.Types.Result.DefaultSelection<Prisma.$OARobotProfilePayload>

export type AggregateOARobotProfile = {
  _count: OARobotProfileCountAggregateOutputType | null
  _avg: OARobotProfileAvgAggregateOutputType | null
  _sum: OARobotProfileSumAggregateOutputType | null
  _min: OARobotProfileMinAggregateOutputType | null
  _max: OARobotProfileMaxAggregateOutputType | null
}

export type OARobotProfileAvgAggregateOutputType = {
  index: number | null
}

export type OARobotProfileSumAggregateOutputType = {
  index: number | null
}

export type OARobotProfileMinAggregateOutputType = {
  id: string | null
  index: number | null
  name: string | null
  desc: string | null
  type: $Enums.OARobotType | null
  accessToken: string | null
  secret: string | null
  userId: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type OARobotProfileMaxAggregateOutputType = {
  id: string | null
  index: number | null
  name: string | null
  desc: string | null
  type: $Enums.OARobotType | null
  accessToken: string | null
  secret: string | null
  userId: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type OARobotProfileCountAggregateOutputType = {
  id: number
  index: number
  name: number
  desc: number
  type: number
  accessToken: number
  secret: number
  extraAuthentication: number
  userId: number
  createdAt: number
  updatedAt: number
  _all: number
}

export type OARobotProfileAvgAggregateInputType = {
  index?: true
}

export type OARobotProfileSumAggregateInputType = {
  index?: true
}

export type OARobotProfileMinAggregateInputType = {
  id?: true
  index?: true
  name?: true
  desc?: true
  type?: true
  accessToken?: true
  secret?: true
  userId?: true
  createdAt?: true
  updatedAt?: true
}

export type OARobotProfileMaxAggregateInputType = {
  id?: true
  index?: true
  name?: true
  desc?: true
  type?: true
  accessToken?: true
  secret?: true
  userId?: true
  createdAt?: true
  updatedAt?: true
}

export type OARobotProfileCountAggregateInputType = {
  id?: true
  index?: true
  name?: true
  desc?: true
  type?: true
  accessToken?: true
  secret?: true
  extraAuthentication?: true
  userId?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type OARobotProfileAggregateArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Filter which OARobotProfile to aggregate.
   */
  where?: Prisma.OARobotProfileWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   *
   * Determine the order of OARobotProfiles to fetch.
   */
  orderBy?:
    | Prisma.OARobotProfileOrderByWithRelationInput
    | Prisma.OARobotProfileOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   *
   * Sets the start position
   */
  cursor?: Prisma.OARobotProfileWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Take `±n` OARobotProfiles from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Skip the first `n` OARobotProfiles.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   *
   * Count returned OARobotProfiles
   **/
  _count?: true | OARobotProfileCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   *
   * Select which fields to average
   **/
  _avg?: OARobotProfileAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   *
   * Select which fields to sum
   **/
  _sum?: OARobotProfileSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   *
   * Select which fields to find the minimum value
   **/
  _min?: OARobotProfileMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   *
   * Select which fields to find the maximum value
   **/
  _max?: OARobotProfileMaxAggregateInputType
}

export type GetOARobotProfileAggregateType<T extends OARobotProfileAggregateArgs> = {
  [P in keyof T & keyof AggregateOARobotProfile]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateOARobotProfile[P]>
    : Prisma.GetScalarType<T[P], AggregateOARobotProfile[P]>
}

export type OARobotProfileGroupByArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  where?: Prisma.OARobotProfileWhereInput
  orderBy?:
    | Prisma.OARobotProfileOrderByWithAggregationInput
    | Prisma.OARobotProfileOrderByWithAggregationInput[]
  by: Prisma.OARobotProfileScalarFieldEnum[] | Prisma.OARobotProfileScalarFieldEnum
  having?: Prisma.OARobotProfileScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: OARobotProfileCountAggregateInputType | true
  _avg?: OARobotProfileAvgAggregateInputType
  _sum?: OARobotProfileSumAggregateInputType
  _min?: OARobotProfileMinAggregateInputType
  _max?: OARobotProfileMaxAggregateInputType
}

export type OARobotProfileGroupByOutputType = {
  id: string
  index: number | null
  name: string
  desc: string | null
  type: $Enums.OARobotType
  accessToken: string | null
  secret: string | null
  extraAuthentication: runtime.JsonValue | null
  userId: string | null
  createdAt: Date
  updatedAt: Date
  _count: OARobotProfileCountAggregateOutputType | null
  _avg: OARobotProfileAvgAggregateOutputType | null
  _sum: OARobotProfileSumAggregateOutputType | null
  _min: OARobotProfileMinAggregateOutputType | null
  _max: OARobotProfileMaxAggregateOutputType | null
}

export type GetOARobotProfileGroupByPayload<T extends OARobotProfileGroupByArgs> =
  Prisma.PrismaPromise<
    Array<
      Prisma.PickEnumerable<OARobotProfileGroupByOutputType, T['by']> & {
        [P in keyof T & keyof OARobotProfileGroupByOutputType]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], OARobotProfileGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], OARobotProfileGroupByOutputType[P]>
      }
    >
  >

export type OARobotProfileWhereInput = {
  AND?: Prisma.OARobotProfileWhereInput | Prisma.OARobotProfileWhereInput[]
  OR?: Prisma.OARobotProfileWhereInput[]
  NOT?: Prisma.OARobotProfileWhereInput | Prisma.OARobotProfileWhereInput[]
  id?: Prisma.StringFilter<'OARobotProfile'> | string
  index?: Prisma.IntNullableFilter<'OARobotProfile'> | number | null
  name?: Prisma.StringFilter<'OARobotProfile'> | string
  desc?: Prisma.StringNullableFilter<'OARobotProfile'> | string | null
  type?: Prisma.EnumOARobotTypeFilter<'OARobotProfile'> | $Enums.OARobotType
  accessToken?: Prisma.StringNullableFilter<'OARobotProfile'> | string | null
  secret?: Prisma.StringNullableFilter<'OARobotProfile'> | string | null
  extraAuthentication?: Prisma.JsonNullableFilter<'OARobotProfile'>
  userId?: Prisma.StringNullableFilter<'OARobotProfile'> | string | null
  createdAt?: Prisma.DateTimeFilter<'OARobotProfile'> | Date | string
  updatedAt?: Prisma.DateTimeFilter<'OARobotProfile'> | Date | string
  author?: Prisma.XOR<Prisma.UserNullableScalarRelationFilter, Prisma.UserWhereInput> | null
}

export type OARobotProfileOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  index?: Prisma.SortOrderInput | Prisma.SortOrder
  name?: Prisma.SortOrder
  desc?: Prisma.SortOrderInput | Prisma.SortOrder
  type?: Prisma.SortOrder
  accessToken?: Prisma.SortOrderInput | Prisma.SortOrder
  secret?: Prisma.SortOrderInput | Prisma.SortOrder
  extraAuthentication?: Prisma.SortOrderInput | Prisma.SortOrder
  userId?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  author?: Prisma.UserOrderByWithRelationInput
}

export type OARobotProfileWhereUniqueInput = Prisma.AtLeast<
  {
    id?: string
    AND?: Prisma.OARobotProfileWhereInput | Prisma.OARobotProfileWhereInput[]
    OR?: Prisma.OARobotProfileWhereInput[]
    NOT?: Prisma.OARobotProfileWhereInput | Prisma.OARobotProfileWhereInput[]
    index?: Prisma.IntNullableFilter<'OARobotProfile'> | number | null
    name?: Prisma.StringFilter<'OARobotProfile'> | string
    desc?: Prisma.StringNullableFilter<'OARobotProfile'> | string | null
    type?: Prisma.EnumOARobotTypeFilter<'OARobotProfile'> | $Enums.OARobotType
    accessToken?: Prisma.StringNullableFilter<'OARobotProfile'> | string | null
    secret?: Prisma.StringNullableFilter<'OARobotProfile'> | string | null
    extraAuthentication?: Prisma.JsonNullableFilter<'OARobotProfile'>
    userId?: Prisma.StringNullableFilter<'OARobotProfile'> | string | null
    createdAt?: Prisma.DateTimeFilter<'OARobotProfile'> | Date | string
    updatedAt?: Prisma.DateTimeFilter<'OARobotProfile'> | Date | string
    author?: Prisma.XOR<Prisma.UserNullableScalarRelationFilter, Prisma.UserWhereInput> | null
  },
  'id'
>

export type OARobotProfileOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  index?: Prisma.SortOrderInput | Prisma.SortOrder
  name?: Prisma.SortOrder
  desc?: Prisma.SortOrderInput | Prisma.SortOrder
  type?: Prisma.SortOrder
  accessToken?: Prisma.SortOrderInput | Prisma.SortOrder
  secret?: Prisma.SortOrderInput | Prisma.SortOrder
  extraAuthentication?: Prisma.SortOrderInput | Prisma.SortOrder
  userId?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.OARobotProfileCountOrderByAggregateInput
  _avg?: Prisma.OARobotProfileAvgOrderByAggregateInput
  _max?: Prisma.OARobotProfileMaxOrderByAggregateInput
  _min?: Prisma.OARobotProfileMinOrderByAggregateInput
  _sum?: Prisma.OARobotProfileSumOrderByAggregateInput
}

export type OARobotProfileScalarWhereWithAggregatesInput = {
  AND?:
    | Prisma.OARobotProfileScalarWhereWithAggregatesInput
    | Prisma.OARobotProfileScalarWhereWithAggregatesInput[]
  OR?: Prisma.OARobotProfileScalarWhereWithAggregatesInput[]
  NOT?:
    | Prisma.OARobotProfileScalarWhereWithAggregatesInput
    | Prisma.OARobotProfileScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<'OARobotProfile'> | string
  index?: Prisma.IntNullableWithAggregatesFilter<'OARobotProfile'> | number | null
  name?: Prisma.StringWithAggregatesFilter<'OARobotProfile'> | string
  desc?: Prisma.StringNullableWithAggregatesFilter<'OARobotProfile'> | string | null
  type?: Prisma.EnumOARobotTypeWithAggregatesFilter<'OARobotProfile'> | $Enums.OARobotType
  accessToken?: Prisma.StringNullableWithAggregatesFilter<'OARobotProfile'> | string | null
  secret?: Prisma.StringNullableWithAggregatesFilter<'OARobotProfile'> | string | null
  extraAuthentication?: Prisma.JsonNullableWithAggregatesFilter<'OARobotProfile'>
  userId?: Prisma.StringNullableWithAggregatesFilter<'OARobotProfile'> | string | null
  createdAt?: Prisma.DateTimeWithAggregatesFilter<'OARobotProfile'> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<'OARobotProfile'> | Date | string
}

export type OARobotProfileCreateInput = {
  id?: string
  index?: number | null
  name: string
  desc?: string | null
  type: $Enums.OARobotType
  accessToken?: string | null
  secret?: string | null
  extraAuthentication?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Date | string
  updatedAt?: Date | string
  author?: Prisma.UserCreateNestedOneWithoutOarobotProfilesInput
}

export type OARobotProfileUncheckedCreateInput = {
  id?: string
  index?: number | null
  name: string
  desc?: string | null
  type: $Enums.OARobotType
  accessToken?: string | null
  secret?: string | null
  extraAuthentication?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  userId?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type OARobotProfileUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  index?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  name?: Prisma.StringFieldUpdateOperationsInput | string
  desc?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  type?: Prisma.EnumOARobotTypeFieldUpdateOperationsInput | $Enums.OARobotType
  accessToken?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  secret?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  extraAuthentication?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  author?: Prisma.UserUpdateOneWithoutOarobotProfilesNestedInput
}

export type OARobotProfileUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  index?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  name?: Prisma.StringFieldUpdateOperationsInput | string
  desc?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  type?: Prisma.EnumOARobotTypeFieldUpdateOperationsInput | $Enums.OARobotType
  accessToken?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  secret?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  extraAuthentication?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  userId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type OARobotProfileCreateManyInput = {
  id?: string
  index?: number | null
  name: string
  desc?: string | null
  type: $Enums.OARobotType
  accessToken?: string | null
  secret?: string | null
  extraAuthentication?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  userId?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type OARobotProfileUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  index?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  name?: Prisma.StringFieldUpdateOperationsInput | string
  desc?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  type?: Prisma.EnumOARobotTypeFieldUpdateOperationsInput | $Enums.OARobotType
  accessToken?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  secret?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  extraAuthentication?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type OARobotProfileUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  index?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  name?: Prisma.StringFieldUpdateOperationsInput | string
  desc?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  type?: Prisma.EnumOARobotTypeFieldUpdateOperationsInput | $Enums.OARobotType
  accessToken?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  secret?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  extraAuthentication?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  userId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type OARobotProfileCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  index?: Prisma.SortOrder
  name?: Prisma.SortOrder
  desc?: Prisma.SortOrder
  type?: Prisma.SortOrder
  accessToken?: Prisma.SortOrder
  secret?: Prisma.SortOrder
  extraAuthentication?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type OARobotProfileAvgOrderByAggregateInput = {
  index?: Prisma.SortOrder
}

export type OARobotProfileMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  index?: Prisma.SortOrder
  name?: Prisma.SortOrder
  desc?: Prisma.SortOrder
  type?: Prisma.SortOrder
  accessToken?: Prisma.SortOrder
  secret?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type OARobotProfileMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  index?: Prisma.SortOrder
  name?: Prisma.SortOrder
  desc?: Prisma.SortOrder
  type?: Prisma.SortOrder
  accessToken?: Prisma.SortOrder
  secret?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type OARobotProfileSumOrderByAggregateInput = {
  index?: Prisma.SortOrder
}

export type OARobotProfileListRelationFilter = {
  every?: Prisma.OARobotProfileWhereInput
  some?: Prisma.OARobotProfileWhereInput
  none?: Prisma.OARobotProfileWhereInput
}

export type OARobotProfileOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type EnumOARobotTypeFieldUpdateOperationsInput = {
  set?: $Enums.OARobotType
}

export type OARobotProfileCreateNestedManyWithoutAuthorInput = {
  create?:
    | Prisma.XOR<
        Prisma.OARobotProfileCreateWithoutAuthorInput,
        Prisma.OARobotProfileUncheckedCreateWithoutAuthorInput
      >
    | Prisma.OARobotProfileCreateWithoutAuthorInput[]
    | Prisma.OARobotProfileUncheckedCreateWithoutAuthorInput[]
  connectOrCreate?:
    | Prisma.OARobotProfileCreateOrConnectWithoutAuthorInput
    | Prisma.OARobotProfileCreateOrConnectWithoutAuthorInput[]
  createMany?: Prisma.OARobotProfileCreateManyAuthorInputEnvelope
  connect?: Prisma.OARobotProfileWhereUniqueInput | Prisma.OARobotProfileWhereUniqueInput[]
}

export type OARobotProfileUncheckedCreateNestedManyWithoutAuthorInput = {
  create?:
    | Prisma.XOR<
        Prisma.OARobotProfileCreateWithoutAuthorInput,
        Prisma.OARobotProfileUncheckedCreateWithoutAuthorInput
      >
    | Prisma.OARobotProfileCreateWithoutAuthorInput[]
    | Prisma.OARobotProfileUncheckedCreateWithoutAuthorInput[]
  connectOrCreate?:
    | Prisma.OARobotProfileCreateOrConnectWithoutAuthorInput
    | Prisma.OARobotProfileCreateOrConnectWithoutAuthorInput[]
  createMany?: Prisma.OARobotProfileCreateManyAuthorInputEnvelope
  connect?: Prisma.OARobotProfileWhereUniqueInput | Prisma.OARobotProfileWhereUniqueInput[]
}

export type OARobotProfileUpdateManyWithoutAuthorNestedInput = {
  create?:
    | Prisma.XOR<
        Prisma.OARobotProfileCreateWithoutAuthorInput,
        Prisma.OARobotProfileUncheckedCreateWithoutAuthorInput
      >
    | Prisma.OARobotProfileCreateWithoutAuthorInput[]
    | Prisma.OARobotProfileUncheckedCreateWithoutAuthorInput[]
  connectOrCreate?:
    | Prisma.OARobotProfileCreateOrConnectWithoutAuthorInput
    | Prisma.OARobotProfileCreateOrConnectWithoutAuthorInput[]
  upsert?:
    | Prisma.OARobotProfileUpsertWithWhereUniqueWithoutAuthorInput
    | Prisma.OARobotProfileUpsertWithWhereUniqueWithoutAuthorInput[]
  createMany?: Prisma.OARobotProfileCreateManyAuthorInputEnvelope
  set?: Prisma.OARobotProfileWhereUniqueInput | Prisma.OARobotProfileWhereUniqueInput[]
  disconnect?: Prisma.OARobotProfileWhereUniqueInput | Prisma.OARobotProfileWhereUniqueInput[]
  delete?: Prisma.OARobotProfileWhereUniqueInput | Prisma.OARobotProfileWhereUniqueInput[]
  connect?: Prisma.OARobotProfileWhereUniqueInput | Prisma.OARobotProfileWhereUniqueInput[]
  update?:
    | Prisma.OARobotProfileUpdateWithWhereUniqueWithoutAuthorInput
    | Prisma.OARobotProfileUpdateWithWhereUniqueWithoutAuthorInput[]
  updateMany?:
    | Prisma.OARobotProfileUpdateManyWithWhereWithoutAuthorInput
    | Prisma.OARobotProfileUpdateManyWithWhereWithoutAuthorInput[]
  deleteMany?: Prisma.OARobotProfileScalarWhereInput | Prisma.OARobotProfileScalarWhereInput[]
}

export type OARobotProfileUncheckedUpdateManyWithoutAuthorNestedInput = {
  create?:
    | Prisma.XOR<
        Prisma.OARobotProfileCreateWithoutAuthorInput,
        Prisma.OARobotProfileUncheckedCreateWithoutAuthorInput
      >
    | Prisma.OARobotProfileCreateWithoutAuthorInput[]
    | Prisma.OARobotProfileUncheckedCreateWithoutAuthorInput[]
  connectOrCreate?:
    | Prisma.OARobotProfileCreateOrConnectWithoutAuthorInput
    | Prisma.OARobotProfileCreateOrConnectWithoutAuthorInput[]
  upsert?:
    | Prisma.OARobotProfileUpsertWithWhereUniqueWithoutAuthorInput
    | Prisma.OARobotProfileUpsertWithWhereUniqueWithoutAuthorInput[]
  createMany?: Prisma.OARobotProfileCreateManyAuthorInputEnvelope
  set?: Prisma.OARobotProfileWhereUniqueInput | Prisma.OARobotProfileWhereUniqueInput[]
  disconnect?: Prisma.OARobotProfileWhereUniqueInput | Prisma.OARobotProfileWhereUniqueInput[]
  delete?: Prisma.OARobotProfileWhereUniqueInput | Prisma.OARobotProfileWhereUniqueInput[]
  connect?: Prisma.OARobotProfileWhereUniqueInput | Prisma.OARobotProfileWhereUniqueInput[]
  update?:
    | Prisma.OARobotProfileUpdateWithWhereUniqueWithoutAuthorInput
    | Prisma.OARobotProfileUpdateWithWhereUniqueWithoutAuthorInput[]
  updateMany?:
    | Prisma.OARobotProfileUpdateManyWithWhereWithoutAuthorInput
    | Prisma.OARobotProfileUpdateManyWithWhereWithoutAuthorInput[]
  deleteMany?: Prisma.OARobotProfileScalarWhereInput | Prisma.OARobotProfileScalarWhereInput[]
}

export type OARobotProfileCreateWithoutAuthorInput = {
  id?: string
  index?: number | null
  name: string
  desc?: string | null
  type: $Enums.OARobotType
  accessToken?: string | null
  secret?: string | null
  extraAuthentication?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type OARobotProfileUncheckedCreateWithoutAuthorInput = {
  id?: string
  index?: number | null
  name: string
  desc?: string | null
  type: $Enums.OARobotType
  accessToken?: string | null
  secret?: string | null
  extraAuthentication?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type OARobotProfileCreateOrConnectWithoutAuthorInput = {
  where: Prisma.OARobotProfileWhereUniqueInput
  create: Prisma.XOR<
    Prisma.OARobotProfileCreateWithoutAuthorInput,
    Prisma.OARobotProfileUncheckedCreateWithoutAuthorInput
  >
}

export type OARobotProfileCreateManyAuthorInputEnvelope = {
  data: Prisma.OARobotProfileCreateManyAuthorInput | Prisma.OARobotProfileCreateManyAuthorInput[]
  skipDuplicates?: boolean
}

export type OARobotProfileUpsertWithWhereUniqueWithoutAuthorInput = {
  where: Prisma.OARobotProfileWhereUniqueInput
  update: Prisma.XOR<
    Prisma.OARobotProfileUpdateWithoutAuthorInput,
    Prisma.OARobotProfileUncheckedUpdateWithoutAuthorInput
  >
  create: Prisma.XOR<
    Prisma.OARobotProfileCreateWithoutAuthorInput,
    Prisma.OARobotProfileUncheckedCreateWithoutAuthorInput
  >
}

export type OARobotProfileUpdateWithWhereUniqueWithoutAuthorInput = {
  where: Prisma.OARobotProfileWhereUniqueInput
  data: Prisma.XOR<
    Prisma.OARobotProfileUpdateWithoutAuthorInput,
    Prisma.OARobotProfileUncheckedUpdateWithoutAuthorInput
  >
}

export type OARobotProfileUpdateManyWithWhereWithoutAuthorInput = {
  where: Prisma.OARobotProfileScalarWhereInput
  data: Prisma.XOR<
    Prisma.OARobotProfileUpdateManyMutationInput,
    Prisma.OARobotProfileUncheckedUpdateManyWithoutAuthorInput
  >
}

export type OARobotProfileScalarWhereInput = {
  AND?: Prisma.OARobotProfileScalarWhereInput | Prisma.OARobotProfileScalarWhereInput[]
  OR?: Prisma.OARobotProfileScalarWhereInput[]
  NOT?: Prisma.OARobotProfileScalarWhereInput | Prisma.OARobotProfileScalarWhereInput[]
  id?: Prisma.StringFilter<'OARobotProfile'> | string
  index?: Prisma.IntNullableFilter<'OARobotProfile'> | number | null
  name?: Prisma.StringFilter<'OARobotProfile'> | string
  desc?: Prisma.StringNullableFilter<'OARobotProfile'> | string | null
  type?: Prisma.EnumOARobotTypeFilter<'OARobotProfile'> | $Enums.OARobotType
  accessToken?: Prisma.StringNullableFilter<'OARobotProfile'> | string | null
  secret?: Prisma.StringNullableFilter<'OARobotProfile'> | string | null
  extraAuthentication?: Prisma.JsonNullableFilter<'OARobotProfile'>
  userId?: Prisma.StringNullableFilter<'OARobotProfile'> | string | null
  createdAt?: Prisma.DateTimeFilter<'OARobotProfile'> | Date | string
  updatedAt?: Prisma.DateTimeFilter<'OARobotProfile'> | Date | string
}

export type OARobotProfileCreateManyAuthorInput = {
  id?: string
  index?: number | null
  name: string
  desc?: string | null
  type: $Enums.OARobotType
  accessToken?: string | null
  secret?: string | null
  extraAuthentication?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type OARobotProfileUpdateWithoutAuthorInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  index?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  name?: Prisma.StringFieldUpdateOperationsInput | string
  desc?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  type?: Prisma.EnumOARobotTypeFieldUpdateOperationsInput | $Enums.OARobotType
  accessToken?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  secret?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  extraAuthentication?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type OARobotProfileUncheckedUpdateWithoutAuthorInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  index?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  name?: Prisma.StringFieldUpdateOperationsInput | string
  desc?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  type?: Prisma.EnumOARobotTypeFieldUpdateOperationsInput | $Enums.OARobotType
  accessToken?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  secret?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  extraAuthentication?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type OARobotProfileUncheckedUpdateManyWithoutAuthorInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  index?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  name?: Prisma.StringFieldUpdateOperationsInput | string
  desc?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  type?: Prisma.EnumOARobotTypeFieldUpdateOperationsInput | $Enums.OARobotType
  accessToken?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  secret?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  extraAuthentication?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type OARobotProfileSelect<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = runtime.Types.Extensions.GetSelect<
  {
    id?: boolean
    index?: boolean
    name?: boolean
    desc?: boolean
    type?: boolean
    accessToken?: boolean
    secret?: boolean
    extraAuthentication?: boolean
    userId?: boolean
    createdAt?: boolean
    updatedAt?: boolean
    author?: boolean | Prisma.OARobotProfile$authorArgs<ExtArgs>
  },
  ExtArgs['result']['oARobotProfile']
>

export type OARobotProfileSelectCreateManyAndReturn<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = runtime.Types.Extensions.GetSelect<
  {
    id?: boolean
    index?: boolean
    name?: boolean
    desc?: boolean
    type?: boolean
    accessToken?: boolean
    secret?: boolean
    extraAuthentication?: boolean
    userId?: boolean
    createdAt?: boolean
    updatedAt?: boolean
    author?: boolean | Prisma.OARobotProfile$authorArgs<ExtArgs>
  },
  ExtArgs['result']['oARobotProfile']
>

export type OARobotProfileSelectUpdateManyAndReturn<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = runtime.Types.Extensions.GetSelect<
  {
    id?: boolean
    index?: boolean
    name?: boolean
    desc?: boolean
    type?: boolean
    accessToken?: boolean
    secret?: boolean
    extraAuthentication?: boolean
    userId?: boolean
    createdAt?: boolean
    updatedAt?: boolean
    author?: boolean | Prisma.OARobotProfile$authorArgs<ExtArgs>
  },
  ExtArgs['result']['oARobotProfile']
>

export type OARobotProfileSelectScalar = {
  id?: boolean
  index?: boolean
  name?: boolean
  desc?: boolean
  type?: boolean
  accessToken?: boolean
  secret?: boolean
  extraAuthentication?: boolean
  userId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type OARobotProfileOmit<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = runtime.Types.Extensions.GetOmit<
  | 'id'
  | 'index'
  | 'name'
  | 'desc'
  | 'type'
  | 'accessToken'
  | 'secret'
  | 'extraAuthentication'
  | 'userId'
  | 'createdAt'
  | 'updatedAt',
  ExtArgs['result']['oARobotProfile']
>
export type OARobotProfileInclude<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  author?: boolean | Prisma.OARobotProfile$authorArgs<ExtArgs>
}
export type OARobotProfileIncludeCreateManyAndReturn<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  author?: boolean | Prisma.OARobotProfile$authorArgs<ExtArgs>
}
export type OARobotProfileIncludeUpdateManyAndReturn<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  author?: boolean | Prisma.OARobotProfile$authorArgs<ExtArgs>
}

export type $OARobotProfilePayload<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  name: 'OARobotProfile'
  objects: {
    author: Prisma.$UserPayload<ExtArgs> | null
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<
    {
      id: string
      index: number | null
      name: string
      desc: string | null
      type: $Enums.OARobotType
      accessToken: string | null
      secret: string | null
      /**
       * 额外配置，例如飞书所需使用的额外令牌
       */
      extraAuthentication: runtime.JsonValue | null
      userId: string | null
      createdAt: Date
      updatedAt: Date
    },
    ExtArgs['result']['oARobotProfile']
  >
  composites: {}
}

export type OARobotProfileGetPayload<
  S extends boolean | null | undefined | OARobotProfileDefaultArgs,
> = runtime.Types.Result.GetResult<Prisma.$OARobotProfilePayload, S>

export type OARobotProfileCountArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = Omit<OARobotProfileFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
  select?: OARobotProfileCountAggregateInputType | true
}

export interface OARobotProfileDelegate<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
  GlobalOmitOptions = {},
> {
  [K: symbol]: {
    types: Prisma.TypeMap<ExtArgs>['model']['OARobotProfile']
    meta: { name: 'OARobotProfile' }
  }
  /**
   * Find zero or one OARobotProfile that matches the filter.
   * @param {OARobotProfileFindUniqueArgs} args - Arguments to find a OARobotProfile
   * @example
   * // Get one OARobotProfile
   * const oARobotProfile = await prisma.oARobotProfile.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends OARobotProfileFindUniqueArgs>(
    args: Prisma.SelectSubset<T, OARobotProfileFindUniqueArgs<ExtArgs>>
  ): Prisma.Prisma__OARobotProfileClient<
    runtime.Types.Result.GetResult<
      Prisma.$OARobotProfilePayload<ExtArgs>,
      T,
      'findUnique',
      GlobalOmitOptions
    > | null,
    null,
    ExtArgs,
    GlobalOmitOptions
  >

  /**
   * Find one OARobotProfile that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {OARobotProfileFindUniqueOrThrowArgs} args - Arguments to find a OARobotProfile
   * @example
   * // Get one OARobotProfile
   * const oARobotProfile = await prisma.oARobotProfile.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends OARobotProfileFindUniqueOrThrowArgs>(
    args: Prisma.SelectSubset<T, OARobotProfileFindUniqueOrThrowArgs<ExtArgs>>
  ): Prisma.Prisma__OARobotProfileClient<
    runtime.Types.Result.GetResult<
      Prisma.$OARobotProfilePayload<ExtArgs>,
      T,
      'findUniqueOrThrow',
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >

  /**
   * Find the first OARobotProfile that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {OARobotProfileFindFirstArgs} args - Arguments to find a OARobotProfile
   * @example
   * // Get one OARobotProfile
   * const oARobotProfile = await prisma.oARobotProfile.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends OARobotProfileFindFirstArgs>(
    args?: Prisma.SelectSubset<T, OARobotProfileFindFirstArgs<ExtArgs>>
  ): Prisma.Prisma__OARobotProfileClient<
    runtime.Types.Result.GetResult<
      Prisma.$OARobotProfilePayload<ExtArgs>,
      T,
      'findFirst',
      GlobalOmitOptions
    > | null,
    null,
    ExtArgs,
    GlobalOmitOptions
  >

  /**
   * Find the first OARobotProfile that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {OARobotProfileFindFirstOrThrowArgs} args - Arguments to find a OARobotProfile
   * @example
   * // Get one OARobotProfile
   * const oARobotProfile = await prisma.oARobotProfile.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends OARobotProfileFindFirstOrThrowArgs>(
    args?: Prisma.SelectSubset<T, OARobotProfileFindFirstOrThrowArgs<ExtArgs>>
  ): Prisma.Prisma__OARobotProfileClient<
    runtime.Types.Result.GetResult<
      Prisma.$OARobotProfilePayload<ExtArgs>,
      T,
      'findFirstOrThrow',
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >

  /**
   * Find zero or more OARobotProfiles that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {OARobotProfileFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all OARobotProfiles
   * const oARobotProfiles = await prisma.oARobotProfile.findMany()
   *
   * // Get first 10 OARobotProfiles
   * const oARobotProfiles = await prisma.oARobotProfile.findMany({ take: 10 })
   *
   * // Only select the `id`
   * const oARobotProfileWithIdOnly = await prisma.oARobotProfile.findMany({ select: { id: true } })
   *
   */
  findMany<T extends OARobotProfileFindManyArgs>(
    args?: Prisma.SelectSubset<T, OARobotProfileFindManyArgs<ExtArgs>>
  ): Prisma.PrismaPromise<
    runtime.Types.Result.GetResult<
      Prisma.$OARobotProfilePayload<ExtArgs>,
      T,
      'findMany',
      GlobalOmitOptions
    >
  >

  /**
   * Create a OARobotProfile.
   * @param {OARobotProfileCreateArgs} args - Arguments to create a OARobotProfile.
   * @example
   * // Create one OARobotProfile
   * const OARobotProfile = await prisma.oARobotProfile.create({
   *   data: {
   *     // ... data to create a OARobotProfile
   *   }
   * })
   *
   */
  create<T extends OARobotProfileCreateArgs>(
    args: Prisma.SelectSubset<T, OARobotProfileCreateArgs<ExtArgs>>
  ): Prisma.Prisma__OARobotProfileClient<
    runtime.Types.Result.GetResult<
      Prisma.$OARobotProfilePayload<ExtArgs>,
      T,
      'create',
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >

  /**
   * Create many OARobotProfiles.
   * @param {OARobotProfileCreateManyArgs} args - Arguments to create many OARobotProfiles.
   * @example
   * // Create many OARobotProfiles
   * const oARobotProfile = await prisma.oARobotProfile.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *
   */
  createMany<T extends OARobotProfileCreateManyArgs>(
    args?: Prisma.SelectSubset<T, OARobotProfileCreateManyArgs<ExtArgs>>
  ): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many OARobotProfiles and returns the data saved in the database.
   * @param {OARobotProfileCreateManyAndReturnArgs} args - Arguments to create many OARobotProfiles.
   * @example
   * // Create many OARobotProfiles
   * const oARobotProfile = await prisma.oARobotProfile.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *
   * // Create many OARobotProfiles and only return the `id`
   * const oARobotProfileWithIdOnly = await prisma.oARobotProfile.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   *
   */
  createManyAndReturn<T extends OARobotProfileCreateManyAndReturnArgs>(
    args?: Prisma.SelectSubset<T, OARobotProfileCreateManyAndReturnArgs<ExtArgs>>
  ): Prisma.PrismaPromise<
    runtime.Types.Result.GetResult<
      Prisma.$OARobotProfilePayload<ExtArgs>,
      T,
      'createManyAndReturn',
      GlobalOmitOptions
    >
  >

  /**
   * Delete a OARobotProfile.
   * @param {OARobotProfileDeleteArgs} args - Arguments to delete one OARobotProfile.
   * @example
   * // Delete one OARobotProfile
   * const OARobotProfile = await prisma.oARobotProfile.delete({
   *   where: {
   *     // ... filter to delete one OARobotProfile
   *   }
   * })
   *
   */
  delete<T extends OARobotProfileDeleteArgs>(
    args: Prisma.SelectSubset<T, OARobotProfileDeleteArgs<ExtArgs>>
  ): Prisma.Prisma__OARobotProfileClient<
    runtime.Types.Result.GetResult<
      Prisma.$OARobotProfilePayload<ExtArgs>,
      T,
      'delete',
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >

  /**
   * Update one OARobotProfile.
   * @param {OARobotProfileUpdateArgs} args - Arguments to update one OARobotProfile.
   * @example
   * // Update one OARobotProfile
   * const oARobotProfile = await prisma.oARobotProfile.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   *
   */
  update<T extends OARobotProfileUpdateArgs>(
    args: Prisma.SelectSubset<T, OARobotProfileUpdateArgs<ExtArgs>>
  ): Prisma.Prisma__OARobotProfileClient<
    runtime.Types.Result.GetResult<
      Prisma.$OARobotProfilePayload<ExtArgs>,
      T,
      'update',
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >

  /**
   * Delete zero or more OARobotProfiles.
   * @param {OARobotProfileDeleteManyArgs} args - Arguments to filter OARobotProfiles to delete.
   * @example
   * // Delete a few OARobotProfiles
   * const { count } = await prisma.oARobotProfile.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   *
   */
  deleteMany<T extends OARobotProfileDeleteManyArgs>(
    args?: Prisma.SelectSubset<T, OARobotProfileDeleteManyArgs<ExtArgs>>
  ): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more OARobotProfiles.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {OARobotProfileUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many OARobotProfiles
   * const oARobotProfile = await prisma.oARobotProfile.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   *
   */
  updateMany<T extends OARobotProfileUpdateManyArgs>(
    args: Prisma.SelectSubset<T, OARobotProfileUpdateManyArgs<ExtArgs>>
  ): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more OARobotProfiles and returns the data updated in the database.
   * @param {OARobotProfileUpdateManyAndReturnArgs} args - Arguments to update many OARobotProfiles.
   * @example
   * // Update many OARobotProfiles
   * const oARobotProfile = await prisma.oARobotProfile.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *
   * // Update zero or more OARobotProfiles and only return the `id`
   * const oARobotProfileWithIdOnly = await prisma.oARobotProfile.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   *
   */
  updateManyAndReturn<T extends OARobotProfileUpdateManyAndReturnArgs>(
    args: Prisma.SelectSubset<T, OARobotProfileUpdateManyAndReturnArgs<ExtArgs>>
  ): Prisma.PrismaPromise<
    runtime.Types.Result.GetResult<
      Prisma.$OARobotProfilePayload<ExtArgs>,
      T,
      'updateManyAndReturn',
      GlobalOmitOptions
    >
  >

  /**
   * Create or update one OARobotProfile.
   * @param {OARobotProfileUpsertArgs} args - Arguments to update or create a OARobotProfile.
   * @example
   * // Update or create a OARobotProfile
   * const oARobotProfile = await prisma.oARobotProfile.upsert({
   *   create: {
   *     // ... data to create a OARobotProfile
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the OARobotProfile we want to update
   *   }
   * })
   */
  upsert<T extends OARobotProfileUpsertArgs>(
    args: Prisma.SelectSubset<T, OARobotProfileUpsertArgs<ExtArgs>>
  ): Prisma.Prisma__OARobotProfileClient<
    runtime.Types.Result.GetResult<
      Prisma.$OARobotProfilePayload<ExtArgs>,
      T,
      'upsert',
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >

  /**
   * Count the number of OARobotProfiles.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {OARobotProfileCountArgs} args - Arguments to filter OARobotProfiles to count.
   * @example
   * // Count the number of OARobotProfiles
   * const count = await prisma.oARobotProfile.count({
   *   where: {
   *     // ... the filter for the OARobotProfiles we want to count
   *   }
   * })
   **/
  count<T extends OARobotProfileCountArgs>(
    args?: Prisma.Subset<T, OARobotProfileCountArgs>
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], OARobotProfileCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a OARobotProfile.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {OARobotProfileAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
   **/
  aggregate<T extends OARobotProfileAggregateArgs>(
    args: Prisma.Subset<T, OARobotProfileAggregateArgs>
  ): Prisma.PrismaPromise<GetOARobotProfileAggregateType<T>>

  /**
   * Group by OARobotProfile.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {OARobotProfileGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   *
   **/
  groupBy<
    T extends OARobotProfileGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: OARobotProfileGroupByArgs['orderBy'] }
      : { orderBy?: OARobotProfileGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<
      Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>
    >,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
      ? `Error: "by" must not be empty.`
      : HavingValid extends Prisma.False
        ? {
            [P in HavingFields]: P extends ByFields
              ? never
              : P extends string
                ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
                : [Error, 'Field ', P, ` in "having" needs to be provided in "by"`]
          }[HavingFields]
        : 'take' extends Prisma.Keys<T>
          ? 'orderBy' extends Prisma.Keys<T>
            ? ByValid extends Prisma.True
              ? {}
              : {
                  [P in OrderFields]: P extends ByFields
                    ? never
                    : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
                }[OrderFields]
            : 'Error: If you provide "take", you also need to provide "orderBy"'
          : 'skip' extends Prisma.Keys<T>
            ? 'orderBy' extends Prisma.Keys<T>
              ? ByValid extends Prisma.True
                ? {}
                : {
                    [P in OrderFields]: P extends ByFields
                      ? never
                      : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
                  }[OrderFields]
              : 'Error: If you provide "skip", you also need to provide "orderBy"'
            : ByValid extends Prisma.True
              ? {}
              : {
                  [P in OrderFields]: P extends ByFields
                    ? never
                    : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
                }[OrderFields],
  >(
    args: Prisma.SubsetIntersection<T, OARobotProfileGroupByArgs, OrderByArg> & InputErrors
  ): {} extends InputErrors ? GetOARobotProfileGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
  /**
   * Fields of the OARobotProfile model
   */
  readonly fields: OARobotProfileFieldRefs
}

/**
 * The delegate class that acts as a "Promise-like" for OARobotProfile.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__OARobotProfileClient<
  T,
  Null = never,
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
  GlobalOmitOptions = {},
> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: 'PrismaPromise'
  author<T extends Prisma.OARobotProfile$authorArgs<ExtArgs> = {}>(
    args?: Prisma.Subset<T, Prisma.OARobotProfile$authorArgs<ExtArgs>>
  ): Prisma.Prisma__UserClient<
    runtime.Types.Result.GetResult<
      Prisma.$UserPayload<ExtArgs>,
      T,
      'findUniqueOrThrow',
      GlobalOmitOptions
    > | null,
    null,
    ExtArgs,
    GlobalOmitOptions
  >
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(
    onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null,
    onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null
  ): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(
    onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null
  ): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}

/**
 * Fields of the OARobotProfile model
 */
export interface OARobotProfileFieldRefs {
  readonly id: Prisma.FieldRef<'OARobotProfile', 'String'>
  readonly index: Prisma.FieldRef<'OARobotProfile', 'Int'>
  readonly name: Prisma.FieldRef<'OARobotProfile', 'String'>
  readonly desc: Prisma.FieldRef<'OARobotProfile', 'String'>
  readonly type: Prisma.FieldRef<'OARobotProfile', 'OARobotType'>
  readonly accessToken: Prisma.FieldRef<'OARobotProfile', 'String'>
  readonly secret: Prisma.FieldRef<'OARobotProfile', 'String'>
  readonly extraAuthentication: Prisma.FieldRef<'OARobotProfile', 'Json'>
  readonly userId: Prisma.FieldRef<'OARobotProfile', 'String'>
  readonly createdAt: Prisma.FieldRef<'OARobotProfile', 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<'OARobotProfile', 'DateTime'>
}

// Custom InputTypes
/**
 * OARobotProfile findUnique
 */
export type OARobotProfileFindUniqueArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the OARobotProfile
   */
  select?: Prisma.OARobotProfileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the OARobotProfile
   */
  omit?: Prisma.OARobotProfileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OARobotProfileInclude<ExtArgs> | null
  /**
   * Filter, which OARobotProfile to fetch.
   */
  where: Prisma.OARobotProfileWhereUniqueInput
}

/**
 * OARobotProfile findUniqueOrThrow
 */
export type OARobotProfileFindUniqueOrThrowArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the OARobotProfile
   */
  select?: Prisma.OARobotProfileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the OARobotProfile
   */
  omit?: Prisma.OARobotProfileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OARobotProfileInclude<ExtArgs> | null
  /**
   * Filter, which OARobotProfile to fetch.
   */
  where: Prisma.OARobotProfileWhereUniqueInput
}

/**
 * OARobotProfile findFirst
 */
export type OARobotProfileFindFirstArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the OARobotProfile
   */
  select?: Prisma.OARobotProfileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the OARobotProfile
   */
  omit?: Prisma.OARobotProfileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OARobotProfileInclude<ExtArgs> | null
  /**
   * Filter, which OARobotProfile to fetch.
   */
  where?: Prisma.OARobotProfileWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   *
   * Determine the order of OARobotProfiles to fetch.
   */
  orderBy?:
    | Prisma.OARobotProfileOrderByWithRelationInput
    | Prisma.OARobotProfileOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   *
   * Sets the position for searching for OARobotProfiles.
   */
  cursor?: Prisma.OARobotProfileWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Take `±n` OARobotProfiles from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Skip the first `n` OARobotProfiles.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   *
   * Filter by unique combinations of OARobotProfiles.
   */
  distinct?: Prisma.OARobotProfileScalarFieldEnum | Prisma.OARobotProfileScalarFieldEnum[]
}

/**
 * OARobotProfile findFirstOrThrow
 */
export type OARobotProfileFindFirstOrThrowArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the OARobotProfile
   */
  select?: Prisma.OARobotProfileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the OARobotProfile
   */
  omit?: Prisma.OARobotProfileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OARobotProfileInclude<ExtArgs> | null
  /**
   * Filter, which OARobotProfile to fetch.
   */
  where?: Prisma.OARobotProfileWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   *
   * Determine the order of OARobotProfiles to fetch.
   */
  orderBy?:
    | Prisma.OARobotProfileOrderByWithRelationInput
    | Prisma.OARobotProfileOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   *
   * Sets the position for searching for OARobotProfiles.
   */
  cursor?: Prisma.OARobotProfileWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Take `±n` OARobotProfiles from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Skip the first `n` OARobotProfiles.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   *
   * Filter by unique combinations of OARobotProfiles.
   */
  distinct?: Prisma.OARobotProfileScalarFieldEnum | Prisma.OARobotProfileScalarFieldEnum[]
}

/**
 * OARobotProfile findMany
 */
export type OARobotProfileFindManyArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the OARobotProfile
   */
  select?: Prisma.OARobotProfileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the OARobotProfile
   */
  omit?: Prisma.OARobotProfileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OARobotProfileInclude<ExtArgs> | null
  /**
   * Filter, which OARobotProfiles to fetch.
   */
  where?: Prisma.OARobotProfileWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   *
   * Determine the order of OARobotProfiles to fetch.
   */
  orderBy?:
    | Prisma.OARobotProfileOrderByWithRelationInput
    | Prisma.OARobotProfileOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   *
   * Sets the position for listing OARobotProfiles.
   */
  cursor?: Prisma.OARobotProfileWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Take `±n` OARobotProfiles from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Skip the first `n` OARobotProfiles.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   *
   * Filter by unique combinations of OARobotProfiles.
   */
  distinct?: Prisma.OARobotProfileScalarFieldEnum | Prisma.OARobotProfileScalarFieldEnum[]
}

/**
 * OARobotProfile create
 */
export type OARobotProfileCreateArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the OARobotProfile
   */
  select?: Prisma.OARobotProfileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the OARobotProfile
   */
  omit?: Prisma.OARobotProfileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OARobotProfileInclude<ExtArgs> | null
  /**
   * The data needed to create a OARobotProfile.
   */
  data: Prisma.XOR<Prisma.OARobotProfileCreateInput, Prisma.OARobotProfileUncheckedCreateInput>
}

/**
 * OARobotProfile createMany
 */
export type OARobotProfileCreateManyArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * The data used to create many OARobotProfiles.
   */
  data: Prisma.OARobotProfileCreateManyInput | Prisma.OARobotProfileCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * OARobotProfile createManyAndReturn
 */
export type OARobotProfileCreateManyAndReturnArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the OARobotProfile
   */
  select?: Prisma.OARobotProfileSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the OARobotProfile
   */
  omit?: Prisma.OARobotProfileOmit<ExtArgs> | null
  /**
   * The data used to create many OARobotProfiles.
   */
  data: Prisma.OARobotProfileCreateManyInput | Prisma.OARobotProfileCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OARobotProfileIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * OARobotProfile update
 */
export type OARobotProfileUpdateArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the OARobotProfile
   */
  select?: Prisma.OARobotProfileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the OARobotProfile
   */
  omit?: Prisma.OARobotProfileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OARobotProfileInclude<ExtArgs> | null
  /**
   * The data needed to update a OARobotProfile.
   */
  data: Prisma.XOR<Prisma.OARobotProfileUpdateInput, Prisma.OARobotProfileUncheckedUpdateInput>
  /**
   * Choose, which OARobotProfile to update.
   */
  where: Prisma.OARobotProfileWhereUniqueInput
}

/**
 * OARobotProfile updateMany
 */
export type OARobotProfileUpdateManyArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * The data used to update OARobotProfiles.
   */
  data: Prisma.XOR<
    Prisma.OARobotProfileUpdateManyMutationInput,
    Prisma.OARobotProfileUncheckedUpdateManyInput
  >
  /**
   * Filter which OARobotProfiles to update
   */
  where?: Prisma.OARobotProfileWhereInput
  /**
   * Limit how many OARobotProfiles to update.
   */
  limit?: number
}

/**
 * OARobotProfile updateManyAndReturn
 */
export type OARobotProfileUpdateManyAndReturnArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the OARobotProfile
   */
  select?: Prisma.OARobotProfileSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the OARobotProfile
   */
  omit?: Prisma.OARobotProfileOmit<ExtArgs> | null
  /**
   * The data used to update OARobotProfiles.
   */
  data: Prisma.XOR<
    Prisma.OARobotProfileUpdateManyMutationInput,
    Prisma.OARobotProfileUncheckedUpdateManyInput
  >
  /**
   * Filter which OARobotProfiles to update
   */
  where?: Prisma.OARobotProfileWhereInput
  /**
   * Limit how many OARobotProfiles to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OARobotProfileIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * OARobotProfile upsert
 */
export type OARobotProfileUpsertArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the OARobotProfile
   */
  select?: Prisma.OARobotProfileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the OARobotProfile
   */
  omit?: Prisma.OARobotProfileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OARobotProfileInclude<ExtArgs> | null
  /**
   * The filter to search for the OARobotProfile to update in case it exists.
   */
  where: Prisma.OARobotProfileWhereUniqueInput
  /**
   * In case the OARobotProfile found by the `where` argument doesn't exist, create a new OARobotProfile with this data.
   */
  create: Prisma.XOR<Prisma.OARobotProfileCreateInput, Prisma.OARobotProfileUncheckedCreateInput>
  /**
   * In case the OARobotProfile was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.OARobotProfileUpdateInput, Prisma.OARobotProfileUncheckedUpdateInput>
}

/**
 * OARobotProfile delete
 */
export type OARobotProfileDeleteArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the OARobotProfile
   */
  select?: Prisma.OARobotProfileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the OARobotProfile
   */
  omit?: Prisma.OARobotProfileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OARobotProfileInclude<ExtArgs> | null
  /**
   * Filter which OARobotProfile to delete.
   */
  where: Prisma.OARobotProfileWhereUniqueInput
}

/**
 * OARobotProfile deleteMany
 */
export type OARobotProfileDeleteManyArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Filter which OARobotProfiles to delete
   */
  where?: Prisma.OARobotProfileWhereInput
  /**
   * Limit how many OARobotProfiles to delete.
   */
  limit?: number
}

/**
 * OARobotProfile.author
 */
export type OARobotProfile$authorArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the User
   */
  select?: Prisma.UserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the User
   */
  omit?: Prisma.UserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserInclude<ExtArgs> | null
  where?: Prisma.UserWhereInput
}

/**
 * OARobotProfile without action
 */
export type OARobotProfileDefaultArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the OARobotProfile
   */
  select?: Prisma.OARobotProfileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the OARobotProfile
   */
  omit?: Prisma.OARobotProfileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OARobotProfileInclude<ExtArgs> | null
}
