/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck
/*
 * This file exports the `WLBDailyRecord` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from '@prisma/client/runtime/client'

import type * as $Enums from '../enums'
import type * as Prisma from '../internal/prismaNamespace'

/**
 * Model WLBDailyRecord
 * WLB 记录
 */
export type WLBDailyRecordModel =
  runtime.Types.Result.DefaultSelection<Prisma.$WLBDailyRecordPayload>

export type AggregateWLBDailyRecord = {
  _count: WLBDailyRecordCountAggregateOutputType | null
  _avg: WLBDailyRecordAvgAggregateOutputType | null
  _sum: WLBDailyRecordSumAggregateOutputType | null
  _min: WLBDailyRecordMinAggregateOutputType | null
  _max: WLBDailyRecordMaxAggregateOutputType | null
}

export type WLBDailyRecordAvgAggregateOutputType = {
  daysToSalaryDate: number | null
  h92: number | null
  h95: number | null
  h98: number | null
  todayStock: number | null
  yesterdayStock: number | null
  stockDelta: number | null
}

export type WLBDailyRecordSumAggregateOutputType = {
  daysToSalaryDate: number | null
  h92: number | null
  h95: number | null
  h98: number | null
  todayStock: number | null
  yesterdayStock: number | null
  stockDelta: number | null
}

export type WLBDailyRecordMinAggregateOutputType = {
  id: string | null
  date: string | null
  workday: boolean | null
  url: string | null
  shortURL: string | null
  imageURL: string | null
  nextSalaryDate: string | null
  daysToSalaryDate: number | null
  todayWeather: string | null
  todayTemperature: string | null
  todayWid: string | null
  tomorrowWeather: string | null
  tomorrowTemperature: string | null
  tomorrowWid: string | null
  h92: number | null
  h95: number | null
  h98: number | null
  traffic: string | null
  trafficImageURL: string | null
  todayStock: number | null
  yesterdayStock: number | null
  stockDelta: number | null
  profileId: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type WLBDailyRecordMaxAggregateOutputType = {
  id: string | null
  date: string | null
  workday: boolean | null
  url: string | null
  shortURL: string | null
  imageURL: string | null
  nextSalaryDate: string | null
  daysToSalaryDate: number | null
  todayWeather: string | null
  todayTemperature: string | null
  todayWid: string | null
  tomorrowWeather: string | null
  tomorrowTemperature: string | null
  tomorrowWid: string | null
  h92: number | null
  h95: number | null
  h98: number | null
  traffic: string | null
  trafficImageURL: string | null
  todayStock: number | null
  yesterdayStock: number | null
  stockDelta: number | null
  profileId: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type WLBDailyRecordCountAggregateOutputType = {
  id: number
  date: number
  workday: number
  url: number
  shortURL: number
  imageURL: number
  nextSalaryDate: number
  daysToSalaryDate: number
  todayWeather: number
  todayTemperature: number
  todayWid: number
  tomorrowWeather: number
  tomorrowTemperature: number
  tomorrowWid: number
  h92: number
  h95: number
  h98: number
  traffic: number
  trafficImageURL: number
  todayStock: number
  yesterdayStock: number
  stockDelta: number
  profileId: number
  createdAt: number
  updatedAt: number
  _all: number
}

export type WLBDailyRecordAvgAggregateInputType = {
  daysToSalaryDate?: true
  h92?: true
  h95?: true
  h98?: true
  todayStock?: true
  yesterdayStock?: true
  stockDelta?: true
}

export type WLBDailyRecordSumAggregateInputType = {
  daysToSalaryDate?: true
  h92?: true
  h95?: true
  h98?: true
  todayStock?: true
  yesterdayStock?: true
  stockDelta?: true
}

export type WLBDailyRecordMinAggregateInputType = {
  id?: true
  date?: true
  workday?: true
  url?: true
  shortURL?: true
  imageURL?: true
  nextSalaryDate?: true
  daysToSalaryDate?: true
  todayWeather?: true
  todayTemperature?: true
  todayWid?: true
  tomorrowWeather?: true
  tomorrowTemperature?: true
  tomorrowWid?: true
  h92?: true
  h95?: true
  h98?: true
  traffic?: true
  trafficImageURL?: true
  todayStock?: true
  yesterdayStock?: true
  stockDelta?: true
  profileId?: true
  createdAt?: true
  updatedAt?: true
}

export type WLBDailyRecordMaxAggregateInputType = {
  id?: true
  date?: true
  workday?: true
  url?: true
  shortURL?: true
  imageURL?: true
  nextSalaryDate?: true
  daysToSalaryDate?: true
  todayWeather?: true
  todayTemperature?: true
  todayWid?: true
  tomorrowWeather?: true
  tomorrowTemperature?: true
  tomorrowWid?: true
  h92?: true
  h95?: true
  h98?: true
  traffic?: true
  trafficImageURL?: true
  todayStock?: true
  yesterdayStock?: true
  stockDelta?: true
  profileId?: true
  createdAt?: true
  updatedAt?: true
}

export type WLBDailyRecordCountAggregateInputType = {
  id?: true
  date?: true
  workday?: true
  url?: true
  shortURL?: true
  imageURL?: true
  nextSalaryDate?: true
  daysToSalaryDate?: true
  todayWeather?: true
  todayTemperature?: true
  todayWid?: true
  tomorrowWeather?: true
  tomorrowTemperature?: true
  tomorrowWid?: true
  h92?: true
  h95?: true
  h98?: true
  traffic?: true
  trafficImageURL?: true
  todayStock?: true
  yesterdayStock?: true
  stockDelta?: true
  profileId?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type WLBDailyRecordAggregateArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Filter which WLBDailyRecord to aggregate.
   */
  where?: Prisma.WLBDailyRecordWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   *
   * Determine the order of WLBDailyRecords to fetch.
   */
  orderBy?:
    | Prisma.WLBDailyRecordOrderByWithRelationInput
    | Prisma.WLBDailyRecordOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   *
   * Sets the start position
   */
  cursor?: Prisma.WLBDailyRecordWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Take `±n` WLBDailyRecords from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Skip the first `n` WLBDailyRecords.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   *
   * Count returned WLBDailyRecords
   **/
  _count?: true | WLBDailyRecordCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   *
   * Select which fields to average
   **/
  _avg?: WLBDailyRecordAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   *
   * Select which fields to sum
   **/
  _sum?: WLBDailyRecordSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   *
   * Select which fields to find the minimum value
   **/
  _min?: WLBDailyRecordMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   *
   * Select which fields to find the maximum value
   **/
  _max?: WLBDailyRecordMaxAggregateInputType
}

export type GetWLBDailyRecordAggregateType<T extends WLBDailyRecordAggregateArgs> = {
  [P in keyof T & keyof AggregateWLBDailyRecord]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateWLBDailyRecord[P]>
    : Prisma.GetScalarType<T[P], AggregateWLBDailyRecord[P]>
}

export type WLBDailyRecordGroupByArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  where?: Prisma.WLBDailyRecordWhereInput
  orderBy?:
    | Prisma.WLBDailyRecordOrderByWithAggregationInput
    | Prisma.WLBDailyRecordOrderByWithAggregationInput[]
  by: Prisma.WLBDailyRecordScalarFieldEnum[] | Prisma.WLBDailyRecordScalarFieldEnum
  having?: Prisma.WLBDailyRecordScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: WLBDailyRecordCountAggregateInputType | true
  _avg?: WLBDailyRecordAvgAggregateInputType
  _sum?: WLBDailyRecordSumAggregateInputType
  _min?: WLBDailyRecordMinAggregateInputType
  _max?: WLBDailyRecordMaxAggregateInputType
}

export type WLBDailyRecordGroupByOutputType = {
  id: string
  date: string
  workday: boolean
  url: string
  shortURL: string
  imageURL: string
  nextSalaryDate: string
  daysToSalaryDate: number
  todayWeather: string
  todayTemperature: string
  todayWid: string
  tomorrowWeather: string
  tomorrowTemperature: string
  tomorrowWid: string
  h92: number
  h95: number
  h98: number
  traffic: string
  trafficImageURL: string
  todayStock: number | null
  yesterdayStock: number | null
  stockDelta: number | null
  profileId: string
  createdAt: Date
  updatedAt: Date
  _count: WLBDailyRecordCountAggregateOutputType | null
  _avg: WLBDailyRecordAvgAggregateOutputType | null
  _sum: WLBDailyRecordSumAggregateOutputType | null
  _min: WLBDailyRecordMinAggregateOutputType | null
  _max: WLBDailyRecordMaxAggregateOutputType | null
}

export type GetWLBDailyRecordGroupByPayload<T extends WLBDailyRecordGroupByArgs> =
  Prisma.PrismaPromise<
    Array<
      Prisma.PickEnumerable<WLBDailyRecordGroupByOutputType, T['by']> & {
        [P in keyof T & keyof WLBDailyRecordGroupByOutputType]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], WLBDailyRecordGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], WLBDailyRecordGroupByOutputType[P]>
      }
    >
  >

export type WLBDailyRecordWhereInput = {
  AND?: Prisma.WLBDailyRecordWhereInput | Prisma.WLBDailyRecordWhereInput[]
  OR?: Prisma.WLBDailyRecordWhereInput[]
  NOT?: Prisma.WLBDailyRecordWhereInput | Prisma.WLBDailyRecordWhereInput[]
  id?: Prisma.StringFilter<'WLBDailyRecord'> | string
  date?: Prisma.StringFilter<'WLBDailyRecord'> | string
  workday?: Prisma.BoolFilter<'WLBDailyRecord'> | boolean
  url?: Prisma.StringFilter<'WLBDailyRecord'> | string
  shortURL?: Prisma.StringFilter<'WLBDailyRecord'> | string
  imageURL?: Prisma.StringFilter<'WLBDailyRecord'> | string
  nextSalaryDate?: Prisma.StringFilter<'WLBDailyRecord'> | string
  daysToSalaryDate?: Prisma.IntFilter<'WLBDailyRecord'> | number
  todayWeather?: Prisma.StringFilter<'WLBDailyRecord'> | string
  todayTemperature?: Prisma.StringFilter<'WLBDailyRecord'> | string
  todayWid?: Prisma.StringFilter<'WLBDailyRecord'> | string
  tomorrowWeather?: Prisma.StringFilter<'WLBDailyRecord'> | string
  tomorrowTemperature?: Prisma.StringFilter<'WLBDailyRecord'> | string
  tomorrowWid?: Prisma.StringFilter<'WLBDailyRecord'> | string
  h92?: Prisma.FloatFilter<'WLBDailyRecord'> | number
  h95?: Prisma.FloatFilter<'WLBDailyRecord'> | number
  h98?: Prisma.FloatFilter<'WLBDailyRecord'> | number
  traffic?: Prisma.StringFilter<'WLBDailyRecord'> | string
  trafficImageURL?: Prisma.StringFilter<'WLBDailyRecord'> | string
  todayStock?: Prisma.FloatNullableFilter<'WLBDailyRecord'> | number | null
  yesterdayStock?: Prisma.FloatNullableFilter<'WLBDailyRecord'> | number | null
  stockDelta?: Prisma.FloatNullableFilter<'WLBDailyRecord'> | number | null
  profileId?: Prisma.StringFilter<'WLBDailyRecord'> | string
  createdAt?: Prisma.DateTimeFilter<'WLBDailyRecord'> | Date | string
  updatedAt?: Prisma.DateTimeFilter<'WLBDailyRecord'> | Date | string
  profile?: Prisma.XOR<Prisma.WLBProfileScalarRelationFilter, Prisma.WLBProfileWhereInput>
  wlbNotificationRecords?: Prisma.WLBNotificationRecordListRelationFilter
}

export type WLBDailyRecordOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  date?: Prisma.SortOrder
  workday?: Prisma.SortOrder
  url?: Prisma.SortOrder
  shortURL?: Prisma.SortOrder
  imageURL?: Prisma.SortOrder
  nextSalaryDate?: Prisma.SortOrder
  daysToSalaryDate?: Prisma.SortOrder
  todayWeather?: Prisma.SortOrder
  todayTemperature?: Prisma.SortOrder
  todayWid?: Prisma.SortOrder
  tomorrowWeather?: Prisma.SortOrder
  tomorrowTemperature?: Prisma.SortOrder
  tomorrowWid?: Prisma.SortOrder
  h92?: Prisma.SortOrder
  h95?: Prisma.SortOrder
  h98?: Prisma.SortOrder
  traffic?: Prisma.SortOrder
  trafficImageURL?: Prisma.SortOrder
  todayStock?: Prisma.SortOrderInput | Prisma.SortOrder
  yesterdayStock?: Prisma.SortOrderInput | Prisma.SortOrder
  stockDelta?: Prisma.SortOrderInput | Prisma.SortOrder
  profileId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  profile?: Prisma.WLBProfileOrderByWithRelationInput
  wlbNotificationRecords?: Prisma.WLBNotificationRecordOrderByRelationAggregateInput
}

export type WLBDailyRecordWhereUniqueInput = Prisma.AtLeast<
  {
    id?: string
    AND?: Prisma.WLBDailyRecordWhereInput | Prisma.WLBDailyRecordWhereInput[]
    OR?: Prisma.WLBDailyRecordWhereInput[]
    NOT?: Prisma.WLBDailyRecordWhereInput | Prisma.WLBDailyRecordWhereInput[]
    date?: Prisma.StringFilter<'WLBDailyRecord'> | string
    workday?: Prisma.BoolFilter<'WLBDailyRecord'> | boolean
    url?: Prisma.StringFilter<'WLBDailyRecord'> | string
    shortURL?: Prisma.StringFilter<'WLBDailyRecord'> | string
    imageURL?: Prisma.StringFilter<'WLBDailyRecord'> | string
    nextSalaryDate?: Prisma.StringFilter<'WLBDailyRecord'> | string
    daysToSalaryDate?: Prisma.IntFilter<'WLBDailyRecord'> | number
    todayWeather?: Prisma.StringFilter<'WLBDailyRecord'> | string
    todayTemperature?: Prisma.StringFilter<'WLBDailyRecord'> | string
    todayWid?: Prisma.StringFilter<'WLBDailyRecord'> | string
    tomorrowWeather?: Prisma.StringFilter<'WLBDailyRecord'> | string
    tomorrowTemperature?: Prisma.StringFilter<'WLBDailyRecord'> | string
    tomorrowWid?: Prisma.StringFilter<'WLBDailyRecord'> | string
    h92?: Prisma.FloatFilter<'WLBDailyRecord'> | number
    h95?: Prisma.FloatFilter<'WLBDailyRecord'> | number
    h98?: Prisma.FloatFilter<'WLBDailyRecord'> | number
    traffic?: Prisma.StringFilter<'WLBDailyRecord'> | string
    trafficImageURL?: Prisma.StringFilter<'WLBDailyRecord'> | string
    todayStock?: Prisma.FloatNullableFilter<'WLBDailyRecord'> | number | null
    yesterdayStock?: Prisma.FloatNullableFilter<'WLBDailyRecord'> | number | null
    stockDelta?: Prisma.FloatNullableFilter<'WLBDailyRecord'> | number | null
    profileId?: Prisma.StringFilter<'WLBDailyRecord'> | string
    createdAt?: Prisma.DateTimeFilter<'WLBDailyRecord'> | Date | string
    updatedAt?: Prisma.DateTimeFilter<'WLBDailyRecord'> | Date | string
    profile?: Prisma.XOR<Prisma.WLBProfileScalarRelationFilter, Prisma.WLBProfileWhereInput>
    wlbNotificationRecords?: Prisma.WLBNotificationRecordListRelationFilter
  },
  'id'
>

export type WLBDailyRecordOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  date?: Prisma.SortOrder
  workday?: Prisma.SortOrder
  url?: Prisma.SortOrder
  shortURL?: Prisma.SortOrder
  imageURL?: Prisma.SortOrder
  nextSalaryDate?: Prisma.SortOrder
  daysToSalaryDate?: Prisma.SortOrder
  todayWeather?: Prisma.SortOrder
  todayTemperature?: Prisma.SortOrder
  todayWid?: Prisma.SortOrder
  tomorrowWeather?: Prisma.SortOrder
  tomorrowTemperature?: Prisma.SortOrder
  tomorrowWid?: Prisma.SortOrder
  h92?: Prisma.SortOrder
  h95?: Prisma.SortOrder
  h98?: Prisma.SortOrder
  traffic?: Prisma.SortOrder
  trafficImageURL?: Prisma.SortOrder
  todayStock?: Prisma.SortOrderInput | Prisma.SortOrder
  yesterdayStock?: Prisma.SortOrderInput | Prisma.SortOrder
  stockDelta?: Prisma.SortOrderInput | Prisma.SortOrder
  profileId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.WLBDailyRecordCountOrderByAggregateInput
  _avg?: Prisma.WLBDailyRecordAvgOrderByAggregateInput
  _max?: Prisma.WLBDailyRecordMaxOrderByAggregateInput
  _min?: Prisma.WLBDailyRecordMinOrderByAggregateInput
  _sum?: Prisma.WLBDailyRecordSumOrderByAggregateInput
}

export type WLBDailyRecordScalarWhereWithAggregatesInput = {
  AND?:
    | Prisma.WLBDailyRecordScalarWhereWithAggregatesInput
    | Prisma.WLBDailyRecordScalarWhereWithAggregatesInput[]
  OR?: Prisma.WLBDailyRecordScalarWhereWithAggregatesInput[]
  NOT?:
    | Prisma.WLBDailyRecordScalarWhereWithAggregatesInput
    | Prisma.WLBDailyRecordScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<'WLBDailyRecord'> | string
  date?: Prisma.StringWithAggregatesFilter<'WLBDailyRecord'> | string
  workday?: Prisma.BoolWithAggregatesFilter<'WLBDailyRecord'> | boolean
  url?: Prisma.StringWithAggregatesFilter<'WLBDailyRecord'> | string
  shortURL?: Prisma.StringWithAggregatesFilter<'WLBDailyRecord'> | string
  imageURL?: Prisma.StringWithAggregatesFilter<'WLBDailyRecord'> | string
  nextSalaryDate?: Prisma.StringWithAggregatesFilter<'WLBDailyRecord'> | string
  daysToSalaryDate?: Prisma.IntWithAggregatesFilter<'WLBDailyRecord'> | number
  todayWeather?: Prisma.StringWithAggregatesFilter<'WLBDailyRecord'> | string
  todayTemperature?: Prisma.StringWithAggregatesFilter<'WLBDailyRecord'> | string
  todayWid?: Prisma.StringWithAggregatesFilter<'WLBDailyRecord'> | string
  tomorrowWeather?: Prisma.StringWithAggregatesFilter<'WLBDailyRecord'> | string
  tomorrowTemperature?: Prisma.StringWithAggregatesFilter<'WLBDailyRecord'> | string
  tomorrowWid?: Prisma.StringWithAggregatesFilter<'WLBDailyRecord'> | string
  h92?: Prisma.FloatWithAggregatesFilter<'WLBDailyRecord'> | number
  h95?: Prisma.FloatWithAggregatesFilter<'WLBDailyRecord'> | number
  h98?: Prisma.FloatWithAggregatesFilter<'WLBDailyRecord'> | number
  traffic?: Prisma.StringWithAggregatesFilter<'WLBDailyRecord'> | string
  trafficImageURL?: Prisma.StringWithAggregatesFilter<'WLBDailyRecord'> | string
  todayStock?: Prisma.FloatNullableWithAggregatesFilter<'WLBDailyRecord'> | number | null
  yesterdayStock?: Prisma.FloatNullableWithAggregatesFilter<'WLBDailyRecord'> | number | null
  stockDelta?: Prisma.FloatNullableWithAggregatesFilter<'WLBDailyRecord'> | number | null
  profileId?: Prisma.StringWithAggregatesFilter<'WLBDailyRecord'> | string
  createdAt?: Prisma.DateTimeWithAggregatesFilter<'WLBDailyRecord'> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<'WLBDailyRecord'> | Date | string
}

export type WLBDailyRecordCreateInput = {
  id?: string
  date: string
  workday: boolean
  url: string
  shortURL: string
  imageURL: string
  nextSalaryDate: string
  daysToSalaryDate: number
  todayWeather: string
  todayTemperature: string
  todayWid: string
  tomorrowWeather: string
  tomorrowTemperature: string
  tomorrowWid: string
  h92: number
  h95: number
  h98: number
  traffic: string
  trafficImageURL: string
  todayStock?: number | null
  yesterdayStock?: number | null
  stockDelta?: number | null
  createdAt?: Date | string
  updatedAt?: Date | string
  profile: Prisma.WLBProfileCreateNestedOneWithoutWlbdailyRecordsInput
  wlbNotificationRecords?: Prisma.WLBNotificationRecordCreateNestedManyWithoutDailyRecordInput
}

export type WLBDailyRecordUncheckedCreateInput = {
  id?: string
  date: string
  workday: boolean
  url: string
  shortURL: string
  imageURL: string
  nextSalaryDate: string
  daysToSalaryDate: number
  todayWeather: string
  todayTemperature: string
  todayWid: string
  tomorrowWeather: string
  tomorrowTemperature: string
  tomorrowWid: string
  h92: number
  h95: number
  h98: number
  traffic: string
  trafficImageURL: string
  todayStock?: number | null
  yesterdayStock?: number | null
  stockDelta?: number | null
  profileId: string
  createdAt?: Date | string
  updatedAt?: Date | string
  wlbNotificationRecords?: Prisma.WLBNotificationRecordUncheckedCreateNestedManyWithoutDailyRecordInput
}

export type WLBDailyRecordUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  date?: Prisma.StringFieldUpdateOperationsInput | string
  workday?: Prisma.BoolFieldUpdateOperationsInput | boolean
  url?: Prisma.StringFieldUpdateOperationsInput | string
  shortURL?: Prisma.StringFieldUpdateOperationsInput | string
  imageURL?: Prisma.StringFieldUpdateOperationsInput | string
  nextSalaryDate?: Prisma.StringFieldUpdateOperationsInput | string
  daysToSalaryDate?: Prisma.IntFieldUpdateOperationsInput | number
  todayWeather?: Prisma.StringFieldUpdateOperationsInput | string
  todayTemperature?: Prisma.StringFieldUpdateOperationsInput | string
  todayWid?: Prisma.StringFieldUpdateOperationsInput | string
  tomorrowWeather?: Prisma.StringFieldUpdateOperationsInput | string
  tomorrowTemperature?: Prisma.StringFieldUpdateOperationsInput | string
  tomorrowWid?: Prisma.StringFieldUpdateOperationsInput | string
  h92?: Prisma.FloatFieldUpdateOperationsInput | number
  h95?: Prisma.FloatFieldUpdateOperationsInput | number
  h98?: Prisma.FloatFieldUpdateOperationsInput | number
  traffic?: Prisma.StringFieldUpdateOperationsInput | string
  trafficImageURL?: Prisma.StringFieldUpdateOperationsInput | string
  todayStock?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  yesterdayStock?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  stockDelta?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  profile?: Prisma.WLBProfileUpdateOneRequiredWithoutWlbdailyRecordsNestedInput
  wlbNotificationRecords?: Prisma.WLBNotificationRecordUpdateManyWithoutDailyRecordNestedInput
}

export type WLBDailyRecordUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  date?: Prisma.StringFieldUpdateOperationsInput | string
  workday?: Prisma.BoolFieldUpdateOperationsInput | boolean
  url?: Prisma.StringFieldUpdateOperationsInput | string
  shortURL?: Prisma.StringFieldUpdateOperationsInput | string
  imageURL?: Prisma.StringFieldUpdateOperationsInput | string
  nextSalaryDate?: Prisma.StringFieldUpdateOperationsInput | string
  daysToSalaryDate?: Prisma.IntFieldUpdateOperationsInput | number
  todayWeather?: Prisma.StringFieldUpdateOperationsInput | string
  todayTemperature?: Prisma.StringFieldUpdateOperationsInput | string
  todayWid?: Prisma.StringFieldUpdateOperationsInput | string
  tomorrowWeather?: Prisma.StringFieldUpdateOperationsInput | string
  tomorrowTemperature?: Prisma.StringFieldUpdateOperationsInput | string
  tomorrowWid?: Prisma.StringFieldUpdateOperationsInput | string
  h92?: Prisma.FloatFieldUpdateOperationsInput | number
  h95?: Prisma.FloatFieldUpdateOperationsInput | number
  h98?: Prisma.FloatFieldUpdateOperationsInput | number
  traffic?: Prisma.StringFieldUpdateOperationsInput | string
  trafficImageURL?: Prisma.StringFieldUpdateOperationsInput | string
  todayStock?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  yesterdayStock?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  stockDelta?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  profileId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  wlbNotificationRecords?: Prisma.WLBNotificationRecordUncheckedUpdateManyWithoutDailyRecordNestedInput
}

export type WLBDailyRecordCreateManyInput = {
  id?: string
  date: string
  workday: boolean
  url: string
  shortURL: string
  imageURL: string
  nextSalaryDate: string
  daysToSalaryDate: number
  todayWeather: string
  todayTemperature: string
  todayWid: string
  tomorrowWeather: string
  tomorrowTemperature: string
  tomorrowWid: string
  h92: number
  h95: number
  h98: number
  traffic: string
  trafficImageURL: string
  todayStock?: number | null
  yesterdayStock?: number | null
  stockDelta?: number | null
  profileId: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type WLBDailyRecordUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  date?: Prisma.StringFieldUpdateOperationsInput | string
  workday?: Prisma.BoolFieldUpdateOperationsInput | boolean
  url?: Prisma.StringFieldUpdateOperationsInput | string
  shortURL?: Prisma.StringFieldUpdateOperationsInput | string
  imageURL?: Prisma.StringFieldUpdateOperationsInput | string
  nextSalaryDate?: Prisma.StringFieldUpdateOperationsInput | string
  daysToSalaryDate?: Prisma.IntFieldUpdateOperationsInput | number
  todayWeather?: Prisma.StringFieldUpdateOperationsInput | string
  todayTemperature?: Prisma.StringFieldUpdateOperationsInput | string
  todayWid?: Prisma.StringFieldUpdateOperationsInput | string
  tomorrowWeather?: Prisma.StringFieldUpdateOperationsInput | string
  tomorrowTemperature?: Prisma.StringFieldUpdateOperationsInput | string
  tomorrowWid?: Prisma.StringFieldUpdateOperationsInput | string
  h92?: Prisma.FloatFieldUpdateOperationsInput | number
  h95?: Prisma.FloatFieldUpdateOperationsInput | number
  h98?: Prisma.FloatFieldUpdateOperationsInput | number
  traffic?: Prisma.StringFieldUpdateOperationsInput | string
  trafficImageURL?: Prisma.StringFieldUpdateOperationsInput | string
  todayStock?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  yesterdayStock?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  stockDelta?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type WLBDailyRecordUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  date?: Prisma.StringFieldUpdateOperationsInput | string
  workday?: Prisma.BoolFieldUpdateOperationsInput | boolean
  url?: Prisma.StringFieldUpdateOperationsInput | string
  shortURL?: Prisma.StringFieldUpdateOperationsInput | string
  imageURL?: Prisma.StringFieldUpdateOperationsInput | string
  nextSalaryDate?: Prisma.StringFieldUpdateOperationsInput | string
  daysToSalaryDate?: Prisma.IntFieldUpdateOperationsInput | number
  todayWeather?: Prisma.StringFieldUpdateOperationsInput | string
  todayTemperature?: Prisma.StringFieldUpdateOperationsInput | string
  todayWid?: Prisma.StringFieldUpdateOperationsInput | string
  tomorrowWeather?: Prisma.StringFieldUpdateOperationsInput | string
  tomorrowTemperature?: Prisma.StringFieldUpdateOperationsInput | string
  tomorrowWid?: Prisma.StringFieldUpdateOperationsInput | string
  h92?: Prisma.FloatFieldUpdateOperationsInput | number
  h95?: Prisma.FloatFieldUpdateOperationsInput | number
  h98?: Prisma.FloatFieldUpdateOperationsInput | number
  traffic?: Prisma.StringFieldUpdateOperationsInput | string
  trafficImageURL?: Prisma.StringFieldUpdateOperationsInput | string
  todayStock?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  yesterdayStock?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  stockDelta?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  profileId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type WLBDailyRecordListRelationFilter = {
  every?: Prisma.WLBDailyRecordWhereInput
  some?: Prisma.WLBDailyRecordWhereInput
  none?: Prisma.WLBDailyRecordWhereInput
}

export type WLBDailyRecordOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type WLBDailyRecordCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  date?: Prisma.SortOrder
  workday?: Prisma.SortOrder
  url?: Prisma.SortOrder
  shortURL?: Prisma.SortOrder
  imageURL?: Prisma.SortOrder
  nextSalaryDate?: Prisma.SortOrder
  daysToSalaryDate?: Prisma.SortOrder
  todayWeather?: Prisma.SortOrder
  todayTemperature?: Prisma.SortOrder
  todayWid?: Prisma.SortOrder
  tomorrowWeather?: Prisma.SortOrder
  tomorrowTemperature?: Prisma.SortOrder
  tomorrowWid?: Prisma.SortOrder
  h92?: Prisma.SortOrder
  h95?: Prisma.SortOrder
  h98?: Prisma.SortOrder
  traffic?: Prisma.SortOrder
  trafficImageURL?: Prisma.SortOrder
  todayStock?: Prisma.SortOrder
  yesterdayStock?: Prisma.SortOrder
  stockDelta?: Prisma.SortOrder
  profileId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type WLBDailyRecordAvgOrderByAggregateInput = {
  daysToSalaryDate?: Prisma.SortOrder
  h92?: Prisma.SortOrder
  h95?: Prisma.SortOrder
  h98?: Prisma.SortOrder
  todayStock?: Prisma.SortOrder
  yesterdayStock?: Prisma.SortOrder
  stockDelta?: Prisma.SortOrder
}

export type WLBDailyRecordMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  date?: Prisma.SortOrder
  workday?: Prisma.SortOrder
  url?: Prisma.SortOrder
  shortURL?: Prisma.SortOrder
  imageURL?: Prisma.SortOrder
  nextSalaryDate?: Prisma.SortOrder
  daysToSalaryDate?: Prisma.SortOrder
  todayWeather?: Prisma.SortOrder
  todayTemperature?: Prisma.SortOrder
  todayWid?: Prisma.SortOrder
  tomorrowWeather?: Prisma.SortOrder
  tomorrowTemperature?: Prisma.SortOrder
  tomorrowWid?: Prisma.SortOrder
  h92?: Prisma.SortOrder
  h95?: Prisma.SortOrder
  h98?: Prisma.SortOrder
  traffic?: Prisma.SortOrder
  trafficImageURL?: Prisma.SortOrder
  todayStock?: Prisma.SortOrder
  yesterdayStock?: Prisma.SortOrder
  stockDelta?: Prisma.SortOrder
  profileId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type WLBDailyRecordMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  date?: Prisma.SortOrder
  workday?: Prisma.SortOrder
  url?: Prisma.SortOrder
  shortURL?: Prisma.SortOrder
  imageURL?: Prisma.SortOrder
  nextSalaryDate?: Prisma.SortOrder
  daysToSalaryDate?: Prisma.SortOrder
  todayWeather?: Prisma.SortOrder
  todayTemperature?: Prisma.SortOrder
  todayWid?: Prisma.SortOrder
  tomorrowWeather?: Prisma.SortOrder
  tomorrowTemperature?: Prisma.SortOrder
  tomorrowWid?: Prisma.SortOrder
  h92?: Prisma.SortOrder
  h95?: Prisma.SortOrder
  h98?: Prisma.SortOrder
  traffic?: Prisma.SortOrder
  trafficImageURL?: Prisma.SortOrder
  todayStock?: Prisma.SortOrder
  yesterdayStock?: Prisma.SortOrder
  stockDelta?: Prisma.SortOrder
  profileId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type WLBDailyRecordSumOrderByAggregateInput = {
  daysToSalaryDate?: Prisma.SortOrder
  h92?: Prisma.SortOrder
  h95?: Prisma.SortOrder
  h98?: Prisma.SortOrder
  todayStock?: Prisma.SortOrder
  yesterdayStock?: Prisma.SortOrder
  stockDelta?: Prisma.SortOrder
}

export type WLBDailyRecordNullableScalarRelationFilter = {
  is?: Prisma.WLBDailyRecordWhereInput | null
  isNot?: Prisma.WLBDailyRecordWhereInput | null
}

export type WLBDailyRecordCreateNestedManyWithoutProfileInput = {
  create?:
    | Prisma.XOR<
        Prisma.WLBDailyRecordCreateWithoutProfileInput,
        Prisma.WLBDailyRecordUncheckedCreateWithoutProfileInput
      >
    | Prisma.WLBDailyRecordCreateWithoutProfileInput[]
    | Prisma.WLBDailyRecordUncheckedCreateWithoutProfileInput[]
  connectOrCreate?:
    | Prisma.WLBDailyRecordCreateOrConnectWithoutProfileInput
    | Prisma.WLBDailyRecordCreateOrConnectWithoutProfileInput[]
  createMany?: Prisma.WLBDailyRecordCreateManyProfileInputEnvelope
  connect?: Prisma.WLBDailyRecordWhereUniqueInput | Prisma.WLBDailyRecordWhereUniqueInput[]
}

export type WLBDailyRecordUncheckedCreateNestedManyWithoutProfileInput = {
  create?:
    | Prisma.XOR<
        Prisma.WLBDailyRecordCreateWithoutProfileInput,
        Prisma.WLBDailyRecordUncheckedCreateWithoutProfileInput
      >
    | Prisma.WLBDailyRecordCreateWithoutProfileInput[]
    | Prisma.WLBDailyRecordUncheckedCreateWithoutProfileInput[]
  connectOrCreate?:
    | Prisma.WLBDailyRecordCreateOrConnectWithoutProfileInput
    | Prisma.WLBDailyRecordCreateOrConnectWithoutProfileInput[]
  createMany?: Prisma.WLBDailyRecordCreateManyProfileInputEnvelope
  connect?: Prisma.WLBDailyRecordWhereUniqueInput | Prisma.WLBDailyRecordWhereUniqueInput[]
}

export type WLBDailyRecordUpdateManyWithoutProfileNestedInput = {
  create?:
    | Prisma.XOR<
        Prisma.WLBDailyRecordCreateWithoutProfileInput,
        Prisma.WLBDailyRecordUncheckedCreateWithoutProfileInput
      >
    | Prisma.WLBDailyRecordCreateWithoutProfileInput[]
    | Prisma.WLBDailyRecordUncheckedCreateWithoutProfileInput[]
  connectOrCreate?:
    | Prisma.WLBDailyRecordCreateOrConnectWithoutProfileInput
    | Prisma.WLBDailyRecordCreateOrConnectWithoutProfileInput[]
  upsert?:
    | Prisma.WLBDailyRecordUpsertWithWhereUniqueWithoutProfileInput
    | Prisma.WLBDailyRecordUpsertWithWhereUniqueWithoutProfileInput[]
  createMany?: Prisma.WLBDailyRecordCreateManyProfileInputEnvelope
  set?: Prisma.WLBDailyRecordWhereUniqueInput | Prisma.WLBDailyRecordWhereUniqueInput[]
  disconnect?: Prisma.WLBDailyRecordWhereUniqueInput | Prisma.WLBDailyRecordWhereUniqueInput[]
  delete?: Prisma.WLBDailyRecordWhereUniqueInput | Prisma.WLBDailyRecordWhereUniqueInput[]
  connect?: Prisma.WLBDailyRecordWhereUniqueInput | Prisma.WLBDailyRecordWhereUniqueInput[]
  update?:
    | Prisma.WLBDailyRecordUpdateWithWhereUniqueWithoutProfileInput
    | Prisma.WLBDailyRecordUpdateWithWhereUniqueWithoutProfileInput[]
  updateMany?:
    | Prisma.WLBDailyRecordUpdateManyWithWhereWithoutProfileInput
    | Prisma.WLBDailyRecordUpdateManyWithWhereWithoutProfileInput[]
  deleteMany?: Prisma.WLBDailyRecordScalarWhereInput | Prisma.WLBDailyRecordScalarWhereInput[]
}

export type WLBDailyRecordUncheckedUpdateManyWithoutProfileNestedInput = {
  create?:
    | Prisma.XOR<
        Prisma.WLBDailyRecordCreateWithoutProfileInput,
        Prisma.WLBDailyRecordUncheckedCreateWithoutProfileInput
      >
    | Prisma.WLBDailyRecordCreateWithoutProfileInput[]
    | Prisma.WLBDailyRecordUncheckedCreateWithoutProfileInput[]
  connectOrCreate?:
    | Prisma.WLBDailyRecordCreateOrConnectWithoutProfileInput
    | Prisma.WLBDailyRecordCreateOrConnectWithoutProfileInput[]
  upsert?:
    | Prisma.WLBDailyRecordUpsertWithWhereUniqueWithoutProfileInput
    | Prisma.WLBDailyRecordUpsertWithWhereUniqueWithoutProfileInput[]
  createMany?: Prisma.WLBDailyRecordCreateManyProfileInputEnvelope
  set?: Prisma.WLBDailyRecordWhereUniqueInput | Prisma.WLBDailyRecordWhereUniqueInput[]
  disconnect?: Prisma.WLBDailyRecordWhereUniqueInput | Prisma.WLBDailyRecordWhereUniqueInput[]
  delete?: Prisma.WLBDailyRecordWhereUniqueInput | Prisma.WLBDailyRecordWhereUniqueInput[]
  connect?: Prisma.WLBDailyRecordWhereUniqueInput | Prisma.WLBDailyRecordWhereUniqueInput[]
  update?:
    | Prisma.WLBDailyRecordUpdateWithWhereUniqueWithoutProfileInput
    | Prisma.WLBDailyRecordUpdateWithWhereUniqueWithoutProfileInput[]
  updateMany?:
    | Prisma.WLBDailyRecordUpdateManyWithWhereWithoutProfileInput
    | Prisma.WLBDailyRecordUpdateManyWithWhereWithoutProfileInput[]
  deleteMany?: Prisma.WLBDailyRecordScalarWhereInput | Prisma.WLBDailyRecordScalarWhereInput[]
}

export type FloatFieldUpdateOperationsInput = {
  set?: number
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}

export type NullableFloatFieldUpdateOperationsInput = {
  set?: number | null
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}

export type WLBDailyRecordCreateNestedOneWithoutWlbNotificationRecordsInput = {
  create?: Prisma.XOR<
    Prisma.WLBDailyRecordCreateWithoutWlbNotificationRecordsInput,
    Prisma.WLBDailyRecordUncheckedCreateWithoutWlbNotificationRecordsInput
  >
  connectOrCreate?: Prisma.WLBDailyRecordCreateOrConnectWithoutWlbNotificationRecordsInput
  connect?: Prisma.WLBDailyRecordWhereUniqueInput
}

export type WLBDailyRecordUpdateOneWithoutWlbNotificationRecordsNestedInput = {
  create?: Prisma.XOR<
    Prisma.WLBDailyRecordCreateWithoutWlbNotificationRecordsInput,
    Prisma.WLBDailyRecordUncheckedCreateWithoutWlbNotificationRecordsInput
  >
  connectOrCreate?: Prisma.WLBDailyRecordCreateOrConnectWithoutWlbNotificationRecordsInput
  upsert?: Prisma.WLBDailyRecordUpsertWithoutWlbNotificationRecordsInput
  disconnect?: Prisma.WLBDailyRecordWhereInput | boolean
  delete?: Prisma.WLBDailyRecordWhereInput | boolean
  connect?: Prisma.WLBDailyRecordWhereUniqueInput
  update?: Prisma.XOR<
    Prisma.XOR<
      Prisma.WLBDailyRecordUpdateToOneWithWhereWithoutWlbNotificationRecordsInput,
      Prisma.WLBDailyRecordUpdateWithoutWlbNotificationRecordsInput
    >,
    Prisma.WLBDailyRecordUncheckedUpdateWithoutWlbNotificationRecordsInput
  >
}

export type WLBDailyRecordCreateWithoutProfileInput = {
  id?: string
  date: string
  workday: boolean
  url: string
  shortURL: string
  imageURL: string
  nextSalaryDate: string
  daysToSalaryDate: number
  todayWeather: string
  todayTemperature: string
  todayWid: string
  tomorrowWeather: string
  tomorrowTemperature: string
  tomorrowWid: string
  h92: number
  h95: number
  h98: number
  traffic: string
  trafficImageURL: string
  todayStock?: number | null
  yesterdayStock?: number | null
  stockDelta?: number | null
  createdAt?: Date | string
  updatedAt?: Date | string
  wlbNotificationRecords?: Prisma.WLBNotificationRecordCreateNestedManyWithoutDailyRecordInput
}

export type WLBDailyRecordUncheckedCreateWithoutProfileInput = {
  id?: string
  date: string
  workday: boolean
  url: string
  shortURL: string
  imageURL: string
  nextSalaryDate: string
  daysToSalaryDate: number
  todayWeather: string
  todayTemperature: string
  todayWid: string
  tomorrowWeather: string
  tomorrowTemperature: string
  tomorrowWid: string
  h92: number
  h95: number
  h98: number
  traffic: string
  trafficImageURL: string
  todayStock?: number | null
  yesterdayStock?: number | null
  stockDelta?: number | null
  createdAt?: Date | string
  updatedAt?: Date | string
  wlbNotificationRecords?: Prisma.WLBNotificationRecordUncheckedCreateNestedManyWithoutDailyRecordInput
}

export type WLBDailyRecordCreateOrConnectWithoutProfileInput = {
  where: Prisma.WLBDailyRecordWhereUniqueInput
  create: Prisma.XOR<
    Prisma.WLBDailyRecordCreateWithoutProfileInput,
    Prisma.WLBDailyRecordUncheckedCreateWithoutProfileInput
  >
}

export type WLBDailyRecordCreateManyProfileInputEnvelope = {
  data: Prisma.WLBDailyRecordCreateManyProfileInput | Prisma.WLBDailyRecordCreateManyProfileInput[]
  skipDuplicates?: boolean
}

export type WLBDailyRecordUpsertWithWhereUniqueWithoutProfileInput = {
  where: Prisma.WLBDailyRecordWhereUniqueInput
  update: Prisma.XOR<
    Prisma.WLBDailyRecordUpdateWithoutProfileInput,
    Prisma.WLBDailyRecordUncheckedUpdateWithoutProfileInput
  >
  create: Prisma.XOR<
    Prisma.WLBDailyRecordCreateWithoutProfileInput,
    Prisma.WLBDailyRecordUncheckedCreateWithoutProfileInput
  >
}

export type WLBDailyRecordUpdateWithWhereUniqueWithoutProfileInput = {
  where: Prisma.WLBDailyRecordWhereUniqueInput
  data: Prisma.XOR<
    Prisma.WLBDailyRecordUpdateWithoutProfileInput,
    Prisma.WLBDailyRecordUncheckedUpdateWithoutProfileInput
  >
}

export type WLBDailyRecordUpdateManyWithWhereWithoutProfileInput = {
  where: Prisma.WLBDailyRecordScalarWhereInput
  data: Prisma.XOR<
    Prisma.WLBDailyRecordUpdateManyMutationInput,
    Prisma.WLBDailyRecordUncheckedUpdateManyWithoutProfileInput
  >
}

export type WLBDailyRecordScalarWhereInput = {
  AND?: Prisma.WLBDailyRecordScalarWhereInput | Prisma.WLBDailyRecordScalarWhereInput[]
  OR?: Prisma.WLBDailyRecordScalarWhereInput[]
  NOT?: Prisma.WLBDailyRecordScalarWhereInput | Prisma.WLBDailyRecordScalarWhereInput[]
  id?: Prisma.StringFilter<'WLBDailyRecord'> | string
  date?: Prisma.StringFilter<'WLBDailyRecord'> | string
  workday?: Prisma.BoolFilter<'WLBDailyRecord'> | boolean
  url?: Prisma.StringFilter<'WLBDailyRecord'> | string
  shortURL?: Prisma.StringFilter<'WLBDailyRecord'> | string
  imageURL?: Prisma.StringFilter<'WLBDailyRecord'> | string
  nextSalaryDate?: Prisma.StringFilter<'WLBDailyRecord'> | string
  daysToSalaryDate?: Prisma.IntFilter<'WLBDailyRecord'> | number
  todayWeather?: Prisma.StringFilter<'WLBDailyRecord'> | string
  todayTemperature?: Prisma.StringFilter<'WLBDailyRecord'> | string
  todayWid?: Prisma.StringFilter<'WLBDailyRecord'> | string
  tomorrowWeather?: Prisma.StringFilter<'WLBDailyRecord'> | string
  tomorrowTemperature?: Prisma.StringFilter<'WLBDailyRecord'> | string
  tomorrowWid?: Prisma.StringFilter<'WLBDailyRecord'> | string
  h92?: Prisma.FloatFilter<'WLBDailyRecord'> | number
  h95?: Prisma.FloatFilter<'WLBDailyRecord'> | number
  h98?: Prisma.FloatFilter<'WLBDailyRecord'> | number
  traffic?: Prisma.StringFilter<'WLBDailyRecord'> | string
  trafficImageURL?: Prisma.StringFilter<'WLBDailyRecord'> | string
  todayStock?: Prisma.FloatNullableFilter<'WLBDailyRecord'> | number | null
  yesterdayStock?: Prisma.FloatNullableFilter<'WLBDailyRecord'> | number | null
  stockDelta?: Prisma.FloatNullableFilter<'WLBDailyRecord'> | number | null
  profileId?: Prisma.StringFilter<'WLBDailyRecord'> | string
  createdAt?: Prisma.DateTimeFilter<'WLBDailyRecord'> | Date | string
  updatedAt?: Prisma.DateTimeFilter<'WLBDailyRecord'> | Date | string
}

export type WLBDailyRecordCreateWithoutWlbNotificationRecordsInput = {
  id?: string
  date: string
  workday: boolean
  url: string
  shortURL: string
  imageURL: string
  nextSalaryDate: string
  daysToSalaryDate: number
  todayWeather: string
  todayTemperature: string
  todayWid: string
  tomorrowWeather: string
  tomorrowTemperature: string
  tomorrowWid: string
  h92: number
  h95: number
  h98: number
  traffic: string
  trafficImageURL: string
  todayStock?: number | null
  yesterdayStock?: number | null
  stockDelta?: number | null
  createdAt?: Date | string
  updatedAt?: Date | string
  profile: Prisma.WLBProfileCreateNestedOneWithoutWlbdailyRecordsInput
}

export type WLBDailyRecordUncheckedCreateWithoutWlbNotificationRecordsInput = {
  id?: string
  date: string
  workday: boolean
  url: string
  shortURL: string
  imageURL: string
  nextSalaryDate: string
  daysToSalaryDate: number
  todayWeather: string
  todayTemperature: string
  todayWid: string
  tomorrowWeather: string
  tomorrowTemperature: string
  tomorrowWid: string
  h92: number
  h95: number
  h98: number
  traffic: string
  trafficImageURL: string
  todayStock?: number | null
  yesterdayStock?: number | null
  stockDelta?: number | null
  profileId: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type WLBDailyRecordCreateOrConnectWithoutWlbNotificationRecordsInput = {
  where: Prisma.WLBDailyRecordWhereUniqueInput
  create: Prisma.XOR<
    Prisma.WLBDailyRecordCreateWithoutWlbNotificationRecordsInput,
    Prisma.WLBDailyRecordUncheckedCreateWithoutWlbNotificationRecordsInput
  >
}

export type WLBDailyRecordUpsertWithoutWlbNotificationRecordsInput = {
  update: Prisma.XOR<
    Prisma.WLBDailyRecordUpdateWithoutWlbNotificationRecordsInput,
    Prisma.WLBDailyRecordUncheckedUpdateWithoutWlbNotificationRecordsInput
  >
  create: Prisma.XOR<
    Prisma.WLBDailyRecordCreateWithoutWlbNotificationRecordsInput,
    Prisma.WLBDailyRecordUncheckedCreateWithoutWlbNotificationRecordsInput
  >
  where?: Prisma.WLBDailyRecordWhereInput
}

export type WLBDailyRecordUpdateToOneWithWhereWithoutWlbNotificationRecordsInput = {
  where?: Prisma.WLBDailyRecordWhereInput
  data: Prisma.XOR<
    Prisma.WLBDailyRecordUpdateWithoutWlbNotificationRecordsInput,
    Prisma.WLBDailyRecordUncheckedUpdateWithoutWlbNotificationRecordsInput
  >
}

export type WLBDailyRecordUpdateWithoutWlbNotificationRecordsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  date?: Prisma.StringFieldUpdateOperationsInput | string
  workday?: Prisma.BoolFieldUpdateOperationsInput | boolean
  url?: Prisma.StringFieldUpdateOperationsInput | string
  shortURL?: Prisma.StringFieldUpdateOperationsInput | string
  imageURL?: Prisma.StringFieldUpdateOperationsInput | string
  nextSalaryDate?: Prisma.StringFieldUpdateOperationsInput | string
  daysToSalaryDate?: Prisma.IntFieldUpdateOperationsInput | number
  todayWeather?: Prisma.StringFieldUpdateOperationsInput | string
  todayTemperature?: Prisma.StringFieldUpdateOperationsInput | string
  todayWid?: Prisma.StringFieldUpdateOperationsInput | string
  tomorrowWeather?: Prisma.StringFieldUpdateOperationsInput | string
  tomorrowTemperature?: Prisma.StringFieldUpdateOperationsInput | string
  tomorrowWid?: Prisma.StringFieldUpdateOperationsInput | string
  h92?: Prisma.FloatFieldUpdateOperationsInput | number
  h95?: Prisma.FloatFieldUpdateOperationsInput | number
  h98?: Prisma.FloatFieldUpdateOperationsInput | number
  traffic?: Prisma.StringFieldUpdateOperationsInput | string
  trafficImageURL?: Prisma.StringFieldUpdateOperationsInput | string
  todayStock?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  yesterdayStock?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  stockDelta?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  profile?: Prisma.WLBProfileUpdateOneRequiredWithoutWlbdailyRecordsNestedInput
}

export type WLBDailyRecordUncheckedUpdateWithoutWlbNotificationRecordsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  date?: Prisma.StringFieldUpdateOperationsInput | string
  workday?: Prisma.BoolFieldUpdateOperationsInput | boolean
  url?: Prisma.StringFieldUpdateOperationsInput | string
  shortURL?: Prisma.StringFieldUpdateOperationsInput | string
  imageURL?: Prisma.StringFieldUpdateOperationsInput | string
  nextSalaryDate?: Prisma.StringFieldUpdateOperationsInput | string
  daysToSalaryDate?: Prisma.IntFieldUpdateOperationsInput | number
  todayWeather?: Prisma.StringFieldUpdateOperationsInput | string
  todayTemperature?: Prisma.StringFieldUpdateOperationsInput | string
  todayWid?: Prisma.StringFieldUpdateOperationsInput | string
  tomorrowWeather?: Prisma.StringFieldUpdateOperationsInput | string
  tomorrowTemperature?: Prisma.StringFieldUpdateOperationsInput | string
  tomorrowWid?: Prisma.StringFieldUpdateOperationsInput | string
  h92?: Prisma.FloatFieldUpdateOperationsInput | number
  h95?: Prisma.FloatFieldUpdateOperationsInput | number
  h98?: Prisma.FloatFieldUpdateOperationsInput | number
  traffic?: Prisma.StringFieldUpdateOperationsInput | string
  trafficImageURL?: Prisma.StringFieldUpdateOperationsInput | string
  todayStock?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  yesterdayStock?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  stockDelta?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  profileId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type WLBDailyRecordCreateManyProfileInput = {
  id?: string
  date: string
  workday: boolean
  url: string
  shortURL: string
  imageURL: string
  nextSalaryDate: string
  daysToSalaryDate: number
  todayWeather: string
  todayTemperature: string
  todayWid: string
  tomorrowWeather: string
  tomorrowTemperature: string
  tomorrowWid: string
  h92: number
  h95: number
  h98: number
  traffic: string
  trafficImageURL: string
  todayStock?: number | null
  yesterdayStock?: number | null
  stockDelta?: number | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type WLBDailyRecordUpdateWithoutProfileInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  date?: Prisma.StringFieldUpdateOperationsInput | string
  workday?: Prisma.BoolFieldUpdateOperationsInput | boolean
  url?: Prisma.StringFieldUpdateOperationsInput | string
  shortURL?: Prisma.StringFieldUpdateOperationsInput | string
  imageURL?: Prisma.StringFieldUpdateOperationsInput | string
  nextSalaryDate?: Prisma.StringFieldUpdateOperationsInput | string
  daysToSalaryDate?: Prisma.IntFieldUpdateOperationsInput | number
  todayWeather?: Prisma.StringFieldUpdateOperationsInput | string
  todayTemperature?: Prisma.StringFieldUpdateOperationsInput | string
  todayWid?: Prisma.StringFieldUpdateOperationsInput | string
  tomorrowWeather?: Prisma.StringFieldUpdateOperationsInput | string
  tomorrowTemperature?: Prisma.StringFieldUpdateOperationsInput | string
  tomorrowWid?: Prisma.StringFieldUpdateOperationsInput | string
  h92?: Prisma.FloatFieldUpdateOperationsInput | number
  h95?: Prisma.FloatFieldUpdateOperationsInput | number
  h98?: Prisma.FloatFieldUpdateOperationsInput | number
  traffic?: Prisma.StringFieldUpdateOperationsInput | string
  trafficImageURL?: Prisma.StringFieldUpdateOperationsInput | string
  todayStock?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  yesterdayStock?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  stockDelta?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  wlbNotificationRecords?: Prisma.WLBNotificationRecordUpdateManyWithoutDailyRecordNestedInput
}

export type WLBDailyRecordUncheckedUpdateWithoutProfileInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  date?: Prisma.StringFieldUpdateOperationsInput | string
  workday?: Prisma.BoolFieldUpdateOperationsInput | boolean
  url?: Prisma.StringFieldUpdateOperationsInput | string
  shortURL?: Prisma.StringFieldUpdateOperationsInput | string
  imageURL?: Prisma.StringFieldUpdateOperationsInput | string
  nextSalaryDate?: Prisma.StringFieldUpdateOperationsInput | string
  daysToSalaryDate?: Prisma.IntFieldUpdateOperationsInput | number
  todayWeather?: Prisma.StringFieldUpdateOperationsInput | string
  todayTemperature?: Prisma.StringFieldUpdateOperationsInput | string
  todayWid?: Prisma.StringFieldUpdateOperationsInput | string
  tomorrowWeather?: Prisma.StringFieldUpdateOperationsInput | string
  tomorrowTemperature?: Prisma.StringFieldUpdateOperationsInput | string
  tomorrowWid?: Prisma.StringFieldUpdateOperationsInput | string
  h92?: Prisma.FloatFieldUpdateOperationsInput | number
  h95?: Prisma.FloatFieldUpdateOperationsInput | number
  h98?: Prisma.FloatFieldUpdateOperationsInput | number
  traffic?: Prisma.StringFieldUpdateOperationsInput | string
  trafficImageURL?: Prisma.StringFieldUpdateOperationsInput | string
  todayStock?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  yesterdayStock?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  stockDelta?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  wlbNotificationRecords?: Prisma.WLBNotificationRecordUncheckedUpdateManyWithoutDailyRecordNestedInput
}

export type WLBDailyRecordUncheckedUpdateManyWithoutProfileInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  date?: Prisma.StringFieldUpdateOperationsInput | string
  workday?: Prisma.BoolFieldUpdateOperationsInput | boolean
  url?: Prisma.StringFieldUpdateOperationsInput | string
  shortURL?: Prisma.StringFieldUpdateOperationsInput | string
  imageURL?: Prisma.StringFieldUpdateOperationsInput | string
  nextSalaryDate?: Prisma.StringFieldUpdateOperationsInput | string
  daysToSalaryDate?: Prisma.IntFieldUpdateOperationsInput | number
  todayWeather?: Prisma.StringFieldUpdateOperationsInput | string
  todayTemperature?: Prisma.StringFieldUpdateOperationsInput | string
  todayWid?: Prisma.StringFieldUpdateOperationsInput | string
  tomorrowWeather?: Prisma.StringFieldUpdateOperationsInput | string
  tomorrowTemperature?: Prisma.StringFieldUpdateOperationsInput | string
  tomorrowWid?: Prisma.StringFieldUpdateOperationsInput | string
  h92?: Prisma.FloatFieldUpdateOperationsInput | number
  h95?: Prisma.FloatFieldUpdateOperationsInput | number
  h98?: Prisma.FloatFieldUpdateOperationsInput | number
  traffic?: Prisma.StringFieldUpdateOperationsInput | string
  trafficImageURL?: Prisma.StringFieldUpdateOperationsInput | string
  todayStock?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  yesterdayStock?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  stockDelta?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

/**
 * Count Type WLBDailyRecordCountOutputType
 */

export type WLBDailyRecordCountOutputType = {
  wlbNotificationRecords: number
}

export type WLBDailyRecordCountOutputTypeSelect<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  wlbNotificationRecords?: boolean | WLBDailyRecordCountOutputTypeCountWlbNotificationRecordsArgs
}

/**
 * WLBDailyRecordCountOutputType without action
 */
export type WLBDailyRecordCountOutputTypeDefaultArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the WLBDailyRecordCountOutputType
   */
  select?: Prisma.WLBDailyRecordCountOutputTypeSelect<ExtArgs> | null
}

/**
 * WLBDailyRecordCountOutputType without action
 */
export type WLBDailyRecordCountOutputTypeCountWlbNotificationRecordsArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  where?: Prisma.WLBNotificationRecordWhereInput
}

export type WLBDailyRecordSelect<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = runtime.Types.Extensions.GetSelect<
  {
    id?: boolean
    date?: boolean
    workday?: boolean
    url?: boolean
    shortURL?: boolean
    imageURL?: boolean
    nextSalaryDate?: boolean
    daysToSalaryDate?: boolean
    todayWeather?: boolean
    todayTemperature?: boolean
    todayWid?: boolean
    tomorrowWeather?: boolean
    tomorrowTemperature?: boolean
    tomorrowWid?: boolean
    h92?: boolean
    h95?: boolean
    h98?: boolean
    traffic?: boolean
    trafficImageURL?: boolean
    todayStock?: boolean
    yesterdayStock?: boolean
    stockDelta?: boolean
    profileId?: boolean
    createdAt?: boolean
    updatedAt?: boolean
    profile?: boolean | Prisma.WLBProfileDefaultArgs<ExtArgs>
    wlbNotificationRecords?: boolean | Prisma.WLBDailyRecord$wlbNotificationRecordsArgs<ExtArgs>
    _count?: boolean | Prisma.WLBDailyRecordCountOutputTypeDefaultArgs<ExtArgs>
  },
  ExtArgs['result']['wLBDailyRecord']
>

export type WLBDailyRecordSelectCreateManyAndReturn<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = runtime.Types.Extensions.GetSelect<
  {
    id?: boolean
    date?: boolean
    workday?: boolean
    url?: boolean
    shortURL?: boolean
    imageURL?: boolean
    nextSalaryDate?: boolean
    daysToSalaryDate?: boolean
    todayWeather?: boolean
    todayTemperature?: boolean
    todayWid?: boolean
    tomorrowWeather?: boolean
    tomorrowTemperature?: boolean
    tomorrowWid?: boolean
    h92?: boolean
    h95?: boolean
    h98?: boolean
    traffic?: boolean
    trafficImageURL?: boolean
    todayStock?: boolean
    yesterdayStock?: boolean
    stockDelta?: boolean
    profileId?: boolean
    createdAt?: boolean
    updatedAt?: boolean
    profile?: boolean | Prisma.WLBProfileDefaultArgs<ExtArgs>
  },
  ExtArgs['result']['wLBDailyRecord']
>

export type WLBDailyRecordSelectUpdateManyAndReturn<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = runtime.Types.Extensions.GetSelect<
  {
    id?: boolean
    date?: boolean
    workday?: boolean
    url?: boolean
    shortURL?: boolean
    imageURL?: boolean
    nextSalaryDate?: boolean
    daysToSalaryDate?: boolean
    todayWeather?: boolean
    todayTemperature?: boolean
    todayWid?: boolean
    tomorrowWeather?: boolean
    tomorrowTemperature?: boolean
    tomorrowWid?: boolean
    h92?: boolean
    h95?: boolean
    h98?: boolean
    traffic?: boolean
    trafficImageURL?: boolean
    todayStock?: boolean
    yesterdayStock?: boolean
    stockDelta?: boolean
    profileId?: boolean
    createdAt?: boolean
    updatedAt?: boolean
    profile?: boolean | Prisma.WLBProfileDefaultArgs<ExtArgs>
  },
  ExtArgs['result']['wLBDailyRecord']
>

export type WLBDailyRecordSelectScalar = {
  id?: boolean
  date?: boolean
  workday?: boolean
  url?: boolean
  shortURL?: boolean
  imageURL?: boolean
  nextSalaryDate?: boolean
  daysToSalaryDate?: boolean
  todayWeather?: boolean
  todayTemperature?: boolean
  todayWid?: boolean
  tomorrowWeather?: boolean
  tomorrowTemperature?: boolean
  tomorrowWid?: boolean
  h92?: boolean
  h95?: boolean
  h98?: boolean
  traffic?: boolean
  trafficImageURL?: boolean
  todayStock?: boolean
  yesterdayStock?: boolean
  stockDelta?: boolean
  profileId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type WLBDailyRecordOmit<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = runtime.Types.Extensions.GetOmit<
  | 'id'
  | 'date'
  | 'workday'
  | 'url'
  | 'shortURL'
  | 'imageURL'
  | 'nextSalaryDate'
  | 'daysToSalaryDate'
  | 'todayWeather'
  | 'todayTemperature'
  | 'todayWid'
  | 'tomorrowWeather'
  | 'tomorrowTemperature'
  | 'tomorrowWid'
  | 'h92'
  | 'h95'
  | 'h98'
  | 'traffic'
  | 'trafficImageURL'
  | 'todayStock'
  | 'yesterdayStock'
  | 'stockDelta'
  | 'profileId'
  | 'createdAt'
  | 'updatedAt',
  ExtArgs['result']['wLBDailyRecord']
>
export type WLBDailyRecordInclude<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  profile?: boolean | Prisma.WLBProfileDefaultArgs<ExtArgs>
  wlbNotificationRecords?: boolean | Prisma.WLBDailyRecord$wlbNotificationRecordsArgs<ExtArgs>
  _count?: boolean | Prisma.WLBDailyRecordCountOutputTypeDefaultArgs<ExtArgs>
}
export type WLBDailyRecordIncludeCreateManyAndReturn<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  profile?: boolean | Prisma.WLBProfileDefaultArgs<ExtArgs>
}
export type WLBDailyRecordIncludeUpdateManyAndReturn<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  profile?: boolean | Prisma.WLBProfileDefaultArgs<ExtArgs>
}

export type $WLBDailyRecordPayload<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  name: 'WLBDailyRecord'
  objects: {
    profile: Prisma.$WLBProfilePayload<ExtArgs>
    wlbNotificationRecords: Prisma.$WLBNotificationRecordPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<
    {
      id: string
      date: string
      workday: boolean
      url: string
      shortURL: string
      imageURL: string
      nextSalaryDate: string
      daysToSalaryDate: number
      todayWeather: string
      todayTemperature: string
      todayWid: string
      tomorrowWeather: string
      tomorrowTemperature: string
      tomorrowWid: string
      h92: number
      h95: number
      h98: number
      traffic: string
      trafficImageURL: string
      todayStock: number | null
      yesterdayStock: number | null
      stockDelta: number | null
      profileId: string
      createdAt: Date
      updatedAt: Date
    },
    ExtArgs['result']['wLBDailyRecord']
  >
  composites: {}
}

export type WLBDailyRecordGetPayload<
  S extends boolean | null | undefined | WLBDailyRecordDefaultArgs,
> = runtime.Types.Result.GetResult<Prisma.$WLBDailyRecordPayload, S>

export type WLBDailyRecordCountArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = Omit<WLBDailyRecordFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
  select?: WLBDailyRecordCountAggregateInputType | true
}

export interface WLBDailyRecordDelegate<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
  GlobalOmitOptions = {},
> {
  [K: symbol]: {
    types: Prisma.TypeMap<ExtArgs>['model']['WLBDailyRecord']
    meta: { name: 'WLBDailyRecord' }
  }
  /**
   * Find zero or one WLBDailyRecord that matches the filter.
   * @param {WLBDailyRecordFindUniqueArgs} args - Arguments to find a WLBDailyRecord
   * @example
   * // Get one WLBDailyRecord
   * const wLBDailyRecord = await prisma.wLBDailyRecord.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends WLBDailyRecordFindUniqueArgs>(
    args: Prisma.SelectSubset<T, WLBDailyRecordFindUniqueArgs<ExtArgs>>
  ): Prisma.Prisma__WLBDailyRecordClient<
    runtime.Types.Result.GetResult<
      Prisma.$WLBDailyRecordPayload<ExtArgs>,
      T,
      'findUnique',
      GlobalOmitOptions
    > | null,
    null,
    ExtArgs,
    GlobalOmitOptions
  >

  /**
   * Find one WLBDailyRecord that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {WLBDailyRecordFindUniqueOrThrowArgs} args - Arguments to find a WLBDailyRecord
   * @example
   * // Get one WLBDailyRecord
   * const wLBDailyRecord = await prisma.wLBDailyRecord.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends WLBDailyRecordFindUniqueOrThrowArgs>(
    args: Prisma.SelectSubset<T, WLBDailyRecordFindUniqueOrThrowArgs<ExtArgs>>
  ): Prisma.Prisma__WLBDailyRecordClient<
    runtime.Types.Result.GetResult<
      Prisma.$WLBDailyRecordPayload<ExtArgs>,
      T,
      'findUniqueOrThrow',
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >

  /**
   * Find the first WLBDailyRecord that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {WLBDailyRecordFindFirstArgs} args - Arguments to find a WLBDailyRecord
   * @example
   * // Get one WLBDailyRecord
   * const wLBDailyRecord = await prisma.wLBDailyRecord.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends WLBDailyRecordFindFirstArgs>(
    args?: Prisma.SelectSubset<T, WLBDailyRecordFindFirstArgs<ExtArgs>>
  ): Prisma.Prisma__WLBDailyRecordClient<
    runtime.Types.Result.GetResult<
      Prisma.$WLBDailyRecordPayload<ExtArgs>,
      T,
      'findFirst',
      GlobalOmitOptions
    > | null,
    null,
    ExtArgs,
    GlobalOmitOptions
  >

  /**
   * Find the first WLBDailyRecord that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {WLBDailyRecordFindFirstOrThrowArgs} args - Arguments to find a WLBDailyRecord
   * @example
   * // Get one WLBDailyRecord
   * const wLBDailyRecord = await prisma.wLBDailyRecord.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends WLBDailyRecordFindFirstOrThrowArgs>(
    args?: Prisma.SelectSubset<T, WLBDailyRecordFindFirstOrThrowArgs<ExtArgs>>
  ): Prisma.Prisma__WLBDailyRecordClient<
    runtime.Types.Result.GetResult<
      Prisma.$WLBDailyRecordPayload<ExtArgs>,
      T,
      'findFirstOrThrow',
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >

  /**
   * Find zero or more WLBDailyRecords that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {WLBDailyRecordFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all WLBDailyRecords
   * const wLBDailyRecords = await prisma.wLBDailyRecord.findMany()
   *
   * // Get first 10 WLBDailyRecords
   * const wLBDailyRecords = await prisma.wLBDailyRecord.findMany({ take: 10 })
   *
   * // Only select the `id`
   * const wLBDailyRecordWithIdOnly = await prisma.wLBDailyRecord.findMany({ select: { id: true } })
   *
   */
  findMany<T extends WLBDailyRecordFindManyArgs>(
    args?: Prisma.SelectSubset<T, WLBDailyRecordFindManyArgs<ExtArgs>>
  ): Prisma.PrismaPromise<
    runtime.Types.Result.GetResult<
      Prisma.$WLBDailyRecordPayload<ExtArgs>,
      T,
      'findMany',
      GlobalOmitOptions
    >
  >

  /**
   * Create a WLBDailyRecord.
   * @param {WLBDailyRecordCreateArgs} args - Arguments to create a WLBDailyRecord.
   * @example
   * // Create one WLBDailyRecord
   * const WLBDailyRecord = await prisma.wLBDailyRecord.create({
   *   data: {
   *     // ... data to create a WLBDailyRecord
   *   }
   * })
   *
   */
  create<T extends WLBDailyRecordCreateArgs>(
    args: Prisma.SelectSubset<T, WLBDailyRecordCreateArgs<ExtArgs>>
  ): Prisma.Prisma__WLBDailyRecordClient<
    runtime.Types.Result.GetResult<
      Prisma.$WLBDailyRecordPayload<ExtArgs>,
      T,
      'create',
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >

  /**
   * Create many WLBDailyRecords.
   * @param {WLBDailyRecordCreateManyArgs} args - Arguments to create many WLBDailyRecords.
   * @example
   * // Create many WLBDailyRecords
   * const wLBDailyRecord = await prisma.wLBDailyRecord.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *
   */
  createMany<T extends WLBDailyRecordCreateManyArgs>(
    args?: Prisma.SelectSubset<T, WLBDailyRecordCreateManyArgs<ExtArgs>>
  ): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many WLBDailyRecords and returns the data saved in the database.
   * @param {WLBDailyRecordCreateManyAndReturnArgs} args - Arguments to create many WLBDailyRecords.
   * @example
   * // Create many WLBDailyRecords
   * const wLBDailyRecord = await prisma.wLBDailyRecord.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *
   * // Create many WLBDailyRecords and only return the `id`
   * const wLBDailyRecordWithIdOnly = await prisma.wLBDailyRecord.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   *
   */
  createManyAndReturn<T extends WLBDailyRecordCreateManyAndReturnArgs>(
    args?: Prisma.SelectSubset<T, WLBDailyRecordCreateManyAndReturnArgs<ExtArgs>>
  ): Prisma.PrismaPromise<
    runtime.Types.Result.GetResult<
      Prisma.$WLBDailyRecordPayload<ExtArgs>,
      T,
      'createManyAndReturn',
      GlobalOmitOptions
    >
  >

  /**
   * Delete a WLBDailyRecord.
   * @param {WLBDailyRecordDeleteArgs} args - Arguments to delete one WLBDailyRecord.
   * @example
   * // Delete one WLBDailyRecord
   * const WLBDailyRecord = await prisma.wLBDailyRecord.delete({
   *   where: {
   *     // ... filter to delete one WLBDailyRecord
   *   }
   * })
   *
   */
  delete<T extends WLBDailyRecordDeleteArgs>(
    args: Prisma.SelectSubset<T, WLBDailyRecordDeleteArgs<ExtArgs>>
  ): Prisma.Prisma__WLBDailyRecordClient<
    runtime.Types.Result.GetResult<
      Prisma.$WLBDailyRecordPayload<ExtArgs>,
      T,
      'delete',
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >

  /**
   * Update one WLBDailyRecord.
   * @param {WLBDailyRecordUpdateArgs} args - Arguments to update one WLBDailyRecord.
   * @example
   * // Update one WLBDailyRecord
   * const wLBDailyRecord = await prisma.wLBDailyRecord.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   *
   */
  update<T extends WLBDailyRecordUpdateArgs>(
    args: Prisma.SelectSubset<T, WLBDailyRecordUpdateArgs<ExtArgs>>
  ): Prisma.Prisma__WLBDailyRecordClient<
    runtime.Types.Result.GetResult<
      Prisma.$WLBDailyRecordPayload<ExtArgs>,
      T,
      'update',
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >

  /**
   * Delete zero or more WLBDailyRecords.
   * @param {WLBDailyRecordDeleteManyArgs} args - Arguments to filter WLBDailyRecords to delete.
   * @example
   * // Delete a few WLBDailyRecords
   * const { count } = await prisma.wLBDailyRecord.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   *
   */
  deleteMany<T extends WLBDailyRecordDeleteManyArgs>(
    args?: Prisma.SelectSubset<T, WLBDailyRecordDeleteManyArgs<ExtArgs>>
  ): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more WLBDailyRecords.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {WLBDailyRecordUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many WLBDailyRecords
   * const wLBDailyRecord = await prisma.wLBDailyRecord.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   *
   */
  updateMany<T extends WLBDailyRecordUpdateManyArgs>(
    args: Prisma.SelectSubset<T, WLBDailyRecordUpdateManyArgs<ExtArgs>>
  ): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more WLBDailyRecords and returns the data updated in the database.
   * @param {WLBDailyRecordUpdateManyAndReturnArgs} args - Arguments to update many WLBDailyRecords.
   * @example
   * // Update many WLBDailyRecords
   * const wLBDailyRecord = await prisma.wLBDailyRecord.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *
   * // Update zero or more WLBDailyRecords and only return the `id`
   * const wLBDailyRecordWithIdOnly = await prisma.wLBDailyRecord.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   *
   */
  updateManyAndReturn<T extends WLBDailyRecordUpdateManyAndReturnArgs>(
    args: Prisma.SelectSubset<T, WLBDailyRecordUpdateManyAndReturnArgs<ExtArgs>>
  ): Prisma.PrismaPromise<
    runtime.Types.Result.GetResult<
      Prisma.$WLBDailyRecordPayload<ExtArgs>,
      T,
      'updateManyAndReturn',
      GlobalOmitOptions
    >
  >

  /**
   * Create or update one WLBDailyRecord.
   * @param {WLBDailyRecordUpsertArgs} args - Arguments to update or create a WLBDailyRecord.
   * @example
   * // Update or create a WLBDailyRecord
   * const wLBDailyRecord = await prisma.wLBDailyRecord.upsert({
   *   create: {
   *     // ... data to create a WLBDailyRecord
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the WLBDailyRecord we want to update
   *   }
   * })
   */
  upsert<T extends WLBDailyRecordUpsertArgs>(
    args: Prisma.SelectSubset<T, WLBDailyRecordUpsertArgs<ExtArgs>>
  ): Prisma.Prisma__WLBDailyRecordClient<
    runtime.Types.Result.GetResult<
      Prisma.$WLBDailyRecordPayload<ExtArgs>,
      T,
      'upsert',
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >

  /**
   * Count the number of WLBDailyRecords.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {WLBDailyRecordCountArgs} args - Arguments to filter WLBDailyRecords to count.
   * @example
   * // Count the number of WLBDailyRecords
   * const count = await prisma.wLBDailyRecord.count({
   *   where: {
   *     // ... the filter for the WLBDailyRecords we want to count
   *   }
   * })
   **/
  count<T extends WLBDailyRecordCountArgs>(
    args?: Prisma.Subset<T, WLBDailyRecordCountArgs>
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], WLBDailyRecordCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a WLBDailyRecord.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {WLBDailyRecordAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
   **/
  aggregate<T extends WLBDailyRecordAggregateArgs>(
    args: Prisma.Subset<T, WLBDailyRecordAggregateArgs>
  ): Prisma.PrismaPromise<GetWLBDailyRecordAggregateType<T>>

  /**
   * Group by WLBDailyRecord.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {WLBDailyRecordGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   *
   **/
  groupBy<
    T extends WLBDailyRecordGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: WLBDailyRecordGroupByArgs['orderBy'] }
      : { orderBy?: WLBDailyRecordGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<
      Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>
    >,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
      ? `Error: "by" must not be empty.`
      : HavingValid extends Prisma.False
        ? {
            [P in HavingFields]: P extends ByFields
              ? never
              : P extends string
                ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
                : [Error, 'Field ', P, ` in "having" needs to be provided in "by"`]
          }[HavingFields]
        : 'take' extends Prisma.Keys<T>
          ? 'orderBy' extends Prisma.Keys<T>
            ? ByValid extends Prisma.True
              ? {}
              : {
                  [P in OrderFields]: P extends ByFields
                    ? never
                    : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
                }[OrderFields]
            : 'Error: If you provide "take", you also need to provide "orderBy"'
          : 'skip' extends Prisma.Keys<T>
            ? 'orderBy' extends Prisma.Keys<T>
              ? ByValid extends Prisma.True
                ? {}
                : {
                    [P in OrderFields]: P extends ByFields
                      ? never
                      : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
                  }[OrderFields]
              : 'Error: If you provide "skip", you also need to provide "orderBy"'
            : ByValid extends Prisma.True
              ? {}
              : {
                  [P in OrderFields]: P extends ByFields
                    ? never
                    : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
                }[OrderFields],
  >(
    args: Prisma.SubsetIntersection<T, WLBDailyRecordGroupByArgs, OrderByArg> & InputErrors
  ): {} extends InputErrors ? GetWLBDailyRecordGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
  /**
   * Fields of the WLBDailyRecord model
   */
  readonly fields: WLBDailyRecordFieldRefs
}

/**
 * The delegate class that acts as a "Promise-like" for WLBDailyRecord.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__WLBDailyRecordClient<
  T,
  Null = never,
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
  GlobalOmitOptions = {},
> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: 'PrismaPromise'
  profile<T extends Prisma.WLBProfileDefaultArgs<ExtArgs> = {}>(
    args?: Prisma.Subset<T, Prisma.WLBProfileDefaultArgs<ExtArgs>>
  ): Prisma.Prisma__WLBProfileClient<
    | runtime.Types.Result.GetResult<
        Prisma.$WLBProfilePayload<ExtArgs>,
        T,
        'findUniqueOrThrow',
        GlobalOmitOptions
      >
    | Null,
    Null,
    ExtArgs,
    GlobalOmitOptions
  >
  wlbNotificationRecords<T extends Prisma.WLBDailyRecord$wlbNotificationRecordsArgs<ExtArgs> = {}>(
    args?: Prisma.Subset<T, Prisma.WLBDailyRecord$wlbNotificationRecordsArgs<ExtArgs>>
  ): Prisma.PrismaPromise<
    | runtime.Types.Result.GetResult<
        Prisma.$WLBNotificationRecordPayload<ExtArgs>,
        T,
        'findMany',
        GlobalOmitOptions
      >
    | Null
  >
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(
    onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null,
    onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null
  ): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(
    onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null
  ): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}

/**
 * Fields of the WLBDailyRecord model
 */
export interface WLBDailyRecordFieldRefs {
  readonly id: Prisma.FieldRef<'WLBDailyRecord', 'String'>
  readonly date: Prisma.FieldRef<'WLBDailyRecord', 'String'>
  readonly workday: Prisma.FieldRef<'WLBDailyRecord', 'Boolean'>
  readonly url: Prisma.FieldRef<'WLBDailyRecord', 'String'>
  readonly shortURL: Prisma.FieldRef<'WLBDailyRecord', 'String'>
  readonly imageURL: Prisma.FieldRef<'WLBDailyRecord', 'String'>
  readonly nextSalaryDate: Prisma.FieldRef<'WLBDailyRecord', 'String'>
  readonly daysToSalaryDate: Prisma.FieldRef<'WLBDailyRecord', 'Int'>
  readonly todayWeather: Prisma.FieldRef<'WLBDailyRecord', 'String'>
  readonly todayTemperature: Prisma.FieldRef<'WLBDailyRecord', 'String'>
  readonly todayWid: Prisma.FieldRef<'WLBDailyRecord', 'String'>
  readonly tomorrowWeather: Prisma.FieldRef<'WLBDailyRecord', 'String'>
  readonly tomorrowTemperature: Prisma.FieldRef<'WLBDailyRecord', 'String'>
  readonly tomorrowWid: Prisma.FieldRef<'WLBDailyRecord', 'String'>
  readonly h92: Prisma.FieldRef<'WLBDailyRecord', 'Float'>
  readonly h95: Prisma.FieldRef<'WLBDailyRecord', 'Float'>
  readonly h98: Prisma.FieldRef<'WLBDailyRecord', 'Float'>
  readonly traffic: Prisma.FieldRef<'WLBDailyRecord', 'String'>
  readonly trafficImageURL: Prisma.FieldRef<'WLBDailyRecord', 'String'>
  readonly todayStock: Prisma.FieldRef<'WLBDailyRecord', 'Float'>
  readonly yesterdayStock: Prisma.FieldRef<'WLBDailyRecord', 'Float'>
  readonly stockDelta: Prisma.FieldRef<'WLBDailyRecord', 'Float'>
  readonly profileId: Prisma.FieldRef<'WLBDailyRecord', 'String'>
  readonly createdAt: Prisma.FieldRef<'WLBDailyRecord', 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<'WLBDailyRecord', 'DateTime'>
}

// Custom InputTypes
/**
 * WLBDailyRecord findUnique
 */
export type WLBDailyRecordFindUniqueArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the WLBDailyRecord
   */
  select?: Prisma.WLBDailyRecordSelect<ExtArgs> | null
  /**
   * Omit specific fields from the WLBDailyRecord
   */
  omit?: Prisma.WLBDailyRecordOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WLBDailyRecordInclude<ExtArgs> | null
  /**
   * Filter, which WLBDailyRecord to fetch.
   */
  where: Prisma.WLBDailyRecordWhereUniqueInput
}

/**
 * WLBDailyRecord findUniqueOrThrow
 */
export type WLBDailyRecordFindUniqueOrThrowArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the WLBDailyRecord
   */
  select?: Prisma.WLBDailyRecordSelect<ExtArgs> | null
  /**
   * Omit specific fields from the WLBDailyRecord
   */
  omit?: Prisma.WLBDailyRecordOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WLBDailyRecordInclude<ExtArgs> | null
  /**
   * Filter, which WLBDailyRecord to fetch.
   */
  where: Prisma.WLBDailyRecordWhereUniqueInput
}

/**
 * WLBDailyRecord findFirst
 */
export type WLBDailyRecordFindFirstArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the WLBDailyRecord
   */
  select?: Prisma.WLBDailyRecordSelect<ExtArgs> | null
  /**
   * Omit specific fields from the WLBDailyRecord
   */
  omit?: Prisma.WLBDailyRecordOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WLBDailyRecordInclude<ExtArgs> | null
  /**
   * Filter, which WLBDailyRecord to fetch.
   */
  where?: Prisma.WLBDailyRecordWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   *
   * Determine the order of WLBDailyRecords to fetch.
   */
  orderBy?:
    | Prisma.WLBDailyRecordOrderByWithRelationInput
    | Prisma.WLBDailyRecordOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   *
   * Sets the position for searching for WLBDailyRecords.
   */
  cursor?: Prisma.WLBDailyRecordWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Take `±n` WLBDailyRecords from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Skip the first `n` WLBDailyRecords.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   *
   * Filter by unique combinations of WLBDailyRecords.
   */
  distinct?: Prisma.WLBDailyRecordScalarFieldEnum | Prisma.WLBDailyRecordScalarFieldEnum[]
}

/**
 * WLBDailyRecord findFirstOrThrow
 */
export type WLBDailyRecordFindFirstOrThrowArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the WLBDailyRecord
   */
  select?: Prisma.WLBDailyRecordSelect<ExtArgs> | null
  /**
   * Omit specific fields from the WLBDailyRecord
   */
  omit?: Prisma.WLBDailyRecordOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WLBDailyRecordInclude<ExtArgs> | null
  /**
   * Filter, which WLBDailyRecord to fetch.
   */
  where?: Prisma.WLBDailyRecordWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   *
   * Determine the order of WLBDailyRecords to fetch.
   */
  orderBy?:
    | Prisma.WLBDailyRecordOrderByWithRelationInput
    | Prisma.WLBDailyRecordOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   *
   * Sets the position for searching for WLBDailyRecords.
   */
  cursor?: Prisma.WLBDailyRecordWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Take `±n` WLBDailyRecords from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Skip the first `n` WLBDailyRecords.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   *
   * Filter by unique combinations of WLBDailyRecords.
   */
  distinct?: Prisma.WLBDailyRecordScalarFieldEnum | Prisma.WLBDailyRecordScalarFieldEnum[]
}

/**
 * WLBDailyRecord findMany
 */
export type WLBDailyRecordFindManyArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the WLBDailyRecord
   */
  select?: Prisma.WLBDailyRecordSelect<ExtArgs> | null
  /**
   * Omit specific fields from the WLBDailyRecord
   */
  omit?: Prisma.WLBDailyRecordOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WLBDailyRecordInclude<ExtArgs> | null
  /**
   * Filter, which WLBDailyRecords to fetch.
   */
  where?: Prisma.WLBDailyRecordWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   *
   * Determine the order of WLBDailyRecords to fetch.
   */
  orderBy?:
    | Prisma.WLBDailyRecordOrderByWithRelationInput
    | Prisma.WLBDailyRecordOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   *
   * Sets the position for listing WLBDailyRecords.
   */
  cursor?: Prisma.WLBDailyRecordWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Take `±n` WLBDailyRecords from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Skip the first `n` WLBDailyRecords.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   *
   * Filter by unique combinations of WLBDailyRecords.
   */
  distinct?: Prisma.WLBDailyRecordScalarFieldEnum | Prisma.WLBDailyRecordScalarFieldEnum[]
}

/**
 * WLBDailyRecord create
 */
export type WLBDailyRecordCreateArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the WLBDailyRecord
   */
  select?: Prisma.WLBDailyRecordSelect<ExtArgs> | null
  /**
   * Omit specific fields from the WLBDailyRecord
   */
  omit?: Prisma.WLBDailyRecordOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WLBDailyRecordInclude<ExtArgs> | null
  /**
   * The data needed to create a WLBDailyRecord.
   */
  data: Prisma.XOR<Prisma.WLBDailyRecordCreateInput, Prisma.WLBDailyRecordUncheckedCreateInput>
}

/**
 * WLBDailyRecord createMany
 */
export type WLBDailyRecordCreateManyArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * The data used to create many WLBDailyRecords.
   */
  data: Prisma.WLBDailyRecordCreateManyInput | Prisma.WLBDailyRecordCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * WLBDailyRecord createManyAndReturn
 */
export type WLBDailyRecordCreateManyAndReturnArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the WLBDailyRecord
   */
  select?: Prisma.WLBDailyRecordSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the WLBDailyRecord
   */
  omit?: Prisma.WLBDailyRecordOmit<ExtArgs> | null
  /**
   * The data used to create many WLBDailyRecords.
   */
  data: Prisma.WLBDailyRecordCreateManyInput | Prisma.WLBDailyRecordCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WLBDailyRecordIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * WLBDailyRecord update
 */
export type WLBDailyRecordUpdateArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the WLBDailyRecord
   */
  select?: Prisma.WLBDailyRecordSelect<ExtArgs> | null
  /**
   * Omit specific fields from the WLBDailyRecord
   */
  omit?: Prisma.WLBDailyRecordOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WLBDailyRecordInclude<ExtArgs> | null
  /**
   * The data needed to update a WLBDailyRecord.
   */
  data: Prisma.XOR<Prisma.WLBDailyRecordUpdateInput, Prisma.WLBDailyRecordUncheckedUpdateInput>
  /**
   * Choose, which WLBDailyRecord to update.
   */
  where: Prisma.WLBDailyRecordWhereUniqueInput
}

/**
 * WLBDailyRecord updateMany
 */
export type WLBDailyRecordUpdateManyArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * The data used to update WLBDailyRecords.
   */
  data: Prisma.XOR<
    Prisma.WLBDailyRecordUpdateManyMutationInput,
    Prisma.WLBDailyRecordUncheckedUpdateManyInput
  >
  /**
   * Filter which WLBDailyRecords to update
   */
  where?: Prisma.WLBDailyRecordWhereInput
  /**
   * Limit how many WLBDailyRecords to update.
   */
  limit?: number
}

/**
 * WLBDailyRecord updateManyAndReturn
 */
export type WLBDailyRecordUpdateManyAndReturnArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the WLBDailyRecord
   */
  select?: Prisma.WLBDailyRecordSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the WLBDailyRecord
   */
  omit?: Prisma.WLBDailyRecordOmit<ExtArgs> | null
  /**
   * The data used to update WLBDailyRecords.
   */
  data: Prisma.XOR<
    Prisma.WLBDailyRecordUpdateManyMutationInput,
    Prisma.WLBDailyRecordUncheckedUpdateManyInput
  >
  /**
   * Filter which WLBDailyRecords to update
   */
  where?: Prisma.WLBDailyRecordWhereInput
  /**
   * Limit how many WLBDailyRecords to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WLBDailyRecordIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * WLBDailyRecord upsert
 */
export type WLBDailyRecordUpsertArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the WLBDailyRecord
   */
  select?: Prisma.WLBDailyRecordSelect<ExtArgs> | null
  /**
   * Omit specific fields from the WLBDailyRecord
   */
  omit?: Prisma.WLBDailyRecordOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WLBDailyRecordInclude<ExtArgs> | null
  /**
   * The filter to search for the WLBDailyRecord to update in case it exists.
   */
  where: Prisma.WLBDailyRecordWhereUniqueInput
  /**
   * In case the WLBDailyRecord found by the `where` argument doesn't exist, create a new WLBDailyRecord with this data.
   */
  create: Prisma.XOR<Prisma.WLBDailyRecordCreateInput, Prisma.WLBDailyRecordUncheckedCreateInput>
  /**
   * In case the WLBDailyRecord was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.WLBDailyRecordUpdateInput, Prisma.WLBDailyRecordUncheckedUpdateInput>
}

/**
 * WLBDailyRecord delete
 */
export type WLBDailyRecordDeleteArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the WLBDailyRecord
   */
  select?: Prisma.WLBDailyRecordSelect<ExtArgs> | null
  /**
   * Omit specific fields from the WLBDailyRecord
   */
  omit?: Prisma.WLBDailyRecordOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WLBDailyRecordInclude<ExtArgs> | null
  /**
   * Filter which WLBDailyRecord to delete.
   */
  where: Prisma.WLBDailyRecordWhereUniqueInput
}

/**
 * WLBDailyRecord deleteMany
 */
export type WLBDailyRecordDeleteManyArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Filter which WLBDailyRecords to delete
   */
  where?: Prisma.WLBDailyRecordWhereInput
  /**
   * Limit how many WLBDailyRecords to delete.
   */
  limit?: number
}

/**
 * WLBDailyRecord.wlbNotificationRecords
 */
export type WLBDailyRecord$wlbNotificationRecordsArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the WLBNotificationRecord
   */
  select?: Prisma.WLBNotificationRecordSelect<ExtArgs> | null
  /**
   * Omit specific fields from the WLBNotificationRecord
   */
  omit?: Prisma.WLBNotificationRecordOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WLBNotificationRecordInclude<ExtArgs> | null
  where?: Prisma.WLBNotificationRecordWhereInput
  orderBy?:
    | Prisma.WLBNotificationRecordOrderByWithRelationInput
    | Prisma.WLBNotificationRecordOrderByWithRelationInput[]
  cursor?: Prisma.WLBNotificationRecordWhereUniqueInput
  take?: number
  skip?: number
  distinct?:
    | Prisma.WLBNotificationRecordScalarFieldEnum
    | Prisma.WLBNotificationRecordScalarFieldEnum[]
}

/**
 * WLBDailyRecord without action
 */
export type WLBDailyRecordDefaultArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the WLBDailyRecord
   */
  select?: Prisma.WLBDailyRecordSelect<ExtArgs> | null
  /**
   * Omit specific fields from the WLBDailyRecord
   */
  omit?: Prisma.WLBDailyRecordOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WLBDailyRecordInclude<ExtArgs> | null
}
