/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck
/*
 * This file exports the `WLBNotificationRecord` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from '@prisma/client/runtime/client'

import type * as $Enums from '../enums'
import type * as Prisma from '../internal/prismaNamespace'

/**
 * Model WLBNotificationRecord
 * WLB 通知发送记录
 */
export type WLBNotificationRecordModel =
  runtime.Types.Result.DefaultSelection<Prisma.$WLBNotificationRecordPayload>

export type AggregateWLBNotificationRecord = {
  _count: WLBNotificationRecordCountAggregateOutputType | null
  _min: WLBNotificationRecordMinAggregateOutputType | null
  _max: WLBNotificationRecordMaxAggregateOutputType | null
}

export type WLBNotificationRecordMinAggregateOutputType = {
  id: string | null
  ok: boolean | null
  dailyRecordId: string | null
  wlbSubscriptionId: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type WLBNotificationRecordMaxAggregateOutputType = {
  id: string | null
  ok: boolean | null
  dailyRecordId: string | null
  wlbSubscriptionId: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type WLBNotificationRecordCountAggregateOutputType = {
  id: number
  ok: number
  dailyRecordId: number
  wlbSubscriptionId: number
  createdAt: number
  updatedAt: number
  _all: number
}

export type WLBNotificationRecordMinAggregateInputType = {
  id?: true
  ok?: true
  dailyRecordId?: true
  wlbSubscriptionId?: true
  createdAt?: true
  updatedAt?: true
}

export type WLBNotificationRecordMaxAggregateInputType = {
  id?: true
  ok?: true
  dailyRecordId?: true
  wlbSubscriptionId?: true
  createdAt?: true
  updatedAt?: true
}

export type WLBNotificationRecordCountAggregateInputType = {
  id?: true
  ok?: true
  dailyRecordId?: true
  wlbSubscriptionId?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type WLBNotificationRecordAggregateArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Filter which WLBNotificationRecord to aggregate.
   */
  where?: Prisma.WLBNotificationRecordWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   *
   * Determine the order of WLBNotificationRecords to fetch.
   */
  orderBy?:
    | Prisma.WLBNotificationRecordOrderByWithRelationInput
    | Prisma.WLBNotificationRecordOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   *
   * Sets the start position
   */
  cursor?: Prisma.WLBNotificationRecordWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Take `±n` WLBNotificationRecords from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Skip the first `n` WLBNotificationRecords.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   *
   * Count returned WLBNotificationRecords
   **/
  _count?: true | WLBNotificationRecordCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   *
   * Select which fields to find the minimum value
   **/
  _min?: WLBNotificationRecordMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   *
   * Select which fields to find the maximum value
   **/
  _max?: WLBNotificationRecordMaxAggregateInputType
}

export type GetWLBNotificationRecordAggregateType<T extends WLBNotificationRecordAggregateArgs> = {
  [P in keyof T & keyof AggregateWLBNotificationRecord]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateWLBNotificationRecord[P]>
    : Prisma.GetScalarType<T[P], AggregateWLBNotificationRecord[P]>
}

export type WLBNotificationRecordGroupByArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  where?: Prisma.WLBNotificationRecordWhereInput
  orderBy?:
    | Prisma.WLBNotificationRecordOrderByWithAggregationInput
    | Prisma.WLBNotificationRecordOrderByWithAggregationInput[]
  by: Prisma.WLBNotificationRecordScalarFieldEnum[] | Prisma.WLBNotificationRecordScalarFieldEnum
  having?: Prisma.WLBNotificationRecordScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: WLBNotificationRecordCountAggregateInputType | true
  _min?: WLBNotificationRecordMinAggregateInputType
  _max?: WLBNotificationRecordMaxAggregateInputType
}

export type WLBNotificationRecordGroupByOutputType = {
  id: string
  ok: boolean
  dailyRecordId: string | null
  wlbSubscriptionId: string | null
  createdAt: Date
  updatedAt: Date
  _count: WLBNotificationRecordCountAggregateOutputType | null
  _min: WLBNotificationRecordMinAggregateOutputType | null
  _max: WLBNotificationRecordMaxAggregateOutputType | null
}

export type GetWLBNotificationRecordGroupByPayload<T extends WLBNotificationRecordGroupByArgs> =
  Prisma.PrismaPromise<
    Array<
      Prisma.PickEnumerable<WLBNotificationRecordGroupByOutputType, T['by']> & {
        [P in keyof T & keyof WLBNotificationRecordGroupByOutputType]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], WLBNotificationRecordGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], WLBNotificationRecordGroupByOutputType[P]>
      }
    >
  >

export type WLBNotificationRecordWhereInput = {
  AND?: Prisma.WLBNotificationRecordWhereInput | Prisma.WLBNotificationRecordWhereInput[]
  OR?: Prisma.WLBNotificationRecordWhereInput[]
  NOT?: Prisma.WLBNotificationRecordWhereInput | Prisma.WLBNotificationRecordWhereInput[]
  id?: Prisma.StringFilter<'WLBNotificationRecord'> | string
  ok?: Prisma.BoolFilter<'WLBNotificationRecord'> | boolean
  dailyRecordId?: Prisma.StringNullableFilter<'WLBNotificationRecord'> | string | null
  wlbSubscriptionId?: Prisma.StringNullableFilter<'WLBNotificationRecord'> | string | null
  createdAt?: Prisma.DateTimeFilter<'WLBNotificationRecord'> | Date | string
  updatedAt?: Prisma.DateTimeFilter<'WLBNotificationRecord'> | Date | string
  dailyRecord?: Prisma.XOR<
    Prisma.WLBDailyRecordNullableScalarRelationFilter,
    Prisma.WLBDailyRecordWhereInput
  > | null
  subscription?: Prisma.XOR<
    Prisma.WLBSubscriptionNullableScalarRelationFilter,
    Prisma.WLBSubscriptionWhereInput
  > | null
}

export type WLBNotificationRecordOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  ok?: Prisma.SortOrder
  dailyRecordId?: Prisma.SortOrderInput | Prisma.SortOrder
  wlbSubscriptionId?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  dailyRecord?: Prisma.WLBDailyRecordOrderByWithRelationInput
  subscription?: Prisma.WLBSubscriptionOrderByWithRelationInput
}

export type WLBNotificationRecordWhereUniqueInput = Prisma.AtLeast<
  {
    id?: string
    AND?: Prisma.WLBNotificationRecordWhereInput | Prisma.WLBNotificationRecordWhereInput[]
    OR?: Prisma.WLBNotificationRecordWhereInput[]
    NOT?: Prisma.WLBNotificationRecordWhereInput | Prisma.WLBNotificationRecordWhereInput[]
    ok?: Prisma.BoolFilter<'WLBNotificationRecord'> | boolean
    dailyRecordId?: Prisma.StringNullableFilter<'WLBNotificationRecord'> | string | null
    wlbSubscriptionId?: Prisma.StringNullableFilter<'WLBNotificationRecord'> | string | null
    createdAt?: Prisma.DateTimeFilter<'WLBNotificationRecord'> | Date | string
    updatedAt?: Prisma.DateTimeFilter<'WLBNotificationRecord'> | Date | string
    dailyRecord?: Prisma.XOR<
      Prisma.WLBDailyRecordNullableScalarRelationFilter,
      Prisma.WLBDailyRecordWhereInput
    > | null
    subscription?: Prisma.XOR<
      Prisma.WLBSubscriptionNullableScalarRelationFilter,
      Prisma.WLBSubscriptionWhereInput
    > | null
  },
  'id'
>

export type WLBNotificationRecordOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  ok?: Prisma.SortOrder
  dailyRecordId?: Prisma.SortOrderInput | Prisma.SortOrder
  wlbSubscriptionId?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.WLBNotificationRecordCountOrderByAggregateInput
  _max?: Prisma.WLBNotificationRecordMaxOrderByAggregateInput
  _min?: Prisma.WLBNotificationRecordMinOrderByAggregateInput
}

export type WLBNotificationRecordScalarWhereWithAggregatesInput = {
  AND?:
    | Prisma.WLBNotificationRecordScalarWhereWithAggregatesInput
    | Prisma.WLBNotificationRecordScalarWhereWithAggregatesInput[]
  OR?: Prisma.WLBNotificationRecordScalarWhereWithAggregatesInput[]
  NOT?:
    | Prisma.WLBNotificationRecordScalarWhereWithAggregatesInput
    | Prisma.WLBNotificationRecordScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<'WLBNotificationRecord'> | string
  ok?: Prisma.BoolWithAggregatesFilter<'WLBNotificationRecord'> | boolean
  dailyRecordId?: Prisma.StringNullableWithAggregatesFilter<'WLBNotificationRecord'> | string | null
  wlbSubscriptionId?:
    | Prisma.StringNullableWithAggregatesFilter<'WLBNotificationRecord'>
    | string
    | null
  createdAt?: Prisma.DateTimeWithAggregatesFilter<'WLBNotificationRecord'> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<'WLBNotificationRecord'> | Date | string
}

export type WLBNotificationRecordCreateInput = {
  id?: string
  ok?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  dailyRecord?: Prisma.WLBDailyRecordCreateNestedOneWithoutWlbNotificationRecordsInput
  subscription?: Prisma.WLBSubscriptionCreateNestedOneWithoutWlbNotificationRecordsInput
}

export type WLBNotificationRecordUncheckedCreateInput = {
  id?: string
  ok?: boolean
  dailyRecordId?: string | null
  wlbSubscriptionId?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type WLBNotificationRecordUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  ok?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  dailyRecord?: Prisma.WLBDailyRecordUpdateOneWithoutWlbNotificationRecordsNestedInput
  subscription?: Prisma.WLBSubscriptionUpdateOneWithoutWlbNotificationRecordsNestedInput
}

export type WLBNotificationRecordUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  ok?: Prisma.BoolFieldUpdateOperationsInput | boolean
  dailyRecordId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  wlbSubscriptionId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type WLBNotificationRecordCreateManyInput = {
  id?: string
  ok?: boolean
  dailyRecordId?: string | null
  wlbSubscriptionId?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type WLBNotificationRecordUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  ok?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type WLBNotificationRecordUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  ok?: Prisma.BoolFieldUpdateOperationsInput | boolean
  dailyRecordId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  wlbSubscriptionId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type WLBNotificationRecordListRelationFilter = {
  every?: Prisma.WLBNotificationRecordWhereInput
  some?: Prisma.WLBNotificationRecordWhereInput
  none?: Prisma.WLBNotificationRecordWhereInput
}

export type WLBNotificationRecordOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type WLBNotificationRecordCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  ok?: Prisma.SortOrder
  dailyRecordId?: Prisma.SortOrder
  wlbSubscriptionId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type WLBNotificationRecordMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  ok?: Prisma.SortOrder
  dailyRecordId?: Prisma.SortOrder
  wlbSubscriptionId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type WLBNotificationRecordMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  ok?: Prisma.SortOrder
  dailyRecordId?: Prisma.SortOrder
  wlbSubscriptionId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type WLBNotificationRecordCreateNestedManyWithoutDailyRecordInput = {
  create?:
    | Prisma.XOR<
        Prisma.WLBNotificationRecordCreateWithoutDailyRecordInput,
        Prisma.WLBNotificationRecordUncheckedCreateWithoutDailyRecordInput
      >
    | Prisma.WLBNotificationRecordCreateWithoutDailyRecordInput[]
    | Prisma.WLBNotificationRecordUncheckedCreateWithoutDailyRecordInput[]
  connectOrCreate?:
    | Prisma.WLBNotificationRecordCreateOrConnectWithoutDailyRecordInput
    | Prisma.WLBNotificationRecordCreateOrConnectWithoutDailyRecordInput[]
  createMany?: Prisma.WLBNotificationRecordCreateManyDailyRecordInputEnvelope
  connect?:
    | Prisma.WLBNotificationRecordWhereUniqueInput
    | Prisma.WLBNotificationRecordWhereUniqueInput[]
}

export type WLBNotificationRecordUncheckedCreateNestedManyWithoutDailyRecordInput = {
  create?:
    | Prisma.XOR<
        Prisma.WLBNotificationRecordCreateWithoutDailyRecordInput,
        Prisma.WLBNotificationRecordUncheckedCreateWithoutDailyRecordInput
      >
    | Prisma.WLBNotificationRecordCreateWithoutDailyRecordInput[]
    | Prisma.WLBNotificationRecordUncheckedCreateWithoutDailyRecordInput[]
  connectOrCreate?:
    | Prisma.WLBNotificationRecordCreateOrConnectWithoutDailyRecordInput
    | Prisma.WLBNotificationRecordCreateOrConnectWithoutDailyRecordInput[]
  createMany?: Prisma.WLBNotificationRecordCreateManyDailyRecordInputEnvelope
  connect?:
    | Prisma.WLBNotificationRecordWhereUniqueInput
    | Prisma.WLBNotificationRecordWhereUniqueInput[]
}

export type WLBNotificationRecordUpdateManyWithoutDailyRecordNestedInput = {
  create?:
    | Prisma.XOR<
        Prisma.WLBNotificationRecordCreateWithoutDailyRecordInput,
        Prisma.WLBNotificationRecordUncheckedCreateWithoutDailyRecordInput
      >
    | Prisma.WLBNotificationRecordCreateWithoutDailyRecordInput[]
    | Prisma.WLBNotificationRecordUncheckedCreateWithoutDailyRecordInput[]
  connectOrCreate?:
    | Prisma.WLBNotificationRecordCreateOrConnectWithoutDailyRecordInput
    | Prisma.WLBNotificationRecordCreateOrConnectWithoutDailyRecordInput[]
  upsert?:
    | Prisma.WLBNotificationRecordUpsertWithWhereUniqueWithoutDailyRecordInput
    | Prisma.WLBNotificationRecordUpsertWithWhereUniqueWithoutDailyRecordInput[]
  createMany?: Prisma.WLBNotificationRecordCreateManyDailyRecordInputEnvelope
  set?:
    | Prisma.WLBNotificationRecordWhereUniqueInput
    | Prisma.WLBNotificationRecordWhereUniqueInput[]
  disconnect?:
    | Prisma.WLBNotificationRecordWhereUniqueInput
    | Prisma.WLBNotificationRecordWhereUniqueInput[]
  delete?:
    | Prisma.WLBNotificationRecordWhereUniqueInput
    | Prisma.WLBNotificationRecordWhereUniqueInput[]
  connect?:
    | Prisma.WLBNotificationRecordWhereUniqueInput
    | Prisma.WLBNotificationRecordWhereUniqueInput[]
  update?:
    | Prisma.WLBNotificationRecordUpdateWithWhereUniqueWithoutDailyRecordInput
    | Prisma.WLBNotificationRecordUpdateWithWhereUniqueWithoutDailyRecordInput[]
  updateMany?:
    | Prisma.WLBNotificationRecordUpdateManyWithWhereWithoutDailyRecordInput
    | Prisma.WLBNotificationRecordUpdateManyWithWhereWithoutDailyRecordInput[]
  deleteMany?:
    | Prisma.WLBNotificationRecordScalarWhereInput
    | Prisma.WLBNotificationRecordScalarWhereInput[]
}

export type WLBNotificationRecordUncheckedUpdateManyWithoutDailyRecordNestedInput = {
  create?:
    | Prisma.XOR<
        Prisma.WLBNotificationRecordCreateWithoutDailyRecordInput,
        Prisma.WLBNotificationRecordUncheckedCreateWithoutDailyRecordInput
      >
    | Prisma.WLBNotificationRecordCreateWithoutDailyRecordInput[]
    | Prisma.WLBNotificationRecordUncheckedCreateWithoutDailyRecordInput[]
  connectOrCreate?:
    | Prisma.WLBNotificationRecordCreateOrConnectWithoutDailyRecordInput
    | Prisma.WLBNotificationRecordCreateOrConnectWithoutDailyRecordInput[]
  upsert?:
    | Prisma.WLBNotificationRecordUpsertWithWhereUniqueWithoutDailyRecordInput
    | Prisma.WLBNotificationRecordUpsertWithWhereUniqueWithoutDailyRecordInput[]
  createMany?: Prisma.WLBNotificationRecordCreateManyDailyRecordInputEnvelope
  set?:
    | Prisma.WLBNotificationRecordWhereUniqueInput
    | Prisma.WLBNotificationRecordWhereUniqueInput[]
  disconnect?:
    | Prisma.WLBNotificationRecordWhereUniqueInput
    | Prisma.WLBNotificationRecordWhereUniqueInput[]
  delete?:
    | Prisma.WLBNotificationRecordWhereUniqueInput
    | Prisma.WLBNotificationRecordWhereUniqueInput[]
  connect?:
    | Prisma.WLBNotificationRecordWhereUniqueInput
    | Prisma.WLBNotificationRecordWhereUniqueInput[]
  update?:
    | Prisma.WLBNotificationRecordUpdateWithWhereUniqueWithoutDailyRecordInput
    | Prisma.WLBNotificationRecordUpdateWithWhereUniqueWithoutDailyRecordInput[]
  updateMany?:
    | Prisma.WLBNotificationRecordUpdateManyWithWhereWithoutDailyRecordInput
    | Prisma.WLBNotificationRecordUpdateManyWithWhereWithoutDailyRecordInput[]
  deleteMany?:
    | Prisma.WLBNotificationRecordScalarWhereInput
    | Prisma.WLBNotificationRecordScalarWhereInput[]
}

export type WLBNotificationRecordCreateNestedManyWithoutSubscriptionInput = {
  create?:
    | Prisma.XOR<
        Prisma.WLBNotificationRecordCreateWithoutSubscriptionInput,
        Prisma.WLBNotificationRecordUncheckedCreateWithoutSubscriptionInput
      >
    | Prisma.WLBNotificationRecordCreateWithoutSubscriptionInput[]
    | Prisma.WLBNotificationRecordUncheckedCreateWithoutSubscriptionInput[]
  connectOrCreate?:
    | Prisma.WLBNotificationRecordCreateOrConnectWithoutSubscriptionInput
    | Prisma.WLBNotificationRecordCreateOrConnectWithoutSubscriptionInput[]
  createMany?: Prisma.WLBNotificationRecordCreateManySubscriptionInputEnvelope
  connect?:
    | Prisma.WLBNotificationRecordWhereUniqueInput
    | Prisma.WLBNotificationRecordWhereUniqueInput[]
}

export type WLBNotificationRecordUncheckedCreateNestedManyWithoutSubscriptionInput = {
  create?:
    | Prisma.XOR<
        Prisma.WLBNotificationRecordCreateWithoutSubscriptionInput,
        Prisma.WLBNotificationRecordUncheckedCreateWithoutSubscriptionInput
      >
    | Prisma.WLBNotificationRecordCreateWithoutSubscriptionInput[]
    | Prisma.WLBNotificationRecordUncheckedCreateWithoutSubscriptionInput[]
  connectOrCreate?:
    | Prisma.WLBNotificationRecordCreateOrConnectWithoutSubscriptionInput
    | Prisma.WLBNotificationRecordCreateOrConnectWithoutSubscriptionInput[]
  createMany?: Prisma.WLBNotificationRecordCreateManySubscriptionInputEnvelope
  connect?:
    | Prisma.WLBNotificationRecordWhereUniqueInput
    | Prisma.WLBNotificationRecordWhereUniqueInput[]
}

export type WLBNotificationRecordUpdateManyWithoutSubscriptionNestedInput = {
  create?:
    | Prisma.XOR<
        Prisma.WLBNotificationRecordCreateWithoutSubscriptionInput,
        Prisma.WLBNotificationRecordUncheckedCreateWithoutSubscriptionInput
      >
    | Prisma.WLBNotificationRecordCreateWithoutSubscriptionInput[]
    | Prisma.WLBNotificationRecordUncheckedCreateWithoutSubscriptionInput[]
  connectOrCreate?:
    | Prisma.WLBNotificationRecordCreateOrConnectWithoutSubscriptionInput
    | Prisma.WLBNotificationRecordCreateOrConnectWithoutSubscriptionInput[]
  upsert?:
    | Prisma.WLBNotificationRecordUpsertWithWhereUniqueWithoutSubscriptionInput
    | Prisma.WLBNotificationRecordUpsertWithWhereUniqueWithoutSubscriptionInput[]
  createMany?: Prisma.WLBNotificationRecordCreateManySubscriptionInputEnvelope
  set?:
    | Prisma.WLBNotificationRecordWhereUniqueInput
    | Prisma.WLBNotificationRecordWhereUniqueInput[]
  disconnect?:
    | Prisma.WLBNotificationRecordWhereUniqueInput
    | Prisma.WLBNotificationRecordWhereUniqueInput[]
  delete?:
    | Prisma.WLBNotificationRecordWhereUniqueInput
    | Prisma.WLBNotificationRecordWhereUniqueInput[]
  connect?:
    | Prisma.WLBNotificationRecordWhereUniqueInput
    | Prisma.WLBNotificationRecordWhereUniqueInput[]
  update?:
    | Prisma.WLBNotificationRecordUpdateWithWhereUniqueWithoutSubscriptionInput
    | Prisma.WLBNotificationRecordUpdateWithWhereUniqueWithoutSubscriptionInput[]
  updateMany?:
    | Prisma.WLBNotificationRecordUpdateManyWithWhereWithoutSubscriptionInput
    | Prisma.WLBNotificationRecordUpdateManyWithWhereWithoutSubscriptionInput[]
  deleteMany?:
    | Prisma.WLBNotificationRecordScalarWhereInput
    | Prisma.WLBNotificationRecordScalarWhereInput[]
}

export type WLBNotificationRecordUncheckedUpdateManyWithoutSubscriptionNestedInput = {
  create?:
    | Prisma.XOR<
        Prisma.WLBNotificationRecordCreateWithoutSubscriptionInput,
        Prisma.WLBNotificationRecordUncheckedCreateWithoutSubscriptionInput
      >
    | Prisma.WLBNotificationRecordCreateWithoutSubscriptionInput[]
    | Prisma.WLBNotificationRecordUncheckedCreateWithoutSubscriptionInput[]
  connectOrCreate?:
    | Prisma.WLBNotificationRecordCreateOrConnectWithoutSubscriptionInput
    | Prisma.WLBNotificationRecordCreateOrConnectWithoutSubscriptionInput[]
  upsert?:
    | Prisma.WLBNotificationRecordUpsertWithWhereUniqueWithoutSubscriptionInput
    | Prisma.WLBNotificationRecordUpsertWithWhereUniqueWithoutSubscriptionInput[]
  createMany?: Prisma.WLBNotificationRecordCreateManySubscriptionInputEnvelope
  set?:
    | Prisma.WLBNotificationRecordWhereUniqueInput
    | Prisma.WLBNotificationRecordWhereUniqueInput[]
  disconnect?:
    | Prisma.WLBNotificationRecordWhereUniqueInput
    | Prisma.WLBNotificationRecordWhereUniqueInput[]
  delete?:
    | Prisma.WLBNotificationRecordWhereUniqueInput
    | Prisma.WLBNotificationRecordWhereUniqueInput[]
  connect?:
    | Prisma.WLBNotificationRecordWhereUniqueInput
    | Prisma.WLBNotificationRecordWhereUniqueInput[]
  update?:
    | Prisma.WLBNotificationRecordUpdateWithWhereUniqueWithoutSubscriptionInput
    | Prisma.WLBNotificationRecordUpdateWithWhereUniqueWithoutSubscriptionInput[]
  updateMany?:
    | Prisma.WLBNotificationRecordUpdateManyWithWhereWithoutSubscriptionInput
    | Prisma.WLBNotificationRecordUpdateManyWithWhereWithoutSubscriptionInput[]
  deleteMany?:
    | Prisma.WLBNotificationRecordScalarWhereInput
    | Prisma.WLBNotificationRecordScalarWhereInput[]
}

export type WLBNotificationRecordCreateWithoutDailyRecordInput = {
  id?: string
  ok?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  subscription?: Prisma.WLBSubscriptionCreateNestedOneWithoutWlbNotificationRecordsInput
}

export type WLBNotificationRecordUncheckedCreateWithoutDailyRecordInput = {
  id?: string
  ok?: boolean
  wlbSubscriptionId?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type WLBNotificationRecordCreateOrConnectWithoutDailyRecordInput = {
  where: Prisma.WLBNotificationRecordWhereUniqueInput
  create: Prisma.XOR<
    Prisma.WLBNotificationRecordCreateWithoutDailyRecordInput,
    Prisma.WLBNotificationRecordUncheckedCreateWithoutDailyRecordInput
  >
}

export type WLBNotificationRecordCreateManyDailyRecordInputEnvelope = {
  data:
    | Prisma.WLBNotificationRecordCreateManyDailyRecordInput
    | Prisma.WLBNotificationRecordCreateManyDailyRecordInput[]
  skipDuplicates?: boolean
}

export type WLBNotificationRecordUpsertWithWhereUniqueWithoutDailyRecordInput = {
  where: Prisma.WLBNotificationRecordWhereUniqueInput
  update: Prisma.XOR<
    Prisma.WLBNotificationRecordUpdateWithoutDailyRecordInput,
    Prisma.WLBNotificationRecordUncheckedUpdateWithoutDailyRecordInput
  >
  create: Prisma.XOR<
    Prisma.WLBNotificationRecordCreateWithoutDailyRecordInput,
    Prisma.WLBNotificationRecordUncheckedCreateWithoutDailyRecordInput
  >
}

export type WLBNotificationRecordUpdateWithWhereUniqueWithoutDailyRecordInput = {
  where: Prisma.WLBNotificationRecordWhereUniqueInput
  data: Prisma.XOR<
    Prisma.WLBNotificationRecordUpdateWithoutDailyRecordInput,
    Prisma.WLBNotificationRecordUncheckedUpdateWithoutDailyRecordInput
  >
}

export type WLBNotificationRecordUpdateManyWithWhereWithoutDailyRecordInput = {
  where: Prisma.WLBNotificationRecordScalarWhereInput
  data: Prisma.XOR<
    Prisma.WLBNotificationRecordUpdateManyMutationInput,
    Prisma.WLBNotificationRecordUncheckedUpdateManyWithoutDailyRecordInput
  >
}

export type WLBNotificationRecordScalarWhereInput = {
  AND?:
    | Prisma.WLBNotificationRecordScalarWhereInput
    | Prisma.WLBNotificationRecordScalarWhereInput[]
  OR?: Prisma.WLBNotificationRecordScalarWhereInput[]
  NOT?:
    | Prisma.WLBNotificationRecordScalarWhereInput
    | Prisma.WLBNotificationRecordScalarWhereInput[]
  id?: Prisma.StringFilter<'WLBNotificationRecord'> | string
  ok?: Prisma.BoolFilter<'WLBNotificationRecord'> | boolean
  dailyRecordId?: Prisma.StringNullableFilter<'WLBNotificationRecord'> | string | null
  wlbSubscriptionId?: Prisma.StringNullableFilter<'WLBNotificationRecord'> | string | null
  createdAt?: Prisma.DateTimeFilter<'WLBNotificationRecord'> | Date | string
  updatedAt?: Prisma.DateTimeFilter<'WLBNotificationRecord'> | Date | string
}

export type WLBNotificationRecordCreateWithoutSubscriptionInput = {
  id?: string
  ok?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  dailyRecord?: Prisma.WLBDailyRecordCreateNestedOneWithoutWlbNotificationRecordsInput
}

export type WLBNotificationRecordUncheckedCreateWithoutSubscriptionInput = {
  id?: string
  ok?: boolean
  dailyRecordId?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type WLBNotificationRecordCreateOrConnectWithoutSubscriptionInput = {
  where: Prisma.WLBNotificationRecordWhereUniqueInput
  create: Prisma.XOR<
    Prisma.WLBNotificationRecordCreateWithoutSubscriptionInput,
    Prisma.WLBNotificationRecordUncheckedCreateWithoutSubscriptionInput
  >
}

export type WLBNotificationRecordCreateManySubscriptionInputEnvelope = {
  data:
    | Prisma.WLBNotificationRecordCreateManySubscriptionInput
    | Prisma.WLBNotificationRecordCreateManySubscriptionInput[]
  skipDuplicates?: boolean
}

export type WLBNotificationRecordUpsertWithWhereUniqueWithoutSubscriptionInput = {
  where: Prisma.WLBNotificationRecordWhereUniqueInput
  update: Prisma.XOR<
    Prisma.WLBNotificationRecordUpdateWithoutSubscriptionInput,
    Prisma.WLBNotificationRecordUncheckedUpdateWithoutSubscriptionInput
  >
  create: Prisma.XOR<
    Prisma.WLBNotificationRecordCreateWithoutSubscriptionInput,
    Prisma.WLBNotificationRecordUncheckedCreateWithoutSubscriptionInput
  >
}

export type WLBNotificationRecordUpdateWithWhereUniqueWithoutSubscriptionInput = {
  where: Prisma.WLBNotificationRecordWhereUniqueInput
  data: Prisma.XOR<
    Prisma.WLBNotificationRecordUpdateWithoutSubscriptionInput,
    Prisma.WLBNotificationRecordUncheckedUpdateWithoutSubscriptionInput
  >
}

export type WLBNotificationRecordUpdateManyWithWhereWithoutSubscriptionInput = {
  where: Prisma.WLBNotificationRecordScalarWhereInput
  data: Prisma.XOR<
    Prisma.WLBNotificationRecordUpdateManyMutationInput,
    Prisma.WLBNotificationRecordUncheckedUpdateManyWithoutSubscriptionInput
  >
}

export type WLBNotificationRecordCreateManyDailyRecordInput = {
  id?: string
  ok?: boolean
  wlbSubscriptionId?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type WLBNotificationRecordUpdateWithoutDailyRecordInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  ok?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  subscription?: Prisma.WLBSubscriptionUpdateOneWithoutWlbNotificationRecordsNestedInput
}

export type WLBNotificationRecordUncheckedUpdateWithoutDailyRecordInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  ok?: Prisma.BoolFieldUpdateOperationsInput | boolean
  wlbSubscriptionId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type WLBNotificationRecordUncheckedUpdateManyWithoutDailyRecordInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  ok?: Prisma.BoolFieldUpdateOperationsInput | boolean
  wlbSubscriptionId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type WLBNotificationRecordCreateManySubscriptionInput = {
  id?: string
  ok?: boolean
  dailyRecordId?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type WLBNotificationRecordUpdateWithoutSubscriptionInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  ok?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  dailyRecord?: Prisma.WLBDailyRecordUpdateOneWithoutWlbNotificationRecordsNestedInput
}

export type WLBNotificationRecordUncheckedUpdateWithoutSubscriptionInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  ok?: Prisma.BoolFieldUpdateOperationsInput | boolean
  dailyRecordId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type WLBNotificationRecordUncheckedUpdateManyWithoutSubscriptionInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  ok?: Prisma.BoolFieldUpdateOperationsInput | boolean
  dailyRecordId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type WLBNotificationRecordSelect<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = runtime.Types.Extensions.GetSelect<
  {
    id?: boolean
    ok?: boolean
    dailyRecordId?: boolean
    wlbSubscriptionId?: boolean
    createdAt?: boolean
    updatedAt?: boolean
    dailyRecord?: boolean | Prisma.WLBNotificationRecord$dailyRecordArgs<ExtArgs>
    subscription?: boolean | Prisma.WLBNotificationRecord$subscriptionArgs<ExtArgs>
  },
  ExtArgs['result']['wLBNotificationRecord']
>

export type WLBNotificationRecordSelectCreateManyAndReturn<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = runtime.Types.Extensions.GetSelect<
  {
    id?: boolean
    ok?: boolean
    dailyRecordId?: boolean
    wlbSubscriptionId?: boolean
    createdAt?: boolean
    updatedAt?: boolean
    dailyRecord?: boolean | Prisma.WLBNotificationRecord$dailyRecordArgs<ExtArgs>
    subscription?: boolean | Prisma.WLBNotificationRecord$subscriptionArgs<ExtArgs>
  },
  ExtArgs['result']['wLBNotificationRecord']
>

export type WLBNotificationRecordSelectUpdateManyAndReturn<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = runtime.Types.Extensions.GetSelect<
  {
    id?: boolean
    ok?: boolean
    dailyRecordId?: boolean
    wlbSubscriptionId?: boolean
    createdAt?: boolean
    updatedAt?: boolean
    dailyRecord?: boolean | Prisma.WLBNotificationRecord$dailyRecordArgs<ExtArgs>
    subscription?: boolean | Prisma.WLBNotificationRecord$subscriptionArgs<ExtArgs>
  },
  ExtArgs['result']['wLBNotificationRecord']
>

export type WLBNotificationRecordSelectScalar = {
  id?: boolean
  ok?: boolean
  dailyRecordId?: boolean
  wlbSubscriptionId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type WLBNotificationRecordOmit<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = runtime.Types.Extensions.GetOmit<
  'id' | 'ok' | 'dailyRecordId' | 'wlbSubscriptionId' | 'createdAt' | 'updatedAt',
  ExtArgs['result']['wLBNotificationRecord']
>
export type WLBNotificationRecordInclude<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  dailyRecord?: boolean | Prisma.WLBNotificationRecord$dailyRecordArgs<ExtArgs>
  subscription?: boolean | Prisma.WLBNotificationRecord$subscriptionArgs<ExtArgs>
}
export type WLBNotificationRecordIncludeCreateManyAndReturn<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  dailyRecord?: boolean | Prisma.WLBNotificationRecord$dailyRecordArgs<ExtArgs>
  subscription?: boolean | Prisma.WLBNotificationRecord$subscriptionArgs<ExtArgs>
}
export type WLBNotificationRecordIncludeUpdateManyAndReturn<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  dailyRecord?: boolean | Prisma.WLBNotificationRecord$dailyRecordArgs<ExtArgs>
  subscription?: boolean | Prisma.WLBNotificationRecord$subscriptionArgs<ExtArgs>
}

export type $WLBNotificationRecordPayload<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  name: 'WLBNotificationRecord'
  objects: {
    dailyRecord: Prisma.$WLBDailyRecordPayload<ExtArgs> | null
    subscription: Prisma.$WLBSubscriptionPayload<ExtArgs> | null
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<
    {
      id: string
      ok: boolean
      dailyRecordId: string | null
      wlbSubscriptionId: string | null
      createdAt: Date
      updatedAt: Date
    },
    ExtArgs['result']['wLBNotificationRecord']
  >
  composites: {}
}

export type WLBNotificationRecordGetPayload<
  S extends boolean | null | undefined | WLBNotificationRecordDefaultArgs,
> = runtime.Types.Result.GetResult<Prisma.$WLBNotificationRecordPayload, S>

export type WLBNotificationRecordCountArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = Omit<WLBNotificationRecordFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
  select?: WLBNotificationRecordCountAggregateInputType | true
}

export interface WLBNotificationRecordDelegate<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
  GlobalOmitOptions = {},
> {
  [K: symbol]: {
    types: Prisma.TypeMap<ExtArgs>['model']['WLBNotificationRecord']
    meta: { name: 'WLBNotificationRecord' }
  }
  /**
   * Find zero or one WLBNotificationRecord that matches the filter.
   * @param {WLBNotificationRecordFindUniqueArgs} args - Arguments to find a WLBNotificationRecord
   * @example
   * // Get one WLBNotificationRecord
   * const wLBNotificationRecord = await prisma.wLBNotificationRecord.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends WLBNotificationRecordFindUniqueArgs>(
    args: Prisma.SelectSubset<T, WLBNotificationRecordFindUniqueArgs<ExtArgs>>
  ): Prisma.Prisma__WLBNotificationRecordClient<
    runtime.Types.Result.GetResult<
      Prisma.$WLBNotificationRecordPayload<ExtArgs>,
      T,
      'findUnique',
      GlobalOmitOptions
    > | null,
    null,
    ExtArgs,
    GlobalOmitOptions
  >

  /**
   * Find one WLBNotificationRecord that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {WLBNotificationRecordFindUniqueOrThrowArgs} args - Arguments to find a WLBNotificationRecord
   * @example
   * // Get one WLBNotificationRecord
   * const wLBNotificationRecord = await prisma.wLBNotificationRecord.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends WLBNotificationRecordFindUniqueOrThrowArgs>(
    args: Prisma.SelectSubset<T, WLBNotificationRecordFindUniqueOrThrowArgs<ExtArgs>>
  ): Prisma.Prisma__WLBNotificationRecordClient<
    runtime.Types.Result.GetResult<
      Prisma.$WLBNotificationRecordPayload<ExtArgs>,
      T,
      'findUniqueOrThrow',
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >

  /**
   * Find the first WLBNotificationRecord that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {WLBNotificationRecordFindFirstArgs} args - Arguments to find a WLBNotificationRecord
   * @example
   * // Get one WLBNotificationRecord
   * const wLBNotificationRecord = await prisma.wLBNotificationRecord.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends WLBNotificationRecordFindFirstArgs>(
    args?: Prisma.SelectSubset<T, WLBNotificationRecordFindFirstArgs<ExtArgs>>
  ): Prisma.Prisma__WLBNotificationRecordClient<
    runtime.Types.Result.GetResult<
      Prisma.$WLBNotificationRecordPayload<ExtArgs>,
      T,
      'findFirst',
      GlobalOmitOptions
    > | null,
    null,
    ExtArgs,
    GlobalOmitOptions
  >

  /**
   * Find the first WLBNotificationRecord that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {WLBNotificationRecordFindFirstOrThrowArgs} args - Arguments to find a WLBNotificationRecord
   * @example
   * // Get one WLBNotificationRecord
   * const wLBNotificationRecord = await prisma.wLBNotificationRecord.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends WLBNotificationRecordFindFirstOrThrowArgs>(
    args?: Prisma.SelectSubset<T, WLBNotificationRecordFindFirstOrThrowArgs<ExtArgs>>
  ): Prisma.Prisma__WLBNotificationRecordClient<
    runtime.Types.Result.GetResult<
      Prisma.$WLBNotificationRecordPayload<ExtArgs>,
      T,
      'findFirstOrThrow',
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >

  /**
   * Find zero or more WLBNotificationRecords that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {WLBNotificationRecordFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all WLBNotificationRecords
   * const wLBNotificationRecords = await prisma.wLBNotificationRecord.findMany()
   *
   * // Get first 10 WLBNotificationRecords
   * const wLBNotificationRecords = await prisma.wLBNotificationRecord.findMany({ take: 10 })
   *
   * // Only select the `id`
   * const wLBNotificationRecordWithIdOnly = await prisma.wLBNotificationRecord.findMany({ select: { id: true } })
   *
   */
  findMany<T extends WLBNotificationRecordFindManyArgs>(
    args?: Prisma.SelectSubset<T, WLBNotificationRecordFindManyArgs<ExtArgs>>
  ): Prisma.PrismaPromise<
    runtime.Types.Result.GetResult<
      Prisma.$WLBNotificationRecordPayload<ExtArgs>,
      T,
      'findMany',
      GlobalOmitOptions
    >
  >

  /**
   * Create a WLBNotificationRecord.
   * @param {WLBNotificationRecordCreateArgs} args - Arguments to create a WLBNotificationRecord.
   * @example
   * // Create one WLBNotificationRecord
   * const WLBNotificationRecord = await prisma.wLBNotificationRecord.create({
   *   data: {
   *     // ... data to create a WLBNotificationRecord
   *   }
   * })
   *
   */
  create<T extends WLBNotificationRecordCreateArgs>(
    args: Prisma.SelectSubset<T, WLBNotificationRecordCreateArgs<ExtArgs>>
  ): Prisma.Prisma__WLBNotificationRecordClient<
    runtime.Types.Result.GetResult<
      Prisma.$WLBNotificationRecordPayload<ExtArgs>,
      T,
      'create',
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >

  /**
   * Create many WLBNotificationRecords.
   * @param {WLBNotificationRecordCreateManyArgs} args - Arguments to create many WLBNotificationRecords.
   * @example
   * // Create many WLBNotificationRecords
   * const wLBNotificationRecord = await prisma.wLBNotificationRecord.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *
   */
  createMany<T extends WLBNotificationRecordCreateManyArgs>(
    args?: Prisma.SelectSubset<T, WLBNotificationRecordCreateManyArgs<ExtArgs>>
  ): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many WLBNotificationRecords and returns the data saved in the database.
   * @param {WLBNotificationRecordCreateManyAndReturnArgs} args - Arguments to create many WLBNotificationRecords.
   * @example
   * // Create many WLBNotificationRecords
   * const wLBNotificationRecord = await prisma.wLBNotificationRecord.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *
   * // Create many WLBNotificationRecords and only return the `id`
   * const wLBNotificationRecordWithIdOnly = await prisma.wLBNotificationRecord.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   *
   */
  createManyAndReturn<T extends WLBNotificationRecordCreateManyAndReturnArgs>(
    args?: Prisma.SelectSubset<T, WLBNotificationRecordCreateManyAndReturnArgs<ExtArgs>>
  ): Prisma.PrismaPromise<
    runtime.Types.Result.GetResult<
      Prisma.$WLBNotificationRecordPayload<ExtArgs>,
      T,
      'createManyAndReturn',
      GlobalOmitOptions
    >
  >

  /**
   * Delete a WLBNotificationRecord.
   * @param {WLBNotificationRecordDeleteArgs} args - Arguments to delete one WLBNotificationRecord.
   * @example
   * // Delete one WLBNotificationRecord
   * const WLBNotificationRecord = await prisma.wLBNotificationRecord.delete({
   *   where: {
   *     // ... filter to delete one WLBNotificationRecord
   *   }
   * })
   *
   */
  delete<T extends WLBNotificationRecordDeleteArgs>(
    args: Prisma.SelectSubset<T, WLBNotificationRecordDeleteArgs<ExtArgs>>
  ): Prisma.Prisma__WLBNotificationRecordClient<
    runtime.Types.Result.GetResult<
      Prisma.$WLBNotificationRecordPayload<ExtArgs>,
      T,
      'delete',
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >

  /**
   * Update one WLBNotificationRecord.
   * @param {WLBNotificationRecordUpdateArgs} args - Arguments to update one WLBNotificationRecord.
   * @example
   * // Update one WLBNotificationRecord
   * const wLBNotificationRecord = await prisma.wLBNotificationRecord.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   *
   */
  update<T extends WLBNotificationRecordUpdateArgs>(
    args: Prisma.SelectSubset<T, WLBNotificationRecordUpdateArgs<ExtArgs>>
  ): Prisma.Prisma__WLBNotificationRecordClient<
    runtime.Types.Result.GetResult<
      Prisma.$WLBNotificationRecordPayload<ExtArgs>,
      T,
      'update',
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >

  /**
   * Delete zero or more WLBNotificationRecords.
   * @param {WLBNotificationRecordDeleteManyArgs} args - Arguments to filter WLBNotificationRecords to delete.
   * @example
   * // Delete a few WLBNotificationRecords
   * const { count } = await prisma.wLBNotificationRecord.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   *
   */
  deleteMany<T extends WLBNotificationRecordDeleteManyArgs>(
    args?: Prisma.SelectSubset<T, WLBNotificationRecordDeleteManyArgs<ExtArgs>>
  ): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more WLBNotificationRecords.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {WLBNotificationRecordUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many WLBNotificationRecords
   * const wLBNotificationRecord = await prisma.wLBNotificationRecord.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   *
   */
  updateMany<T extends WLBNotificationRecordUpdateManyArgs>(
    args: Prisma.SelectSubset<T, WLBNotificationRecordUpdateManyArgs<ExtArgs>>
  ): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more WLBNotificationRecords and returns the data updated in the database.
   * @param {WLBNotificationRecordUpdateManyAndReturnArgs} args - Arguments to update many WLBNotificationRecords.
   * @example
   * // Update many WLBNotificationRecords
   * const wLBNotificationRecord = await prisma.wLBNotificationRecord.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *
   * // Update zero or more WLBNotificationRecords and only return the `id`
   * const wLBNotificationRecordWithIdOnly = await prisma.wLBNotificationRecord.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   *
   */
  updateManyAndReturn<T extends WLBNotificationRecordUpdateManyAndReturnArgs>(
    args: Prisma.SelectSubset<T, WLBNotificationRecordUpdateManyAndReturnArgs<ExtArgs>>
  ): Prisma.PrismaPromise<
    runtime.Types.Result.GetResult<
      Prisma.$WLBNotificationRecordPayload<ExtArgs>,
      T,
      'updateManyAndReturn',
      GlobalOmitOptions
    >
  >

  /**
   * Create or update one WLBNotificationRecord.
   * @param {WLBNotificationRecordUpsertArgs} args - Arguments to update or create a WLBNotificationRecord.
   * @example
   * // Update or create a WLBNotificationRecord
   * const wLBNotificationRecord = await prisma.wLBNotificationRecord.upsert({
   *   create: {
   *     // ... data to create a WLBNotificationRecord
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the WLBNotificationRecord we want to update
   *   }
   * })
   */
  upsert<T extends WLBNotificationRecordUpsertArgs>(
    args: Prisma.SelectSubset<T, WLBNotificationRecordUpsertArgs<ExtArgs>>
  ): Prisma.Prisma__WLBNotificationRecordClient<
    runtime.Types.Result.GetResult<
      Prisma.$WLBNotificationRecordPayload<ExtArgs>,
      T,
      'upsert',
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >

  /**
   * Count the number of WLBNotificationRecords.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {WLBNotificationRecordCountArgs} args - Arguments to filter WLBNotificationRecords to count.
   * @example
   * // Count the number of WLBNotificationRecords
   * const count = await prisma.wLBNotificationRecord.count({
   *   where: {
   *     // ... the filter for the WLBNotificationRecords we want to count
   *   }
   * })
   **/
  count<T extends WLBNotificationRecordCountArgs>(
    args?: Prisma.Subset<T, WLBNotificationRecordCountArgs>
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], WLBNotificationRecordCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a WLBNotificationRecord.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {WLBNotificationRecordAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
   **/
  aggregate<T extends WLBNotificationRecordAggregateArgs>(
    args: Prisma.Subset<T, WLBNotificationRecordAggregateArgs>
  ): Prisma.PrismaPromise<GetWLBNotificationRecordAggregateType<T>>

  /**
   * Group by WLBNotificationRecord.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {WLBNotificationRecordGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   *
   **/
  groupBy<
    T extends WLBNotificationRecordGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: WLBNotificationRecordGroupByArgs['orderBy'] }
      : { orderBy?: WLBNotificationRecordGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<
      Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>
    >,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
      ? `Error: "by" must not be empty.`
      : HavingValid extends Prisma.False
        ? {
            [P in HavingFields]: P extends ByFields
              ? never
              : P extends string
                ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
                : [Error, 'Field ', P, ` in "having" needs to be provided in "by"`]
          }[HavingFields]
        : 'take' extends Prisma.Keys<T>
          ? 'orderBy' extends Prisma.Keys<T>
            ? ByValid extends Prisma.True
              ? {}
              : {
                  [P in OrderFields]: P extends ByFields
                    ? never
                    : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
                }[OrderFields]
            : 'Error: If you provide "take", you also need to provide "orderBy"'
          : 'skip' extends Prisma.Keys<T>
            ? 'orderBy' extends Prisma.Keys<T>
              ? ByValid extends Prisma.True
                ? {}
                : {
                    [P in OrderFields]: P extends ByFields
                      ? never
                      : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
                  }[OrderFields]
              : 'Error: If you provide "skip", you also need to provide "orderBy"'
            : ByValid extends Prisma.True
              ? {}
              : {
                  [P in OrderFields]: P extends ByFields
                    ? never
                    : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
                }[OrderFields],
  >(
    args: Prisma.SubsetIntersection<T, WLBNotificationRecordGroupByArgs, OrderByArg> & InputErrors
  ): {} extends InputErrors
    ? GetWLBNotificationRecordGroupByPayload<T>
    : Prisma.PrismaPromise<InputErrors>
  /**
   * Fields of the WLBNotificationRecord model
   */
  readonly fields: WLBNotificationRecordFieldRefs
}

/**
 * The delegate class that acts as a "Promise-like" for WLBNotificationRecord.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__WLBNotificationRecordClient<
  T,
  Null = never,
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
  GlobalOmitOptions = {},
> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: 'PrismaPromise'
  dailyRecord<T extends Prisma.WLBNotificationRecord$dailyRecordArgs<ExtArgs> = {}>(
    args?: Prisma.Subset<T, Prisma.WLBNotificationRecord$dailyRecordArgs<ExtArgs>>
  ): Prisma.Prisma__WLBDailyRecordClient<
    runtime.Types.Result.GetResult<
      Prisma.$WLBDailyRecordPayload<ExtArgs>,
      T,
      'findUniqueOrThrow',
      GlobalOmitOptions
    > | null,
    null,
    ExtArgs,
    GlobalOmitOptions
  >
  subscription<T extends Prisma.WLBNotificationRecord$subscriptionArgs<ExtArgs> = {}>(
    args?: Prisma.Subset<T, Prisma.WLBNotificationRecord$subscriptionArgs<ExtArgs>>
  ): Prisma.Prisma__WLBSubscriptionClient<
    runtime.Types.Result.GetResult<
      Prisma.$WLBSubscriptionPayload<ExtArgs>,
      T,
      'findUniqueOrThrow',
      GlobalOmitOptions
    > | null,
    null,
    ExtArgs,
    GlobalOmitOptions
  >
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(
    onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null,
    onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null
  ): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(
    onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null
  ): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}

/**
 * Fields of the WLBNotificationRecord model
 */
export interface WLBNotificationRecordFieldRefs {
  readonly id: Prisma.FieldRef<'WLBNotificationRecord', 'String'>
  readonly ok: Prisma.FieldRef<'WLBNotificationRecord', 'Boolean'>
  readonly dailyRecordId: Prisma.FieldRef<'WLBNotificationRecord', 'String'>
  readonly wlbSubscriptionId: Prisma.FieldRef<'WLBNotificationRecord', 'String'>
  readonly createdAt: Prisma.FieldRef<'WLBNotificationRecord', 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<'WLBNotificationRecord', 'DateTime'>
}

// Custom InputTypes
/**
 * WLBNotificationRecord findUnique
 */
export type WLBNotificationRecordFindUniqueArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the WLBNotificationRecord
   */
  select?: Prisma.WLBNotificationRecordSelect<ExtArgs> | null
  /**
   * Omit specific fields from the WLBNotificationRecord
   */
  omit?: Prisma.WLBNotificationRecordOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WLBNotificationRecordInclude<ExtArgs> | null
  /**
   * Filter, which WLBNotificationRecord to fetch.
   */
  where: Prisma.WLBNotificationRecordWhereUniqueInput
}

/**
 * WLBNotificationRecord findUniqueOrThrow
 */
export type WLBNotificationRecordFindUniqueOrThrowArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the WLBNotificationRecord
   */
  select?: Prisma.WLBNotificationRecordSelect<ExtArgs> | null
  /**
   * Omit specific fields from the WLBNotificationRecord
   */
  omit?: Prisma.WLBNotificationRecordOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WLBNotificationRecordInclude<ExtArgs> | null
  /**
   * Filter, which WLBNotificationRecord to fetch.
   */
  where: Prisma.WLBNotificationRecordWhereUniqueInput
}

/**
 * WLBNotificationRecord findFirst
 */
export type WLBNotificationRecordFindFirstArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the WLBNotificationRecord
   */
  select?: Prisma.WLBNotificationRecordSelect<ExtArgs> | null
  /**
   * Omit specific fields from the WLBNotificationRecord
   */
  omit?: Prisma.WLBNotificationRecordOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WLBNotificationRecordInclude<ExtArgs> | null
  /**
   * Filter, which WLBNotificationRecord to fetch.
   */
  where?: Prisma.WLBNotificationRecordWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   *
   * Determine the order of WLBNotificationRecords to fetch.
   */
  orderBy?:
    | Prisma.WLBNotificationRecordOrderByWithRelationInput
    | Prisma.WLBNotificationRecordOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   *
   * Sets the position for searching for WLBNotificationRecords.
   */
  cursor?: Prisma.WLBNotificationRecordWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Take `±n` WLBNotificationRecords from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Skip the first `n` WLBNotificationRecords.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   *
   * Filter by unique combinations of WLBNotificationRecords.
   */
  distinct?:
    | Prisma.WLBNotificationRecordScalarFieldEnum
    | Prisma.WLBNotificationRecordScalarFieldEnum[]
}

/**
 * WLBNotificationRecord findFirstOrThrow
 */
export type WLBNotificationRecordFindFirstOrThrowArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the WLBNotificationRecord
   */
  select?: Prisma.WLBNotificationRecordSelect<ExtArgs> | null
  /**
   * Omit specific fields from the WLBNotificationRecord
   */
  omit?: Prisma.WLBNotificationRecordOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WLBNotificationRecordInclude<ExtArgs> | null
  /**
   * Filter, which WLBNotificationRecord to fetch.
   */
  where?: Prisma.WLBNotificationRecordWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   *
   * Determine the order of WLBNotificationRecords to fetch.
   */
  orderBy?:
    | Prisma.WLBNotificationRecordOrderByWithRelationInput
    | Prisma.WLBNotificationRecordOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   *
   * Sets the position for searching for WLBNotificationRecords.
   */
  cursor?: Prisma.WLBNotificationRecordWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Take `±n` WLBNotificationRecords from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Skip the first `n` WLBNotificationRecords.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   *
   * Filter by unique combinations of WLBNotificationRecords.
   */
  distinct?:
    | Prisma.WLBNotificationRecordScalarFieldEnum
    | Prisma.WLBNotificationRecordScalarFieldEnum[]
}

/**
 * WLBNotificationRecord findMany
 */
export type WLBNotificationRecordFindManyArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the WLBNotificationRecord
   */
  select?: Prisma.WLBNotificationRecordSelect<ExtArgs> | null
  /**
   * Omit specific fields from the WLBNotificationRecord
   */
  omit?: Prisma.WLBNotificationRecordOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WLBNotificationRecordInclude<ExtArgs> | null
  /**
   * Filter, which WLBNotificationRecords to fetch.
   */
  where?: Prisma.WLBNotificationRecordWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   *
   * Determine the order of WLBNotificationRecords to fetch.
   */
  orderBy?:
    | Prisma.WLBNotificationRecordOrderByWithRelationInput
    | Prisma.WLBNotificationRecordOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   *
   * Sets the position for listing WLBNotificationRecords.
   */
  cursor?: Prisma.WLBNotificationRecordWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Take `±n` WLBNotificationRecords from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Skip the first `n` WLBNotificationRecords.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   *
   * Filter by unique combinations of WLBNotificationRecords.
   */
  distinct?:
    | Prisma.WLBNotificationRecordScalarFieldEnum
    | Prisma.WLBNotificationRecordScalarFieldEnum[]
}

/**
 * WLBNotificationRecord create
 */
export type WLBNotificationRecordCreateArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the WLBNotificationRecord
   */
  select?: Prisma.WLBNotificationRecordSelect<ExtArgs> | null
  /**
   * Omit specific fields from the WLBNotificationRecord
   */
  omit?: Prisma.WLBNotificationRecordOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WLBNotificationRecordInclude<ExtArgs> | null
  /**
   * The data needed to create a WLBNotificationRecord.
   */
  data: Prisma.XOR<
    Prisma.WLBNotificationRecordCreateInput,
    Prisma.WLBNotificationRecordUncheckedCreateInput
  >
}

/**
 * WLBNotificationRecord createMany
 */
export type WLBNotificationRecordCreateManyArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * The data used to create many WLBNotificationRecords.
   */
  data: Prisma.WLBNotificationRecordCreateManyInput | Prisma.WLBNotificationRecordCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * WLBNotificationRecord createManyAndReturn
 */
export type WLBNotificationRecordCreateManyAndReturnArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the WLBNotificationRecord
   */
  select?: Prisma.WLBNotificationRecordSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the WLBNotificationRecord
   */
  omit?: Prisma.WLBNotificationRecordOmit<ExtArgs> | null
  /**
   * The data used to create many WLBNotificationRecords.
   */
  data: Prisma.WLBNotificationRecordCreateManyInput | Prisma.WLBNotificationRecordCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WLBNotificationRecordIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * WLBNotificationRecord update
 */
export type WLBNotificationRecordUpdateArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the WLBNotificationRecord
   */
  select?: Prisma.WLBNotificationRecordSelect<ExtArgs> | null
  /**
   * Omit specific fields from the WLBNotificationRecord
   */
  omit?: Prisma.WLBNotificationRecordOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WLBNotificationRecordInclude<ExtArgs> | null
  /**
   * The data needed to update a WLBNotificationRecord.
   */
  data: Prisma.XOR<
    Prisma.WLBNotificationRecordUpdateInput,
    Prisma.WLBNotificationRecordUncheckedUpdateInput
  >
  /**
   * Choose, which WLBNotificationRecord to update.
   */
  where: Prisma.WLBNotificationRecordWhereUniqueInput
}

/**
 * WLBNotificationRecord updateMany
 */
export type WLBNotificationRecordUpdateManyArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * The data used to update WLBNotificationRecords.
   */
  data: Prisma.XOR<
    Prisma.WLBNotificationRecordUpdateManyMutationInput,
    Prisma.WLBNotificationRecordUncheckedUpdateManyInput
  >
  /**
   * Filter which WLBNotificationRecords to update
   */
  where?: Prisma.WLBNotificationRecordWhereInput
  /**
   * Limit how many WLBNotificationRecords to update.
   */
  limit?: number
}

/**
 * WLBNotificationRecord updateManyAndReturn
 */
export type WLBNotificationRecordUpdateManyAndReturnArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the WLBNotificationRecord
   */
  select?: Prisma.WLBNotificationRecordSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the WLBNotificationRecord
   */
  omit?: Prisma.WLBNotificationRecordOmit<ExtArgs> | null
  /**
   * The data used to update WLBNotificationRecords.
   */
  data: Prisma.XOR<
    Prisma.WLBNotificationRecordUpdateManyMutationInput,
    Prisma.WLBNotificationRecordUncheckedUpdateManyInput
  >
  /**
   * Filter which WLBNotificationRecords to update
   */
  where?: Prisma.WLBNotificationRecordWhereInput
  /**
   * Limit how many WLBNotificationRecords to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WLBNotificationRecordIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * WLBNotificationRecord upsert
 */
export type WLBNotificationRecordUpsertArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the WLBNotificationRecord
   */
  select?: Prisma.WLBNotificationRecordSelect<ExtArgs> | null
  /**
   * Omit specific fields from the WLBNotificationRecord
   */
  omit?: Prisma.WLBNotificationRecordOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WLBNotificationRecordInclude<ExtArgs> | null
  /**
   * The filter to search for the WLBNotificationRecord to update in case it exists.
   */
  where: Prisma.WLBNotificationRecordWhereUniqueInput
  /**
   * In case the WLBNotificationRecord found by the `where` argument doesn't exist, create a new WLBNotificationRecord with this data.
   */
  create: Prisma.XOR<
    Prisma.WLBNotificationRecordCreateInput,
    Prisma.WLBNotificationRecordUncheckedCreateInput
  >
  /**
   * In case the WLBNotificationRecord was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<
    Prisma.WLBNotificationRecordUpdateInput,
    Prisma.WLBNotificationRecordUncheckedUpdateInput
  >
}

/**
 * WLBNotificationRecord delete
 */
export type WLBNotificationRecordDeleteArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the WLBNotificationRecord
   */
  select?: Prisma.WLBNotificationRecordSelect<ExtArgs> | null
  /**
   * Omit specific fields from the WLBNotificationRecord
   */
  omit?: Prisma.WLBNotificationRecordOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WLBNotificationRecordInclude<ExtArgs> | null
  /**
   * Filter which WLBNotificationRecord to delete.
   */
  where: Prisma.WLBNotificationRecordWhereUniqueInput
}

/**
 * WLBNotificationRecord deleteMany
 */
export type WLBNotificationRecordDeleteManyArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Filter which WLBNotificationRecords to delete
   */
  where?: Prisma.WLBNotificationRecordWhereInput
  /**
   * Limit how many WLBNotificationRecords to delete.
   */
  limit?: number
}

/**
 * WLBNotificationRecord.dailyRecord
 */
export type WLBNotificationRecord$dailyRecordArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the WLBDailyRecord
   */
  select?: Prisma.WLBDailyRecordSelect<ExtArgs> | null
  /**
   * Omit specific fields from the WLBDailyRecord
   */
  omit?: Prisma.WLBDailyRecordOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WLBDailyRecordInclude<ExtArgs> | null
  where?: Prisma.WLBDailyRecordWhereInput
}

/**
 * WLBNotificationRecord.subscription
 */
export type WLBNotificationRecord$subscriptionArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the WLBSubscription
   */
  select?: Prisma.WLBSubscriptionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the WLBSubscription
   */
  omit?: Prisma.WLBSubscriptionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WLBSubscriptionInclude<ExtArgs> | null
  where?: Prisma.WLBSubscriptionWhereInput
}

/**
 * WLBNotificationRecord without action
 */
export type WLBNotificationRecordDefaultArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the WLBNotificationRecord
   */
  select?: Prisma.WLBNotificationRecordSelect<ExtArgs> | null
  /**
   * Omit specific fields from the WLBNotificationRecord
   */
  omit?: Prisma.WLBNotificationRecordOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WLBNotificationRecordInclude<ExtArgs> | null
}
