/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck
/*
 * This file exports the `WLBSubscription` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from '@prisma/client/runtime/client'

import type * as $Enums from '../enums'
import type * as Prisma from '../internal/prismaNamespace'

/**
 * Model WLBSubscription
 * WLB 订阅配置
 */
export type WLBSubscriptionModel =
  runtime.Types.Result.DefaultSelection<Prisma.$WLBSubscriptionPayload>

export type AggregateWLBSubscription = {
  _count: WLBSubscriptionCountAggregateOutputType | null
  _avg: WLBSubscriptionAvgAggregateOutputType | null
  _sum: WLBSubscriptionSumAggregateOutputType | null
  _min: WLBSubscriptionMinAggregateOutputType | null
  _max: WLBSubscriptionMaxAggregateOutputType | null
}

export type WLBSubscriptionAvgAggregateOutputType = {
  timeOffset: number | null
}

export type WLBSubscriptionSumAggregateOutputType = {
  timeOffset: number | null
}

export type WLBSubscriptionMinAggregateOutputType = {
  id: string | null
  name: string | null
  enable: boolean | null
  type: $Enums.WLBSubscriptionType | null
  message: $Enums.WLBSubscriptionMessage | null
  timeOffset: number | null
  profileId: string | null
  userId: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type WLBSubscriptionMaxAggregateOutputType = {
  id: string | null
  name: string | null
  enable: boolean | null
  type: $Enums.WLBSubscriptionType | null
  message: $Enums.WLBSubscriptionMessage | null
  timeOffset: number | null
  profileId: string | null
  userId: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type WLBSubscriptionCountAggregateOutputType = {
  id: number
  name: number
  enable: number
  type: number
  message: number
  config: number
  timeOffset: number
  profileId: number
  userId: number
  createdAt: number
  updatedAt: number
  _all: number
}

export type WLBSubscriptionAvgAggregateInputType = {
  timeOffset?: true
}

export type WLBSubscriptionSumAggregateInputType = {
  timeOffset?: true
}

export type WLBSubscriptionMinAggregateInputType = {
  id?: true
  name?: true
  enable?: true
  type?: true
  message?: true
  timeOffset?: true
  profileId?: true
  userId?: true
  createdAt?: true
  updatedAt?: true
}

export type WLBSubscriptionMaxAggregateInputType = {
  id?: true
  name?: true
  enable?: true
  type?: true
  message?: true
  timeOffset?: true
  profileId?: true
  userId?: true
  createdAt?: true
  updatedAt?: true
}

export type WLBSubscriptionCountAggregateInputType = {
  id?: true
  name?: true
  enable?: true
  type?: true
  message?: true
  config?: true
  timeOffset?: true
  profileId?: true
  userId?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type WLBSubscriptionAggregateArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Filter which WLBSubscription to aggregate.
   */
  where?: Prisma.WLBSubscriptionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   *
   * Determine the order of WLBSubscriptions to fetch.
   */
  orderBy?:
    | Prisma.WLBSubscriptionOrderByWithRelationInput
    | Prisma.WLBSubscriptionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   *
   * Sets the start position
   */
  cursor?: Prisma.WLBSubscriptionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Take `±n` WLBSubscriptions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Skip the first `n` WLBSubscriptions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   *
   * Count returned WLBSubscriptions
   **/
  _count?: true | WLBSubscriptionCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   *
   * Select which fields to average
   **/
  _avg?: WLBSubscriptionAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   *
   * Select which fields to sum
   **/
  _sum?: WLBSubscriptionSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   *
   * Select which fields to find the minimum value
   **/
  _min?: WLBSubscriptionMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   *
   * Select which fields to find the maximum value
   **/
  _max?: WLBSubscriptionMaxAggregateInputType
}

export type GetWLBSubscriptionAggregateType<T extends WLBSubscriptionAggregateArgs> = {
  [P in keyof T & keyof AggregateWLBSubscription]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateWLBSubscription[P]>
    : Prisma.GetScalarType<T[P], AggregateWLBSubscription[P]>
}

export type WLBSubscriptionGroupByArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  where?: Prisma.WLBSubscriptionWhereInput
  orderBy?:
    | Prisma.WLBSubscriptionOrderByWithAggregationInput
    | Prisma.WLBSubscriptionOrderByWithAggregationInput[]
  by: Prisma.WLBSubscriptionScalarFieldEnum[] | Prisma.WLBSubscriptionScalarFieldEnum
  having?: Prisma.WLBSubscriptionScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: WLBSubscriptionCountAggregateInputType | true
  _avg?: WLBSubscriptionAvgAggregateInputType
  _sum?: WLBSubscriptionSumAggregateInputType
  _min?: WLBSubscriptionMinAggregateInputType
  _max?: WLBSubscriptionMaxAggregateInputType
}

export type WLBSubscriptionGroupByOutputType = {
  id: string
  name: string
  enable: boolean
  type: $Enums.WLBSubscriptionType
  message: $Enums.WLBSubscriptionMessage
  config: runtime.JsonValue
  timeOffset: number
  profileId: string
  userId: string | null
  createdAt: Date
  updatedAt: Date
  _count: WLBSubscriptionCountAggregateOutputType | null
  _avg: WLBSubscriptionAvgAggregateOutputType | null
  _sum: WLBSubscriptionSumAggregateOutputType | null
  _min: WLBSubscriptionMinAggregateOutputType | null
  _max: WLBSubscriptionMaxAggregateOutputType | null
}

export type GetWLBSubscriptionGroupByPayload<T extends WLBSubscriptionGroupByArgs> =
  Prisma.PrismaPromise<
    Array<
      Prisma.PickEnumerable<WLBSubscriptionGroupByOutputType, T['by']> & {
        [P in keyof T & keyof WLBSubscriptionGroupByOutputType]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], WLBSubscriptionGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], WLBSubscriptionGroupByOutputType[P]>
      }
    >
  >

export type WLBSubscriptionWhereInput = {
  AND?: Prisma.WLBSubscriptionWhereInput | Prisma.WLBSubscriptionWhereInput[]
  OR?: Prisma.WLBSubscriptionWhereInput[]
  NOT?: Prisma.WLBSubscriptionWhereInput | Prisma.WLBSubscriptionWhereInput[]
  id?: Prisma.StringFilter<'WLBSubscription'> | string
  name?: Prisma.StringFilter<'WLBSubscription'> | string
  enable?: Prisma.BoolFilter<'WLBSubscription'> | boolean
  type?: Prisma.EnumWLBSubscriptionTypeFilter<'WLBSubscription'> | $Enums.WLBSubscriptionType
  message?:
    | Prisma.EnumWLBSubscriptionMessageFilter<'WLBSubscription'>
    | $Enums.WLBSubscriptionMessage
  config?: Prisma.JsonFilter<'WLBSubscription'>
  timeOffset?: Prisma.IntFilter<'WLBSubscription'> | number
  profileId?: Prisma.StringFilter<'WLBSubscription'> | string
  userId?: Prisma.StringNullableFilter<'WLBSubscription'> | string | null
  createdAt?: Prisma.DateTimeFilter<'WLBSubscription'> | Date | string
  updatedAt?: Prisma.DateTimeFilter<'WLBSubscription'> | Date | string
  profile?: Prisma.XOR<Prisma.WLBProfileScalarRelationFilter, Prisma.WLBProfileWhereInput>
  author?: Prisma.XOR<Prisma.UserNullableScalarRelationFilter, Prisma.UserWhereInput> | null
  wlbNotificationRecords?: Prisma.WLBNotificationRecordListRelationFilter
}

export type WLBSubscriptionOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  enable?: Prisma.SortOrder
  type?: Prisma.SortOrder
  message?: Prisma.SortOrder
  config?: Prisma.SortOrder
  timeOffset?: Prisma.SortOrder
  profileId?: Prisma.SortOrder
  userId?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  profile?: Prisma.WLBProfileOrderByWithRelationInput
  author?: Prisma.UserOrderByWithRelationInput
  wlbNotificationRecords?: Prisma.WLBNotificationRecordOrderByRelationAggregateInput
}

export type WLBSubscriptionWhereUniqueInput = Prisma.AtLeast<
  {
    id?: string
    AND?: Prisma.WLBSubscriptionWhereInput | Prisma.WLBSubscriptionWhereInput[]
    OR?: Prisma.WLBSubscriptionWhereInput[]
    NOT?: Prisma.WLBSubscriptionWhereInput | Prisma.WLBSubscriptionWhereInput[]
    name?: Prisma.StringFilter<'WLBSubscription'> | string
    enable?: Prisma.BoolFilter<'WLBSubscription'> | boolean
    type?: Prisma.EnumWLBSubscriptionTypeFilter<'WLBSubscription'> | $Enums.WLBSubscriptionType
    message?:
      | Prisma.EnumWLBSubscriptionMessageFilter<'WLBSubscription'>
      | $Enums.WLBSubscriptionMessage
    config?: Prisma.JsonFilter<'WLBSubscription'>
    timeOffset?: Prisma.IntFilter<'WLBSubscription'> | number
    profileId?: Prisma.StringFilter<'WLBSubscription'> | string
    userId?: Prisma.StringNullableFilter<'WLBSubscription'> | string | null
    createdAt?: Prisma.DateTimeFilter<'WLBSubscription'> | Date | string
    updatedAt?: Prisma.DateTimeFilter<'WLBSubscription'> | Date | string
    profile?: Prisma.XOR<Prisma.WLBProfileScalarRelationFilter, Prisma.WLBProfileWhereInput>
    author?: Prisma.XOR<Prisma.UserNullableScalarRelationFilter, Prisma.UserWhereInput> | null
    wlbNotificationRecords?: Prisma.WLBNotificationRecordListRelationFilter
  },
  'id'
>

export type WLBSubscriptionOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  enable?: Prisma.SortOrder
  type?: Prisma.SortOrder
  message?: Prisma.SortOrder
  config?: Prisma.SortOrder
  timeOffset?: Prisma.SortOrder
  profileId?: Prisma.SortOrder
  userId?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.WLBSubscriptionCountOrderByAggregateInput
  _avg?: Prisma.WLBSubscriptionAvgOrderByAggregateInput
  _max?: Prisma.WLBSubscriptionMaxOrderByAggregateInput
  _min?: Prisma.WLBSubscriptionMinOrderByAggregateInput
  _sum?: Prisma.WLBSubscriptionSumOrderByAggregateInput
}

export type WLBSubscriptionScalarWhereWithAggregatesInput = {
  AND?:
    | Prisma.WLBSubscriptionScalarWhereWithAggregatesInput
    | Prisma.WLBSubscriptionScalarWhereWithAggregatesInput[]
  OR?: Prisma.WLBSubscriptionScalarWhereWithAggregatesInput[]
  NOT?:
    | Prisma.WLBSubscriptionScalarWhereWithAggregatesInput
    | Prisma.WLBSubscriptionScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<'WLBSubscription'> | string
  name?: Prisma.StringWithAggregatesFilter<'WLBSubscription'> | string
  enable?: Prisma.BoolWithAggregatesFilter<'WLBSubscription'> | boolean
  type?:
    | Prisma.EnumWLBSubscriptionTypeWithAggregatesFilter<'WLBSubscription'>
    | $Enums.WLBSubscriptionType
  message?:
    | Prisma.EnumWLBSubscriptionMessageWithAggregatesFilter<'WLBSubscription'>
    | $Enums.WLBSubscriptionMessage
  config?: Prisma.JsonWithAggregatesFilter<'WLBSubscription'>
  timeOffset?: Prisma.IntWithAggregatesFilter<'WLBSubscription'> | number
  profileId?: Prisma.StringWithAggregatesFilter<'WLBSubscription'> | string
  userId?: Prisma.StringNullableWithAggregatesFilter<'WLBSubscription'> | string | null
  createdAt?: Prisma.DateTimeWithAggregatesFilter<'WLBSubscription'> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<'WLBSubscription'> | Date | string
}

export type WLBSubscriptionCreateInput = {
  id?: string
  name: string
  enable?: boolean
  type: $Enums.WLBSubscriptionType
  message?: $Enums.WLBSubscriptionMessage
  config: Prisma.JsonNullValueInput | runtime.InputJsonValue
  timeOffset?: number
  createdAt?: Date | string
  updatedAt?: Date | string
  profile: Prisma.WLBProfileCreateNestedOneWithoutWlbsubscriptionsInput
  author?: Prisma.UserCreateNestedOneWithoutWlbsubscriptionsInput
  wlbNotificationRecords?: Prisma.WLBNotificationRecordCreateNestedManyWithoutSubscriptionInput
}

export type WLBSubscriptionUncheckedCreateInput = {
  id?: string
  name: string
  enable?: boolean
  type: $Enums.WLBSubscriptionType
  message?: $Enums.WLBSubscriptionMessage
  config: Prisma.JsonNullValueInput | runtime.InputJsonValue
  timeOffset?: number
  profileId: string
  userId?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  wlbNotificationRecords?: Prisma.WLBNotificationRecordUncheckedCreateNestedManyWithoutSubscriptionInput
}

export type WLBSubscriptionUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  enable?: Prisma.BoolFieldUpdateOperationsInput | boolean
  type?: Prisma.EnumWLBSubscriptionTypeFieldUpdateOperationsInput | $Enums.WLBSubscriptionType
  message?:
    | Prisma.EnumWLBSubscriptionMessageFieldUpdateOperationsInput
    | $Enums.WLBSubscriptionMessage
  config?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  timeOffset?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  profile?: Prisma.WLBProfileUpdateOneRequiredWithoutWlbsubscriptionsNestedInput
  author?: Prisma.UserUpdateOneWithoutWlbsubscriptionsNestedInput
  wlbNotificationRecords?: Prisma.WLBNotificationRecordUpdateManyWithoutSubscriptionNestedInput
}

export type WLBSubscriptionUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  enable?: Prisma.BoolFieldUpdateOperationsInput | boolean
  type?: Prisma.EnumWLBSubscriptionTypeFieldUpdateOperationsInput | $Enums.WLBSubscriptionType
  message?:
    | Prisma.EnumWLBSubscriptionMessageFieldUpdateOperationsInput
    | $Enums.WLBSubscriptionMessage
  config?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  timeOffset?: Prisma.IntFieldUpdateOperationsInput | number
  profileId?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  wlbNotificationRecords?: Prisma.WLBNotificationRecordUncheckedUpdateManyWithoutSubscriptionNestedInput
}

export type WLBSubscriptionCreateManyInput = {
  id?: string
  name: string
  enable?: boolean
  type: $Enums.WLBSubscriptionType
  message?: $Enums.WLBSubscriptionMessage
  config: Prisma.JsonNullValueInput | runtime.InputJsonValue
  timeOffset?: number
  profileId: string
  userId?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type WLBSubscriptionUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  enable?: Prisma.BoolFieldUpdateOperationsInput | boolean
  type?: Prisma.EnumWLBSubscriptionTypeFieldUpdateOperationsInput | $Enums.WLBSubscriptionType
  message?:
    | Prisma.EnumWLBSubscriptionMessageFieldUpdateOperationsInput
    | $Enums.WLBSubscriptionMessage
  config?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  timeOffset?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type WLBSubscriptionUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  enable?: Prisma.BoolFieldUpdateOperationsInput | boolean
  type?: Prisma.EnumWLBSubscriptionTypeFieldUpdateOperationsInput | $Enums.WLBSubscriptionType
  message?:
    | Prisma.EnumWLBSubscriptionMessageFieldUpdateOperationsInput
    | $Enums.WLBSubscriptionMessage
  config?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  timeOffset?: Prisma.IntFieldUpdateOperationsInput | number
  profileId?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type WLBSubscriptionListRelationFilter = {
  every?: Prisma.WLBSubscriptionWhereInput
  some?: Prisma.WLBSubscriptionWhereInput
  none?: Prisma.WLBSubscriptionWhereInput
}

export type WLBSubscriptionOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type WLBSubscriptionCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  enable?: Prisma.SortOrder
  type?: Prisma.SortOrder
  message?: Prisma.SortOrder
  config?: Prisma.SortOrder
  timeOffset?: Prisma.SortOrder
  profileId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type WLBSubscriptionAvgOrderByAggregateInput = {
  timeOffset?: Prisma.SortOrder
}

export type WLBSubscriptionMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  enable?: Prisma.SortOrder
  type?: Prisma.SortOrder
  message?: Prisma.SortOrder
  timeOffset?: Prisma.SortOrder
  profileId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type WLBSubscriptionMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  enable?: Prisma.SortOrder
  type?: Prisma.SortOrder
  message?: Prisma.SortOrder
  timeOffset?: Prisma.SortOrder
  profileId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type WLBSubscriptionSumOrderByAggregateInput = {
  timeOffset?: Prisma.SortOrder
}

export type WLBSubscriptionNullableScalarRelationFilter = {
  is?: Prisma.WLBSubscriptionWhereInput | null
  isNot?: Prisma.WLBSubscriptionWhereInput | null
}

export type WLBSubscriptionCreateNestedManyWithoutAuthorInput = {
  create?:
    | Prisma.XOR<
        Prisma.WLBSubscriptionCreateWithoutAuthorInput,
        Prisma.WLBSubscriptionUncheckedCreateWithoutAuthorInput
      >
    | Prisma.WLBSubscriptionCreateWithoutAuthorInput[]
    | Prisma.WLBSubscriptionUncheckedCreateWithoutAuthorInput[]
  connectOrCreate?:
    | Prisma.WLBSubscriptionCreateOrConnectWithoutAuthorInput
    | Prisma.WLBSubscriptionCreateOrConnectWithoutAuthorInput[]
  createMany?: Prisma.WLBSubscriptionCreateManyAuthorInputEnvelope
  connect?: Prisma.WLBSubscriptionWhereUniqueInput | Prisma.WLBSubscriptionWhereUniqueInput[]
}

export type WLBSubscriptionUncheckedCreateNestedManyWithoutAuthorInput = {
  create?:
    | Prisma.XOR<
        Prisma.WLBSubscriptionCreateWithoutAuthorInput,
        Prisma.WLBSubscriptionUncheckedCreateWithoutAuthorInput
      >
    | Prisma.WLBSubscriptionCreateWithoutAuthorInput[]
    | Prisma.WLBSubscriptionUncheckedCreateWithoutAuthorInput[]
  connectOrCreate?:
    | Prisma.WLBSubscriptionCreateOrConnectWithoutAuthorInput
    | Prisma.WLBSubscriptionCreateOrConnectWithoutAuthorInput[]
  createMany?: Prisma.WLBSubscriptionCreateManyAuthorInputEnvelope
  connect?: Prisma.WLBSubscriptionWhereUniqueInput | Prisma.WLBSubscriptionWhereUniqueInput[]
}

export type WLBSubscriptionUpdateManyWithoutAuthorNestedInput = {
  create?:
    | Prisma.XOR<
        Prisma.WLBSubscriptionCreateWithoutAuthorInput,
        Prisma.WLBSubscriptionUncheckedCreateWithoutAuthorInput
      >
    | Prisma.WLBSubscriptionCreateWithoutAuthorInput[]
    | Prisma.WLBSubscriptionUncheckedCreateWithoutAuthorInput[]
  connectOrCreate?:
    | Prisma.WLBSubscriptionCreateOrConnectWithoutAuthorInput
    | Prisma.WLBSubscriptionCreateOrConnectWithoutAuthorInput[]
  upsert?:
    | Prisma.WLBSubscriptionUpsertWithWhereUniqueWithoutAuthorInput
    | Prisma.WLBSubscriptionUpsertWithWhereUniqueWithoutAuthorInput[]
  createMany?: Prisma.WLBSubscriptionCreateManyAuthorInputEnvelope
  set?: Prisma.WLBSubscriptionWhereUniqueInput | Prisma.WLBSubscriptionWhereUniqueInput[]
  disconnect?: Prisma.WLBSubscriptionWhereUniqueInput | Prisma.WLBSubscriptionWhereUniqueInput[]
  delete?: Prisma.WLBSubscriptionWhereUniqueInput | Prisma.WLBSubscriptionWhereUniqueInput[]
  connect?: Prisma.WLBSubscriptionWhereUniqueInput | Prisma.WLBSubscriptionWhereUniqueInput[]
  update?:
    | Prisma.WLBSubscriptionUpdateWithWhereUniqueWithoutAuthorInput
    | Prisma.WLBSubscriptionUpdateWithWhereUniqueWithoutAuthorInput[]
  updateMany?:
    | Prisma.WLBSubscriptionUpdateManyWithWhereWithoutAuthorInput
    | Prisma.WLBSubscriptionUpdateManyWithWhereWithoutAuthorInput[]
  deleteMany?: Prisma.WLBSubscriptionScalarWhereInput | Prisma.WLBSubscriptionScalarWhereInput[]
}

export type WLBSubscriptionUncheckedUpdateManyWithoutAuthorNestedInput = {
  create?:
    | Prisma.XOR<
        Prisma.WLBSubscriptionCreateWithoutAuthorInput,
        Prisma.WLBSubscriptionUncheckedCreateWithoutAuthorInput
      >
    | Prisma.WLBSubscriptionCreateWithoutAuthorInput[]
    | Prisma.WLBSubscriptionUncheckedCreateWithoutAuthorInput[]
  connectOrCreate?:
    | Prisma.WLBSubscriptionCreateOrConnectWithoutAuthorInput
    | Prisma.WLBSubscriptionCreateOrConnectWithoutAuthorInput[]
  upsert?:
    | Prisma.WLBSubscriptionUpsertWithWhereUniqueWithoutAuthorInput
    | Prisma.WLBSubscriptionUpsertWithWhereUniqueWithoutAuthorInput[]
  createMany?: Prisma.WLBSubscriptionCreateManyAuthorInputEnvelope
  set?: Prisma.WLBSubscriptionWhereUniqueInput | Prisma.WLBSubscriptionWhereUniqueInput[]
  disconnect?: Prisma.WLBSubscriptionWhereUniqueInput | Prisma.WLBSubscriptionWhereUniqueInput[]
  delete?: Prisma.WLBSubscriptionWhereUniqueInput | Prisma.WLBSubscriptionWhereUniqueInput[]
  connect?: Prisma.WLBSubscriptionWhereUniqueInput | Prisma.WLBSubscriptionWhereUniqueInput[]
  update?:
    | Prisma.WLBSubscriptionUpdateWithWhereUniqueWithoutAuthorInput
    | Prisma.WLBSubscriptionUpdateWithWhereUniqueWithoutAuthorInput[]
  updateMany?:
    | Prisma.WLBSubscriptionUpdateManyWithWhereWithoutAuthorInput
    | Prisma.WLBSubscriptionUpdateManyWithWhereWithoutAuthorInput[]
  deleteMany?: Prisma.WLBSubscriptionScalarWhereInput | Prisma.WLBSubscriptionScalarWhereInput[]
}

export type WLBSubscriptionCreateNestedManyWithoutProfileInput = {
  create?:
    | Prisma.XOR<
        Prisma.WLBSubscriptionCreateWithoutProfileInput,
        Prisma.WLBSubscriptionUncheckedCreateWithoutProfileInput
      >
    | Prisma.WLBSubscriptionCreateWithoutProfileInput[]
    | Prisma.WLBSubscriptionUncheckedCreateWithoutProfileInput[]
  connectOrCreate?:
    | Prisma.WLBSubscriptionCreateOrConnectWithoutProfileInput
    | Prisma.WLBSubscriptionCreateOrConnectWithoutProfileInput[]
  createMany?: Prisma.WLBSubscriptionCreateManyProfileInputEnvelope
  connect?: Prisma.WLBSubscriptionWhereUniqueInput | Prisma.WLBSubscriptionWhereUniqueInput[]
}

export type WLBSubscriptionUncheckedCreateNestedManyWithoutProfileInput = {
  create?:
    | Prisma.XOR<
        Prisma.WLBSubscriptionCreateWithoutProfileInput,
        Prisma.WLBSubscriptionUncheckedCreateWithoutProfileInput
      >
    | Prisma.WLBSubscriptionCreateWithoutProfileInput[]
    | Prisma.WLBSubscriptionUncheckedCreateWithoutProfileInput[]
  connectOrCreate?:
    | Prisma.WLBSubscriptionCreateOrConnectWithoutProfileInput
    | Prisma.WLBSubscriptionCreateOrConnectWithoutProfileInput[]
  createMany?: Prisma.WLBSubscriptionCreateManyProfileInputEnvelope
  connect?: Prisma.WLBSubscriptionWhereUniqueInput | Prisma.WLBSubscriptionWhereUniqueInput[]
}

export type WLBSubscriptionUpdateManyWithoutProfileNestedInput = {
  create?:
    | Prisma.XOR<
        Prisma.WLBSubscriptionCreateWithoutProfileInput,
        Prisma.WLBSubscriptionUncheckedCreateWithoutProfileInput
      >
    | Prisma.WLBSubscriptionCreateWithoutProfileInput[]
    | Prisma.WLBSubscriptionUncheckedCreateWithoutProfileInput[]
  connectOrCreate?:
    | Prisma.WLBSubscriptionCreateOrConnectWithoutProfileInput
    | Prisma.WLBSubscriptionCreateOrConnectWithoutProfileInput[]
  upsert?:
    | Prisma.WLBSubscriptionUpsertWithWhereUniqueWithoutProfileInput
    | Prisma.WLBSubscriptionUpsertWithWhereUniqueWithoutProfileInput[]
  createMany?: Prisma.WLBSubscriptionCreateManyProfileInputEnvelope
  set?: Prisma.WLBSubscriptionWhereUniqueInput | Prisma.WLBSubscriptionWhereUniqueInput[]
  disconnect?: Prisma.WLBSubscriptionWhereUniqueInput | Prisma.WLBSubscriptionWhereUniqueInput[]
  delete?: Prisma.WLBSubscriptionWhereUniqueInput | Prisma.WLBSubscriptionWhereUniqueInput[]
  connect?: Prisma.WLBSubscriptionWhereUniqueInput | Prisma.WLBSubscriptionWhereUniqueInput[]
  update?:
    | Prisma.WLBSubscriptionUpdateWithWhereUniqueWithoutProfileInput
    | Prisma.WLBSubscriptionUpdateWithWhereUniqueWithoutProfileInput[]
  updateMany?:
    | Prisma.WLBSubscriptionUpdateManyWithWhereWithoutProfileInput
    | Prisma.WLBSubscriptionUpdateManyWithWhereWithoutProfileInput[]
  deleteMany?: Prisma.WLBSubscriptionScalarWhereInput | Prisma.WLBSubscriptionScalarWhereInput[]
}

export type WLBSubscriptionUncheckedUpdateManyWithoutProfileNestedInput = {
  create?:
    | Prisma.XOR<
        Prisma.WLBSubscriptionCreateWithoutProfileInput,
        Prisma.WLBSubscriptionUncheckedCreateWithoutProfileInput
      >
    | Prisma.WLBSubscriptionCreateWithoutProfileInput[]
    | Prisma.WLBSubscriptionUncheckedCreateWithoutProfileInput[]
  connectOrCreate?:
    | Prisma.WLBSubscriptionCreateOrConnectWithoutProfileInput
    | Prisma.WLBSubscriptionCreateOrConnectWithoutProfileInput[]
  upsert?:
    | Prisma.WLBSubscriptionUpsertWithWhereUniqueWithoutProfileInput
    | Prisma.WLBSubscriptionUpsertWithWhereUniqueWithoutProfileInput[]
  createMany?: Prisma.WLBSubscriptionCreateManyProfileInputEnvelope
  set?: Prisma.WLBSubscriptionWhereUniqueInput | Prisma.WLBSubscriptionWhereUniqueInput[]
  disconnect?: Prisma.WLBSubscriptionWhereUniqueInput | Prisma.WLBSubscriptionWhereUniqueInput[]
  delete?: Prisma.WLBSubscriptionWhereUniqueInput | Prisma.WLBSubscriptionWhereUniqueInput[]
  connect?: Prisma.WLBSubscriptionWhereUniqueInput | Prisma.WLBSubscriptionWhereUniqueInput[]
  update?:
    | Prisma.WLBSubscriptionUpdateWithWhereUniqueWithoutProfileInput
    | Prisma.WLBSubscriptionUpdateWithWhereUniqueWithoutProfileInput[]
  updateMany?:
    | Prisma.WLBSubscriptionUpdateManyWithWhereWithoutProfileInput
    | Prisma.WLBSubscriptionUpdateManyWithWhereWithoutProfileInput[]
  deleteMany?: Prisma.WLBSubscriptionScalarWhereInput | Prisma.WLBSubscriptionScalarWhereInput[]
}

export type EnumWLBSubscriptionTypeFieldUpdateOperationsInput = {
  set?: $Enums.WLBSubscriptionType
}

export type EnumWLBSubscriptionMessageFieldUpdateOperationsInput = {
  set?: $Enums.WLBSubscriptionMessage
}

export type WLBSubscriptionCreateNestedOneWithoutWlbNotificationRecordsInput = {
  create?: Prisma.XOR<
    Prisma.WLBSubscriptionCreateWithoutWlbNotificationRecordsInput,
    Prisma.WLBSubscriptionUncheckedCreateWithoutWlbNotificationRecordsInput
  >
  connectOrCreate?: Prisma.WLBSubscriptionCreateOrConnectWithoutWlbNotificationRecordsInput
  connect?: Prisma.WLBSubscriptionWhereUniqueInput
}

export type WLBSubscriptionUpdateOneWithoutWlbNotificationRecordsNestedInput = {
  create?: Prisma.XOR<
    Prisma.WLBSubscriptionCreateWithoutWlbNotificationRecordsInput,
    Prisma.WLBSubscriptionUncheckedCreateWithoutWlbNotificationRecordsInput
  >
  connectOrCreate?: Prisma.WLBSubscriptionCreateOrConnectWithoutWlbNotificationRecordsInput
  upsert?: Prisma.WLBSubscriptionUpsertWithoutWlbNotificationRecordsInput
  disconnect?: Prisma.WLBSubscriptionWhereInput | boolean
  delete?: Prisma.WLBSubscriptionWhereInput | boolean
  connect?: Prisma.WLBSubscriptionWhereUniqueInput
  update?: Prisma.XOR<
    Prisma.XOR<
      Prisma.WLBSubscriptionUpdateToOneWithWhereWithoutWlbNotificationRecordsInput,
      Prisma.WLBSubscriptionUpdateWithoutWlbNotificationRecordsInput
    >,
    Prisma.WLBSubscriptionUncheckedUpdateWithoutWlbNotificationRecordsInput
  >
}

export type WLBSubscriptionCreateWithoutAuthorInput = {
  id?: string
  name: string
  enable?: boolean
  type: $Enums.WLBSubscriptionType
  message?: $Enums.WLBSubscriptionMessage
  config: Prisma.JsonNullValueInput | runtime.InputJsonValue
  timeOffset?: number
  createdAt?: Date | string
  updatedAt?: Date | string
  profile: Prisma.WLBProfileCreateNestedOneWithoutWlbsubscriptionsInput
  wlbNotificationRecords?: Prisma.WLBNotificationRecordCreateNestedManyWithoutSubscriptionInput
}

export type WLBSubscriptionUncheckedCreateWithoutAuthorInput = {
  id?: string
  name: string
  enable?: boolean
  type: $Enums.WLBSubscriptionType
  message?: $Enums.WLBSubscriptionMessage
  config: Prisma.JsonNullValueInput | runtime.InputJsonValue
  timeOffset?: number
  profileId: string
  createdAt?: Date | string
  updatedAt?: Date | string
  wlbNotificationRecords?: Prisma.WLBNotificationRecordUncheckedCreateNestedManyWithoutSubscriptionInput
}

export type WLBSubscriptionCreateOrConnectWithoutAuthorInput = {
  where: Prisma.WLBSubscriptionWhereUniqueInput
  create: Prisma.XOR<
    Prisma.WLBSubscriptionCreateWithoutAuthorInput,
    Prisma.WLBSubscriptionUncheckedCreateWithoutAuthorInput
  >
}

export type WLBSubscriptionCreateManyAuthorInputEnvelope = {
  data: Prisma.WLBSubscriptionCreateManyAuthorInput | Prisma.WLBSubscriptionCreateManyAuthorInput[]
  skipDuplicates?: boolean
}

export type WLBSubscriptionUpsertWithWhereUniqueWithoutAuthorInput = {
  where: Prisma.WLBSubscriptionWhereUniqueInput
  update: Prisma.XOR<
    Prisma.WLBSubscriptionUpdateWithoutAuthorInput,
    Prisma.WLBSubscriptionUncheckedUpdateWithoutAuthorInput
  >
  create: Prisma.XOR<
    Prisma.WLBSubscriptionCreateWithoutAuthorInput,
    Prisma.WLBSubscriptionUncheckedCreateWithoutAuthorInput
  >
}

export type WLBSubscriptionUpdateWithWhereUniqueWithoutAuthorInput = {
  where: Prisma.WLBSubscriptionWhereUniqueInput
  data: Prisma.XOR<
    Prisma.WLBSubscriptionUpdateWithoutAuthorInput,
    Prisma.WLBSubscriptionUncheckedUpdateWithoutAuthorInput
  >
}

export type WLBSubscriptionUpdateManyWithWhereWithoutAuthorInput = {
  where: Prisma.WLBSubscriptionScalarWhereInput
  data: Prisma.XOR<
    Prisma.WLBSubscriptionUpdateManyMutationInput,
    Prisma.WLBSubscriptionUncheckedUpdateManyWithoutAuthorInput
  >
}

export type WLBSubscriptionScalarWhereInput = {
  AND?: Prisma.WLBSubscriptionScalarWhereInput | Prisma.WLBSubscriptionScalarWhereInput[]
  OR?: Prisma.WLBSubscriptionScalarWhereInput[]
  NOT?: Prisma.WLBSubscriptionScalarWhereInput | Prisma.WLBSubscriptionScalarWhereInput[]
  id?: Prisma.StringFilter<'WLBSubscription'> | string
  name?: Prisma.StringFilter<'WLBSubscription'> | string
  enable?: Prisma.BoolFilter<'WLBSubscription'> | boolean
  type?: Prisma.EnumWLBSubscriptionTypeFilter<'WLBSubscription'> | $Enums.WLBSubscriptionType
  message?:
    | Prisma.EnumWLBSubscriptionMessageFilter<'WLBSubscription'>
    | $Enums.WLBSubscriptionMessage
  config?: Prisma.JsonFilter<'WLBSubscription'>
  timeOffset?: Prisma.IntFilter<'WLBSubscription'> | number
  profileId?: Prisma.StringFilter<'WLBSubscription'> | string
  userId?: Prisma.StringNullableFilter<'WLBSubscription'> | string | null
  createdAt?: Prisma.DateTimeFilter<'WLBSubscription'> | Date | string
  updatedAt?: Prisma.DateTimeFilter<'WLBSubscription'> | Date | string
}

export type WLBSubscriptionCreateWithoutProfileInput = {
  id?: string
  name: string
  enable?: boolean
  type: $Enums.WLBSubscriptionType
  message?: $Enums.WLBSubscriptionMessage
  config: Prisma.JsonNullValueInput | runtime.InputJsonValue
  timeOffset?: number
  createdAt?: Date | string
  updatedAt?: Date | string
  author?: Prisma.UserCreateNestedOneWithoutWlbsubscriptionsInput
  wlbNotificationRecords?: Prisma.WLBNotificationRecordCreateNestedManyWithoutSubscriptionInput
}

export type WLBSubscriptionUncheckedCreateWithoutProfileInput = {
  id?: string
  name: string
  enable?: boolean
  type: $Enums.WLBSubscriptionType
  message?: $Enums.WLBSubscriptionMessage
  config: Prisma.JsonNullValueInput | runtime.InputJsonValue
  timeOffset?: number
  userId?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  wlbNotificationRecords?: Prisma.WLBNotificationRecordUncheckedCreateNestedManyWithoutSubscriptionInput
}

export type WLBSubscriptionCreateOrConnectWithoutProfileInput = {
  where: Prisma.WLBSubscriptionWhereUniqueInput
  create: Prisma.XOR<
    Prisma.WLBSubscriptionCreateWithoutProfileInput,
    Prisma.WLBSubscriptionUncheckedCreateWithoutProfileInput
  >
}

export type WLBSubscriptionCreateManyProfileInputEnvelope = {
  data:
    | Prisma.WLBSubscriptionCreateManyProfileInput
    | Prisma.WLBSubscriptionCreateManyProfileInput[]
  skipDuplicates?: boolean
}

export type WLBSubscriptionUpsertWithWhereUniqueWithoutProfileInput = {
  where: Prisma.WLBSubscriptionWhereUniqueInput
  update: Prisma.XOR<
    Prisma.WLBSubscriptionUpdateWithoutProfileInput,
    Prisma.WLBSubscriptionUncheckedUpdateWithoutProfileInput
  >
  create: Prisma.XOR<
    Prisma.WLBSubscriptionCreateWithoutProfileInput,
    Prisma.WLBSubscriptionUncheckedCreateWithoutProfileInput
  >
}

export type WLBSubscriptionUpdateWithWhereUniqueWithoutProfileInput = {
  where: Prisma.WLBSubscriptionWhereUniqueInput
  data: Prisma.XOR<
    Prisma.WLBSubscriptionUpdateWithoutProfileInput,
    Prisma.WLBSubscriptionUncheckedUpdateWithoutProfileInput
  >
}

export type WLBSubscriptionUpdateManyWithWhereWithoutProfileInput = {
  where: Prisma.WLBSubscriptionScalarWhereInput
  data: Prisma.XOR<
    Prisma.WLBSubscriptionUpdateManyMutationInput,
    Prisma.WLBSubscriptionUncheckedUpdateManyWithoutProfileInput
  >
}

export type WLBSubscriptionCreateWithoutWlbNotificationRecordsInput = {
  id?: string
  name: string
  enable?: boolean
  type: $Enums.WLBSubscriptionType
  message?: $Enums.WLBSubscriptionMessage
  config: Prisma.JsonNullValueInput | runtime.InputJsonValue
  timeOffset?: number
  createdAt?: Date | string
  updatedAt?: Date | string
  profile: Prisma.WLBProfileCreateNestedOneWithoutWlbsubscriptionsInput
  author?: Prisma.UserCreateNestedOneWithoutWlbsubscriptionsInput
}

export type WLBSubscriptionUncheckedCreateWithoutWlbNotificationRecordsInput = {
  id?: string
  name: string
  enable?: boolean
  type: $Enums.WLBSubscriptionType
  message?: $Enums.WLBSubscriptionMessage
  config: Prisma.JsonNullValueInput | runtime.InputJsonValue
  timeOffset?: number
  profileId: string
  userId?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type WLBSubscriptionCreateOrConnectWithoutWlbNotificationRecordsInput = {
  where: Prisma.WLBSubscriptionWhereUniqueInput
  create: Prisma.XOR<
    Prisma.WLBSubscriptionCreateWithoutWlbNotificationRecordsInput,
    Prisma.WLBSubscriptionUncheckedCreateWithoutWlbNotificationRecordsInput
  >
}

export type WLBSubscriptionUpsertWithoutWlbNotificationRecordsInput = {
  update: Prisma.XOR<
    Prisma.WLBSubscriptionUpdateWithoutWlbNotificationRecordsInput,
    Prisma.WLBSubscriptionUncheckedUpdateWithoutWlbNotificationRecordsInput
  >
  create: Prisma.XOR<
    Prisma.WLBSubscriptionCreateWithoutWlbNotificationRecordsInput,
    Prisma.WLBSubscriptionUncheckedCreateWithoutWlbNotificationRecordsInput
  >
  where?: Prisma.WLBSubscriptionWhereInput
}

export type WLBSubscriptionUpdateToOneWithWhereWithoutWlbNotificationRecordsInput = {
  where?: Prisma.WLBSubscriptionWhereInput
  data: Prisma.XOR<
    Prisma.WLBSubscriptionUpdateWithoutWlbNotificationRecordsInput,
    Prisma.WLBSubscriptionUncheckedUpdateWithoutWlbNotificationRecordsInput
  >
}

export type WLBSubscriptionUpdateWithoutWlbNotificationRecordsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  enable?: Prisma.BoolFieldUpdateOperationsInput | boolean
  type?: Prisma.EnumWLBSubscriptionTypeFieldUpdateOperationsInput | $Enums.WLBSubscriptionType
  message?:
    | Prisma.EnumWLBSubscriptionMessageFieldUpdateOperationsInput
    | $Enums.WLBSubscriptionMessage
  config?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  timeOffset?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  profile?: Prisma.WLBProfileUpdateOneRequiredWithoutWlbsubscriptionsNestedInput
  author?: Prisma.UserUpdateOneWithoutWlbsubscriptionsNestedInput
}

export type WLBSubscriptionUncheckedUpdateWithoutWlbNotificationRecordsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  enable?: Prisma.BoolFieldUpdateOperationsInput | boolean
  type?: Prisma.EnumWLBSubscriptionTypeFieldUpdateOperationsInput | $Enums.WLBSubscriptionType
  message?:
    | Prisma.EnumWLBSubscriptionMessageFieldUpdateOperationsInput
    | $Enums.WLBSubscriptionMessage
  config?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  timeOffset?: Prisma.IntFieldUpdateOperationsInput | number
  profileId?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type WLBSubscriptionCreateManyAuthorInput = {
  id?: string
  name: string
  enable?: boolean
  type: $Enums.WLBSubscriptionType
  message?: $Enums.WLBSubscriptionMessage
  config: Prisma.JsonNullValueInput | runtime.InputJsonValue
  timeOffset?: number
  profileId: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type WLBSubscriptionUpdateWithoutAuthorInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  enable?: Prisma.BoolFieldUpdateOperationsInput | boolean
  type?: Prisma.EnumWLBSubscriptionTypeFieldUpdateOperationsInput | $Enums.WLBSubscriptionType
  message?:
    | Prisma.EnumWLBSubscriptionMessageFieldUpdateOperationsInput
    | $Enums.WLBSubscriptionMessage
  config?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  timeOffset?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  profile?: Prisma.WLBProfileUpdateOneRequiredWithoutWlbsubscriptionsNestedInput
  wlbNotificationRecords?: Prisma.WLBNotificationRecordUpdateManyWithoutSubscriptionNestedInput
}

export type WLBSubscriptionUncheckedUpdateWithoutAuthorInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  enable?: Prisma.BoolFieldUpdateOperationsInput | boolean
  type?: Prisma.EnumWLBSubscriptionTypeFieldUpdateOperationsInput | $Enums.WLBSubscriptionType
  message?:
    | Prisma.EnumWLBSubscriptionMessageFieldUpdateOperationsInput
    | $Enums.WLBSubscriptionMessage
  config?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  timeOffset?: Prisma.IntFieldUpdateOperationsInput | number
  profileId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  wlbNotificationRecords?: Prisma.WLBNotificationRecordUncheckedUpdateManyWithoutSubscriptionNestedInput
}

export type WLBSubscriptionUncheckedUpdateManyWithoutAuthorInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  enable?: Prisma.BoolFieldUpdateOperationsInput | boolean
  type?: Prisma.EnumWLBSubscriptionTypeFieldUpdateOperationsInput | $Enums.WLBSubscriptionType
  message?:
    | Prisma.EnumWLBSubscriptionMessageFieldUpdateOperationsInput
    | $Enums.WLBSubscriptionMessage
  config?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  timeOffset?: Prisma.IntFieldUpdateOperationsInput | number
  profileId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type WLBSubscriptionCreateManyProfileInput = {
  id?: string
  name: string
  enable?: boolean
  type: $Enums.WLBSubscriptionType
  message?: $Enums.WLBSubscriptionMessage
  config: Prisma.JsonNullValueInput | runtime.InputJsonValue
  timeOffset?: number
  userId?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type WLBSubscriptionUpdateWithoutProfileInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  enable?: Prisma.BoolFieldUpdateOperationsInput | boolean
  type?: Prisma.EnumWLBSubscriptionTypeFieldUpdateOperationsInput | $Enums.WLBSubscriptionType
  message?:
    | Prisma.EnumWLBSubscriptionMessageFieldUpdateOperationsInput
    | $Enums.WLBSubscriptionMessage
  config?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  timeOffset?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  author?: Prisma.UserUpdateOneWithoutWlbsubscriptionsNestedInput
  wlbNotificationRecords?: Prisma.WLBNotificationRecordUpdateManyWithoutSubscriptionNestedInput
}

export type WLBSubscriptionUncheckedUpdateWithoutProfileInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  enable?: Prisma.BoolFieldUpdateOperationsInput | boolean
  type?: Prisma.EnumWLBSubscriptionTypeFieldUpdateOperationsInput | $Enums.WLBSubscriptionType
  message?:
    | Prisma.EnumWLBSubscriptionMessageFieldUpdateOperationsInput
    | $Enums.WLBSubscriptionMessage
  config?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  timeOffset?: Prisma.IntFieldUpdateOperationsInput | number
  userId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  wlbNotificationRecords?: Prisma.WLBNotificationRecordUncheckedUpdateManyWithoutSubscriptionNestedInput
}

export type WLBSubscriptionUncheckedUpdateManyWithoutProfileInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  enable?: Prisma.BoolFieldUpdateOperationsInput | boolean
  type?: Prisma.EnumWLBSubscriptionTypeFieldUpdateOperationsInput | $Enums.WLBSubscriptionType
  message?:
    | Prisma.EnumWLBSubscriptionMessageFieldUpdateOperationsInput
    | $Enums.WLBSubscriptionMessage
  config?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  timeOffset?: Prisma.IntFieldUpdateOperationsInput | number
  userId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

/**
 * Count Type WLBSubscriptionCountOutputType
 */

export type WLBSubscriptionCountOutputType = {
  wlbNotificationRecords: number
}

export type WLBSubscriptionCountOutputTypeSelect<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  wlbNotificationRecords?: boolean | WLBSubscriptionCountOutputTypeCountWlbNotificationRecordsArgs
}

/**
 * WLBSubscriptionCountOutputType without action
 */
export type WLBSubscriptionCountOutputTypeDefaultArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the WLBSubscriptionCountOutputType
   */
  select?: Prisma.WLBSubscriptionCountOutputTypeSelect<ExtArgs> | null
}

/**
 * WLBSubscriptionCountOutputType without action
 */
export type WLBSubscriptionCountOutputTypeCountWlbNotificationRecordsArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  where?: Prisma.WLBNotificationRecordWhereInput
}

export type WLBSubscriptionSelect<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = runtime.Types.Extensions.GetSelect<
  {
    id?: boolean
    name?: boolean
    enable?: boolean
    type?: boolean
    message?: boolean
    config?: boolean
    timeOffset?: boolean
    profileId?: boolean
    userId?: boolean
    createdAt?: boolean
    updatedAt?: boolean
    profile?: boolean | Prisma.WLBProfileDefaultArgs<ExtArgs>
    author?: boolean | Prisma.WLBSubscription$authorArgs<ExtArgs>
    wlbNotificationRecords?: boolean | Prisma.WLBSubscription$wlbNotificationRecordsArgs<ExtArgs>
    _count?: boolean | Prisma.WLBSubscriptionCountOutputTypeDefaultArgs<ExtArgs>
  },
  ExtArgs['result']['wLBSubscription']
>

export type WLBSubscriptionSelectCreateManyAndReturn<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = runtime.Types.Extensions.GetSelect<
  {
    id?: boolean
    name?: boolean
    enable?: boolean
    type?: boolean
    message?: boolean
    config?: boolean
    timeOffset?: boolean
    profileId?: boolean
    userId?: boolean
    createdAt?: boolean
    updatedAt?: boolean
    profile?: boolean | Prisma.WLBProfileDefaultArgs<ExtArgs>
    author?: boolean | Prisma.WLBSubscription$authorArgs<ExtArgs>
  },
  ExtArgs['result']['wLBSubscription']
>

export type WLBSubscriptionSelectUpdateManyAndReturn<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = runtime.Types.Extensions.GetSelect<
  {
    id?: boolean
    name?: boolean
    enable?: boolean
    type?: boolean
    message?: boolean
    config?: boolean
    timeOffset?: boolean
    profileId?: boolean
    userId?: boolean
    createdAt?: boolean
    updatedAt?: boolean
    profile?: boolean | Prisma.WLBProfileDefaultArgs<ExtArgs>
    author?: boolean | Prisma.WLBSubscription$authorArgs<ExtArgs>
  },
  ExtArgs['result']['wLBSubscription']
>

export type WLBSubscriptionSelectScalar = {
  id?: boolean
  name?: boolean
  enable?: boolean
  type?: boolean
  message?: boolean
  config?: boolean
  timeOffset?: boolean
  profileId?: boolean
  userId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type WLBSubscriptionOmit<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = runtime.Types.Extensions.GetOmit<
  | 'id'
  | 'name'
  | 'enable'
  | 'type'
  | 'message'
  | 'config'
  | 'timeOffset'
  | 'profileId'
  | 'userId'
  | 'createdAt'
  | 'updatedAt',
  ExtArgs['result']['wLBSubscription']
>
export type WLBSubscriptionInclude<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  profile?: boolean | Prisma.WLBProfileDefaultArgs<ExtArgs>
  author?: boolean | Prisma.WLBSubscription$authorArgs<ExtArgs>
  wlbNotificationRecords?: boolean | Prisma.WLBSubscription$wlbNotificationRecordsArgs<ExtArgs>
  _count?: boolean | Prisma.WLBSubscriptionCountOutputTypeDefaultArgs<ExtArgs>
}
export type WLBSubscriptionIncludeCreateManyAndReturn<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  profile?: boolean | Prisma.WLBProfileDefaultArgs<ExtArgs>
  author?: boolean | Prisma.WLBSubscription$authorArgs<ExtArgs>
}
export type WLBSubscriptionIncludeUpdateManyAndReturn<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  profile?: boolean | Prisma.WLBProfileDefaultArgs<ExtArgs>
  author?: boolean | Prisma.WLBSubscription$authorArgs<ExtArgs>
}

export type $WLBSubscriptionPayload<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  name: 'WLBSubscription'
  objects: {
    profile: Prisma.$WLBProfilePayload<ExtArgs>
    author: Prisma.$UserPayload<ExtArgs> | null
    wlbNotificationRecords: Prisma.$WLBNotificationRecordPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<
    {
      id: string
      name: string
      enable: boolean
      type: $Enums.WLBSubscriptionType
      message: $Enums.WLBSubscriptionMessage
      /**
       * 配置详情
       */
      config: runtime.JsonValue
      /**
       * 时间偏移，从下班时间开始的偏移毫秒数，通常为负数，因为要提前通知
       */
      timeOffset: number
      profileId: string
      userId: string | null
      createdAt: Date
      updatedAt: Date
    },
    ExtArgs['result']['wLBSubscription']
  >
  composites: {}
}

export type WLBSubscriptionGetPayload<
  S extends boolean | null | undefined | WLBSubscriptionDefaultArgs,
> = runtime.Types.Result.GetResult<Prisma.$WLBSubscriptionPayload, S>

export type WLBSubscriptionCountArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = Omit<WLBSubscriptionFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
  select?: WLBSubscriptionCountAggregateInputType | true
}

export interface WLBSubscriptionDelegate<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
  GlobalOmitOptions = {},
> {
  [K: symbol]: {
    types: Prisma.TypeMap<ExtArgs>['model']['WLBSubscription']
    meta: { name: 'WLBSubscription' }
  }
  /**
   * Find zero or one WLBSubscription that matches the filter.
   * @param {WLBSubscriptionFindUniqueArgs} args - Arguments to find a WLBSubscription
   * @example
   * // Get one WLBSubscription
   * const wLBSubscription = await prisma.wLBSubscription.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends WLBSubscriptionFindUniqueArgs>(
    args: Prisma.SelectSubset<T, WLBSubscriptionFindUniqueArgs<ExtArgs>>
  ): Prisma.Prisma__WLBSubscriptionClient<
    runtime.Types.Result.GetResult<
      Prisma.$WLBSubscriptionPayload<ExtArgs>,
      T,
      'findUnique',
      GlobalOmitOptions
    > | null,
    null,
    ExtArgs,
    GlobalOmitOptions
  >

  /**
   * Find one WLBSubscription that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {WLBSubscriptionFindUniqueOrThrowArgs} args - Arguments to find a WLBSubscription
   * @example
   * // Get one WLBSubscription
   * const wLBSubscription = await prisma.wLBSubscription.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends WLBSubscriptionFindUniqueOrThrowArgs>(
    args: Prisma.SelectSubset<T, WLBSubscriptionFindUniqueOrThrowArgs<ExtArgs>>
  ): Prisma.Prisma__WLBSubscriptionClient<
    runtime.Types.Result.GetResult<
      Prisma.$WLBSubscriptionPayload<ExtArgs>,
      T,
      'findUniqueOrThrow',
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >

  /**
   * Find the first WLBSubscription that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {WLBSubscriptionFindFirstArgs} args - Arguments to find a WLBSubscription
   * @example
   * // Get one WLBSubscription
   * const wLBSubscription = await prisma.wLBSubscription.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends WLBSubscriptionFindFirstArgs>(
    args?: Prisma.SelectSubset<T, WLBSubscriptionFindFirstArgs<ExtArgs>>
  ): Prisma.Prisma__WLBSubscriptionClient<
    runtime.Types.Result.GetResult<
      Prisma.$WLBSubscriptionPayload<ExtArgs>,
      T,
      'findFirst',
      GlobalOmitOptions
    > | null,
    null,
    ExtArgs,
    GlobalOmitOptions
  >

  /**
   * Find the first WLBSubscription that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {WLBSubscriptionFindFirstOrThrowArgs} args - Arguments to find a WLBSubscription
   * @example
   * // Get one WLBSubscription
   * const wLBSubscription = await prisma.wLBSubscription.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends WLBSubscriptionFindFirstOrThrowArgs>(
    args?: Prisma.SelectSubset<T, WLBSubscriptionFindFirstOrThrowArgs<ExtArgs>>
  ): Prisma.Prisma__WLBSubscriptionClient<
    runtime.Types.Result.GetResult<
      Prisma.$WLBSubscriptionPayload<ExtArgs>,
      T,
      'findFirstOrThrow',
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >

  /**
   * Find zero or more WLBSubscriptions that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {WLBSubscriptionFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all WLBSubscriptions
   * const wLBSubscriptions = await prisma.wLBSubscription.findMany()
   *
   * // Get first 10 WLBSubscriptions
   * const wLBSubscriptions = await prisma.wLBSubscription.findMany({ take: 10 })
   *
   * // Only select the `id`
   * const wLBSubscriptionWithIdOnly = await prisma.wLBSubscription.findMany({ select: { id: true } })
   *
   */
  findMany<T extends WLBSubscriptionFindManyArgs>(
    args?: Prisma.SelectSubset<T, WLBSubscriptionFindManyArgs<ExtArgs>>
  ): Prisma.PrismaPromise<
    runtime.Types.Result.GetResult<
      Prisma.$WLBSubscriptionPayload<ExtArgs>,
      T,
      'findMany',
      GlobalOmitOptions
    >
  >

  /**
   * Create a WLBSubscription.
   * @param {WLBSubscriptionCreateArgs} args - Arguments to create a WLBSubscription.
   * @example
   * // Create one WLBSubscription
   * const WLBSubscription = await prisma.wLBSubscription.create({
   *   data: {
   *     // ... data to create a WLBSubscription
   *   }
   * })
   *
   */
  create<T extends WLBSubscriptionCreateArgs>(
    args: Prisma.SelectSubset<T, WLBSubscriptionCreateArgs<ExtArgs>>
  ): Prisma.Prisma__WLBSubscriptionClient<
    runtime.Types.Result.GetResult<
      Prisma.$WLBSubscriptionPayload<ExtArgs>,
      T,
      'create',
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >

  /**
   * Create many WLBSubscriptions.
   * @param {WLBSubscriptionCreateManyArgs} args - Arguments to create many WLBSubscriptions.
   * @example
   * // Create many WLBSubscriptions
   * const wLBSubscription = await prisma.wLBSubscription.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *
   */
  createMany<T extends WLBSubscriptionCreateManyArgs>(
    args?: Prisma.SelectSubset<T, WLBSubscriptionCreateManyArgs<ExtArgs>>
  ): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many WLBSubscriptions and returns the data saved in the database.
   * @param {WLBSubscriptionCreateManyAndReturnArgs} args - Arguments to create many WLBSubscriptions.
   * @example
   * // Create many WLBSubscriptions
   * const wLBSubscription = await prisma.wLBSubscription.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *
   * // Create many WLBSubscriptions and only return the `id`
   * const wLBSubscriptionWithIdOnly = await prisma.wLBSubscription.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   *
   */
  createManyAndReturn<T extends WLBSubscriptionCreateManyAndReturnArgs>(
    args?: Prisma.SelectSubset<T, WLBSubscriptionCreateManyAndReturnArgs<ExtArgs>>
  ): Prisma.PrismaPromise<
    runtime.Types.Result.GetResult<
      Prisma.$WLBSubscriptionPayload<ExtArgs>,
      T,
      'createManyAndReturn',
      GlobalOmitOptions
    >
  >

  /**
   * Delete a WLBSubscription.
   * @param {WLBSubscriptionDeleteArgs} args - Arguments to delete one WLBSubscription.
   * @example
   * // Delete one WLBSubscription
   * const WLBSubscription = await prisma.wLBSubscription.delete({
   *   where: {
   *     // ... filter to delete one WLBSubscription
   *   }
   * })
   *
   */
  delete<T extends WLBSubscriptionDeleteArgs>(
    args: Prisma.SelectSubset<T, WLBSubscriptionDeleteArgs<ExtArgs>>
  ): Prisma.Prisma__WLBSubscriptionClient<
    runtime.Types.Result.GetResult<
      Prisma.$WLBSubscriptionPayload<ExtArgs>,
      T,
      'delete',
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >

  /**
   * Update one WLBSubscription.
   * @param {WLBSubscriptionUpdateArgs} args - Arguments to update one WLBSubscription.
   * @example
   * // Update one WLBSubscription
   * const wLBSubscription = await prisma.wLBSubscription.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   *
   */
  update<T extends WLBSubscriptionUpdateArgs>(
    args: Prisma.SelectSubset<T, WLBSubscriptionUpdateArgs<ExtArgs>>
  ): Prisma.Prisma__WLBSubscriptionClient<
    runtime.Types.Result.GetResult<
      Prisma.$WLBSubscriptionPayload<ExtArgs>,
      T,
      'update',
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >

  /**
   * Delete zero or more WLBSubscriptions.
   * @param {WLBSubscriptionDeleteManyArgs} args - Arguments to filter WLBSubscriptions to delete.
   * @example
   * // Delete a few WLBSubscriptions
   * const { count } = await prisma.wLBSubscription.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   *
   */
  deleteMany<T extends WLBSubscriptionDeleteManyArgs>(
    args?: Prisma.SelectSubset<T, WLBSubscriptionDeleteManyArgs<ExtArgs>>
  ): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more WLBSubscriptions.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {WLBSubscriptionUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many WLBSubscriptions
   * const wLBSubscription = await prisma.wLBSubscription.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   *
   */
  updateMany<T extends WLBSubscriptionUpdateManyArgs>(
    args: Prisma.SelectSubset<T, WLBSubscriptionUpdateManyArgs<ExtArgs>>
  ): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more WLBSubscriptions and returns the data updated in the database.
   * @param {WLBSubscriptionUpdateManyAndReturnArgs} args - Arguments to update many WLBSubscriptions.
   * @example
   * // Update many WLBSubscriptions
   * const wLBSubscription = await prisma.wLBSubscription.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *
   * // Update zero or more WLBSubscriptions and only return the `id`
   * const wLBSubscriptionWithIdOnly = await prisma.wLBSubscription.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   *
   */
  updateManyAndReturn<T extends WLBSubscriptionUpdateManyAndReturnArgs>(
    args: Prisma.SelectSubset<T, WLBSubscriptionUpdateManyAndReturnArgs<ExtArgs>>
  ): Prisma.PrismaPromise<
    runtime.Types.Result.GetResult<
      Prisma.$WLBSubscriptionPayload<ExtArgs>,
      T,
      'updateManyAndReturn',
      GlobalOmitOptions
    >
  >

  /**
   * Create or update one WLBSubscription.
   * @param {WLBSubscriptionUpsertArgs} args - Arguments to update or create a WLBSubscription.
   * @example
   * // Update or create a WLBSubscription
   * const wLBSubscription = await prisma.wLBSubscription.upsert({
   *   create: {
   *     // ... data to create a WLBSubscription
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the WLBSubscription we want to update
   *   }
   * })
   */
  upsert<T extends WLBSubscriptionUpsertArgs>(
    args: Prisma.SelectSubset<T, WLBSubscriptionUpsertArgs<ExtArgs>>
  ): Prisma.Prisma__WLBSubscriptionClient<
    runtime.Types.Result.GetResult<
      Prisma.$WLBSubscriptionPayload<ExtArgs>,
      T,
      'upsert',
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >

  /**
   * Count the number of WLBSubscriptions.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {WLBSubscriptionCountArgs} args - Arguments to filter WLBSubscriptions to count.
   * @example
   * // Count the number of WLBSubscriptions
   * const count = await prisma.wLBSubscription.count({
   *   where: {
   *     // ... the filter for the WLBSubscriptions we want to count
   *   }
   * })
   **/
  count<T extends WLBSubscriptionCountArgs>(
    args?: Prisma.Subset<T, WLBSubscriptionCountArgs>
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], WLBSubscriptionCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a WLBSubscription.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {WLBSubscriptionAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
   **/
  aggregate<T extends WLBSubscriptionAggregateArgs>(
    args: Prisma.Subset<T, WLBSubscriptionAggregateArgs>
  ): Prisma.PrismaPromise<GetWLBSubscriptionAggregateType<T>>

  /**
   * Group by WLBSubscription.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {WLBSubscriptionGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   *
   **/
  groupBy<
    T extends WLBSubscriptionGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: WLBSubscriptionGroupByArgs['orderBy'] }
      : { orderBy?: WLBSubscriptionGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<
      Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>
    >,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
      ? `Error: "by" must not be empty.`
      : HavingValid extends Prisma.False
        ? {
            [P in HavingFields]: P extends ByFields
              ? never
              : P extends string
                ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
                : [Error, 'Field ', P, ` in "having" needs to be provided in "by"`]
          }[HavingFields]
        : 'take' extends Prisma.Keys<T>
          ? 'orderBy' extends Prisma.Keys<T>
            ? ByValid extends Prisma.True
              ? {}
              : {
                  [P in OrderFields]: P extends ByFields
                    ? never
                    : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
                }[OrderFields]
            : 'Error: If you provide "take", you also need to provide "orderBy"'
          : 'skip' extends Prisma.Keys<T>
            ? 'orderBy' extends Prisma.Keys<T>
              ? ByValid extends Prisma.True
                ? {}
                : {
                    [P in OrderFields]: P extends ByFields
                      ? never
                      : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
                  }[OrderFields]
              : 'Error: If you provide "skip", you also need to provide "orderBy"'
            : ByValid extends Prisma.True
              ? {}
              : {
                  [P in OrderFields]: P extends ByFields
                    ? never
                    : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
                }[OrderFields],
  >(
    args: Prisma.SubsetIntersection<T, WLBSubscriptionGroupByArgs, OrderByArg> & InputErrors
  ): {} extends InputErrors
    ? GetWLBSubscriptionGroupByPayload<T>
    : Prisma.PrismaPromise<InputErrors>
  /**
   * Fields of the WLBSubscription model
   */
  readonly fields: WLBSubscriptionFieldRefs
}

/**
 * The delegate class that acts as a "Promise-like" for WLBSubscription.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__WLBSubscriptionClient<
  T,
  Null = never,
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
  GlobalOmitOptions = {},
> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: 'PrismaPromise'
  profile<T extends Prisma.WLBProfileDefaultArgs<ExtArgs> = {}>(
    args?: Prisma.Subset<T, Prisma.WLBProfileDefaultArgs<ExtArgs>>
  ): Prisma.Prisma__WLBProfileClient<
    | runtime.Types.Result.GetResult<
        Prisma.$WLBProfilePayload<ExtArgs>,
        T,
        'findUniqueOrThrow',
        GlobalOmitOptions
      >
    | Null,
    Null,
    ExtArgs,
    GlobalOmitOptions
  >
  author<T extends Prisma.WLBSubscription$authorArgs<ExtArgs> = {}>(
    args?: Prisma.Subset<T, Prisma.WLBSubscription$authorArgs<ExtArgs>>
  ): Prisma.Prisma__UserClient<
    runtime.Types.Result.GetResult<
      Prisma.$UserPayload<ExtArgs>,
      T,
      'findUniqueOrThrow',
      GlobalOmitOptions
    > | null,
    null,
    ExtArgs,
    GlobalOmitOptions
  >
  wlbNotificationRecords<T extends Prisma.WLBSubscription$wlbNotificationRecordsArgs<ExtArgs> = {}>(
    args?: Prisma.Subset<T, Prisma.WLBSubscription$wlbNotificationRecordsArgs<ExtArgs>>
  ): Prisma.PrismaPromise<
    | runtime.Types.Result.GetResult<
        Prisma.$WLBNotificationRecordPayload<ExtArgs>,
        T,
        'findMany',
        GlobalOmitOptions
      >
    | Null
  >
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(
    onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null,
    onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null
  ): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(
    onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null
  ): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}

/**
 * Fields of the WLBSubscription model
 */
export interface WLBSubscriptionFieldRefs {
  readonly id: Prisma.FieldRef<'WLBSubscription', 'String'>
  readonly name: Prisma.FieldRef<'WLBSubscription', 'String'>
  readonly enable: Prisma.FieldRef<'WLBSubscription', 'Boolean'>
  readonly type: Prisma.FieldRef<'WLBSubscription', 'WLBSubscriptionType'>
  readonly message: Prisma.FieldRef<'WLBSubscription', 'WLBSubscriptionMessage'>
  readonly config: Prisma.FieldRef<'WLBSubscription', 'Json'>
  readonly timeOffset: Prisma.FieldRef<'WLBSubscription', 'Int'>
  readonly profileId: Prisma.FieldRef<'WLBSubscription', 'String'>
  readonly userId: Prisma.FieldRef<'WLBSubscription', 'String'>
  readonly createdAt: Prisma.FieldRef<'WLBSubscription', 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<'WLBSubscription', 'DateTime'>
}

// Custom InputTypes
/**
 * WLBSubscription findUnique
 */
export type WLBSubscriptionFindUniqueArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the WLBSubscription
   */
  select?: Prisma.WLBSubscriptionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the WLBSubscription
   */
  omit?: Prisma.WLBSubscriptionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WLBSubscriptionInclude<ExtArgs> | null
  /**
   * Filter, which WLBSubscription to fetch.
   */
  where: Prisma.WLBSubscriptionWhereUniqueInput
}

/**
 * WLBSubscription findUniqueOrThrow
 */
export type WLBSubscriptionFindUniqueOrThrowArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the WLBSubscription
   */
  select?: Prisma.WLBSubscriptionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the WLBSubscription
   */
  omit?: Prisma.WLBSubscriptionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WLBSubscriptionInclude<ExtArgs> | null
  /**
   * Filter, which WLBSubscription to fetch.
   */
  where: Prisma.WLBSubscriptionWhereUniqueInput
}

/**
 * WLBSubscription findFirst
 */
export type WLBSubscriptionFindFirstArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the WLBSubscription
   */
  select?: Prisma.WLBSubscriptionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the WLBSubscription
   */
  omit?: Prisma.WLBSubscriptionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WLBSubscriptionInclude<ExtArgs> | null
  /**
   * Filter, which WLBSubscription to fetch.
   */
  where?: Prisma.WLBSubscriptionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   *
   * Determine the order of WLBSubscriptions to fetch.
   */
  orderBy?:
    | Prisma.WLBSubscriptionOrderByWithRelationInput
    | Prisma.WLBSubscriptionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   *
   * Sets the position for searching for WLBSubscriptions.
   */
  cursor?: Prisma.WLBSubscriptionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Take `±n` WLBSubscriptions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Skip the first `n` WLBSubscriptions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   *
   * Filter by unique combinations of WLBSubscriptions.
   */
  distinct?: Prisma.WLBSubscriptionScalarFieldEnum | Prisma.WLBSubscriptionScalarFieldEnum[]
}

/**
 * WLBSubscription findFirstOrThrow
 */
export type WLBSubscriptionFindFirstOrThrowArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the WLBSubscription
   */
  select?: Prisma.WLBSubscriptionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the WLBSubscription
   */
  omit?: Prisma.WLBSubscriptionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WLBSubscriptionInclude<ExtArgs> | null
  /**
   * Filter, which WLBSubscription to fetch.
   */
  where?: Prisma.WLBSubscriptionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   *
   * Determine the order of WLBSubscriptions to fetch.
   */
  orderBy?:
    | Prisma.WLBSubscriptionOrderByWithRelationInput
    | Prisma.WLBSubscriptionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   *
   * Sets the position for searching for WLBSubscriptions.
   */
  cursor?: Prisma.WLBSubscriptionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Take `±n` WLBSubscriptions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Skip the first `n` WLBSubscriptions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   *
   * Filter by unique combinations of WLBSubscriptions.
   */
  distinct?: Prisma.WLBSubscriptionScalarFieldEnum | Prisma.WLBSubscriptionScalarFieldEnum[]
}

/**
 * WLBSubscription findMany
 */
export type WLBSubscriptionFindManyArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the WLBSubscription
   */
  select?: Prisma.WLBSubscriptionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the WLBSubscription
   */
  omit?: Prisma.WLBSubscriptionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WLBSubscriptionInclude<ExtArgs> | null
  /**
   * Filter, which WLBSubscriptions to fetch.
   */
  where?: Prisma.WLBSubscriptionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   *
   * Determine the order of WLBSubscriptions to fetch.
   */
  orderBy?:
    | Prisma.WLBSubscriptionOrderByWithRelationInput
    | Prisma.WLBSubscriptionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   *
   * Sets the position for listing WLBSubscriptions.
   */
  cursor?: Prisma.WLBSubscriptionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Take `±n` WLBSubscriptions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Skip the first `n` WLBSubscriptions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   *
   * Filter by unique combinations of WLBSubscriptions.
   */
  distinct?: Prisma.WLBSubscriptionScalarFieldEnum | Prisma.WLBSubscriptionScalarFieldEnum[]
}

/**
 * WLBSubscription create
 */
export type WLBSubscriptionCreateArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the WLBSubscription
   */
  select?: Prisma.WLBSubscriptionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the WLBSubscription
   */
  omit?: Prisma.WLBSubscriptionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WLBSubscriptionInclude<ExtArgs> | null
  /**
   * The data needed to create a WLBSubscription.
   */
  data: Prisma.XOR<Prisma.WLBSubscriptionCreateInput, Prisma.WLBSubscriptionUncheckedCreateInput>
}

/**
 * WLBSubscription createMany
 */
export type WLBSubscriptionCreateManyArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * The data used to create many WLBSubscriptions.
   */
  data: Prisma.WLBSubscriptionCreateManyInput | Prisma.WLBSubscriptionCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * WLBSubscription createManyAndReturn
 */
export type WLBSubscriptionCreateManyAndReturnArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the WLBSubscription
   */
  select?: Prisma.WLBSubscriptionSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the WLBSubscription
   */
  omit?: Prisma.WLBSubscriptionOmit<ExtArgs> | null
  /**
   * The data used to create many WLBSubscriptions.
   */
  data: Prisma.WLBSubscriptionCreateManyInput | Prisma.WLBSubscriptionCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WLBSubscriptionIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * WLBSubscription update
 */
export type WLBSubscriptionUpdateArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the WLBSubscription
   */
  select?: Prisma.WLBSubscriptionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the WLBSubscription
   */
  omit?: Prisma.WLBSubscriptionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WLBSubscriptionInclude<ExtArgs> | null
  /**
   * The data needed to update a WLBSubscription.
   */
  data: Prisma.XOR<Prisma.WLBSubscriptionUpdateInput, Prisma.WLBSubscriptionUncheckedUpdateInput>
  /**
   * Choose, which WLBSubscription to update.
   */
  where: Prisma.WLBSubscriptionWhereUniqueInput
}

/**
 * WLBSubscription updateMany
 */
export type WLBSubscriptionUpdateManyArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * The data used to update WLBSubscriptions.
   */
  data: Prisma.XOR<
    Prisma.WLBSubscriptionUpdateManyMutationInput,
    Prisma.WLBSubscriptionUncheckedUpdateManyInput
  >
  /**
   * Filter which WLBSubscriptions to update
   */
  where?: Prisma.WLBSubscriptionWhereInput
  /**
   * Limit how many WLBSubscriptions to update.
   */
  limit?: number
}

/**
 * WLBSubscription updateManyAndReturn
 */
export type WLBSubscriptionUpdateManyAndReturnArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the WLBSubscription
   */
  select?: Prisma.WLBSubscriptionSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the WLBSubscription
   */
  omit?: Prisma.WLBSubscriptionOmit<ExtArgs> | null
  /**
   * The data used to update WLBSubscriptions.
   */
  data: Prisma.XOR<
    Prisma.WLBSubscriptionUpdateManyMutationInput,
    Prisma.WLBSubscriptionUncheckedUpdateManyInput
  >
  /**
   * Filter which WLBSubscriptions to update
   */
  where?: Prisma.WLBSubscriptionWhereInput
  /**
   * Limit how many WLBSubscriptions to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WLBSubscriptionIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * WLBSubscription upsert
 */
export type WLBSubscriptionUpsertArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the WLBSubscription
   */
  select?: Prisma.WLBSubscriptionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the WLBSubscription
   */
  omit?: Prisma.WLBSubscriptionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WLBSubscriptionInclude<ExtArgs> | null
  /**
   * The filter to search for the WLBSubscription to update in case it exists.
   */
  where: Prisma.WLBSubscriptionWhereUniqueInput
  /**
   * In case the WLBSubscription found by the `where` argument doesn't exist, create a new WLBSubscription with this data.
   */
  create: Prisma.XOR<Prisma.WLBSubscriptionCreateInput, Prisma.WLBSubscriptionUncheckedCreateInput>
  /**
   * In case the WLBSubscription was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.WLBSubscriptionUpdateInput, Prisma.WLBSubscriptionUncheckedUpdateInput>
}

/**
 * WLBSubscription delete
 */
export type WLBSubscriptionDeleteArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the WLBSubscription
   */
  select?: Prisma.WLBSubscriptionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the WLBSubscription
   */
  omit?: Prisma.WLBSubscriptionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WLBSubscriptionInclude<ExtArgs> | null
  /**
   * Filter which WLBSubscription to delete.
   */
  where: Prisma.WLBSubscriptionWhereUniqueInput
}

/**
 * WLBSubscription deleteMany
 */
export type WLBSubscriptionDeleteManyArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Filter which WLBSubscriptions to delete
   */
  where?: Prisma.WLBSubscriptionWhereInput
  /**
   * Limit how many WLBSubscriptions to delete.
   */
  limit?: number
}

/**
 * WLBSubscription.author
 */
export type WLBSubscription$authorArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the User
   */
  select?: Prisma.UserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the User
   */
  omit?: Prisma.UserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserInclude<ExtArgs> | null
  where?: Prisma.UserWhereInput
}

/**
 * WLBSubscription.wlbNotificationRecords
 */
export type WLBSubscription$wlbNotificationRecordsArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the WLBNotificationRecord
   */
  select?: Prisma.WLBNotificationRecordSelect<ExtArgs> | null
  /**
   * Omit specific fields from the WLBNotificationRecord
   */
  omit?: Prisma.WLBNotificationRecordOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WLBNotificationRecordInclude<ExtArgs> | null
  where?: Prisma.WLBNotificationRecordWhereInput
  orderBy?:
    | Prisma.WLBNotificationRecordOrderByWithRelationInput
    | Prisma.WLBNotificationRecordOrderByWithRelationInput[]
  cursor?: Prisma.WLBNotificationRecordWhereUniqueInput
  take?: number
  skip?: number
  distinct?:
    | Prisma.WLBNotificationRecordScalarFieldEnum
    | Prisma.WLBNotificationRecordScalarFieldEnum[]
}

/**
 * WLBSubscription without action
 */
export type WLBSubscriptionDefaultArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the WLBSubscription
   */
  select?: Prisma.WLBSubscriptionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the WLBSubscription
   */
  omit?: Prisma.WLBSubscriptionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WLBSubscriptionInclude<ExtArgs> | null
}
