kind: pipeline
name: default

workspace:
  path: /paperplane.cc

volumes:
  - name: dockersock
    host:
      path: /var/run/docker.sock
  - name: envfile
    host:
      path: /root/project-config/paperplane.cc/.env.production.local

trigger:
  branch:
    - main

steps:
  - name: prepare
    image: chiskat/baseline-node20:2026.4.26
    commands:
      - pnpm run ci:prepare-docker

  - name: build-image
    image: docker:dind
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
      - name: envfile
        path: /paperplane.cc/.env.production.local
    commands:
      - docker build --progress plain --compress -t chiskat/paperplane.cc:${DRONE_COMMIT_SHA:0:8} .

  - name: stop-old-container
    image: docker:dind
    failure: ignore
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
    commands:
      - docker stop paperplane-cc
      - docker rm paperplane-cc

  - name: rename-old-image
    image: docker:dind
    failure: ignore
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
    commands:
      - docker tag chiskat/paperplane.cc:production chiskat/paperplane.cc:previous-prod
      - docker rmi chiskat/paperplane.cc:production

  - name: server-prisma-sync-db
    image: appleboy/drone-ssh
    settings:
      host:
        from_secret: DEPLOY_SSH_HOST
      username:
        from_secret: DEPLOY_SSH_USER
      key:
        from_secret: DEPLOY_SSH_PRIKEY
      command_timeout: 5m
      script:
        - cd /root/project-config/paperplane.cc
        - |
          docker run -t --rm --name paperplane.cc-prisma --network pgsql -e NODE_ENV=production \
          -v ./.env.production.local:/paperplane.cc/.env.production.local:ro \
          chiskat/paperplane.cc:${DRONE_COMMIT_SHA:0:8} pnpm db:deploy

  - name: deploy
    image: appleboy/drone-ssh
    settings:
      host:
        from_secret: DEPLOY_SSH_HOST
      username:
        from_secret: DEPLOY_SSH_USER
      key:
        from_secret: DEPLOY_SSH_PRIKEY
      command_timeout: 20m
      script:
        - docker tag chiskat/paperplane.cc:${DRONE_COMMIT_SHA:0:8} chiskat/paperplane.cc:production
        - cd /root/project-config/paperplane.cc
        - docker compose up -d

  - name: extract-assets
    image: docker:dind
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
    commands:
      - docker cp paperplane-cc:/paperplane.cc/.next/ ./

  - name: deploy-upload-s3
    image: plugins/s3
    settings:
      endpoint:
        from_secret: S3_ENDPOINT
      region:
        from_secret: S3_REGION
      bucket:
        from_secret: S3_BUCKET_NAME
      access_key:
        from_secret: S3_ACCESS_KEY_ID
      secret_key:
        from_secret: S3_SECRET_ACCESS_KEY
      source: ./.next/static/**/*
      target: /paperplane.cc/_next/static
      strip_prefix: .next/static

  - name: clean
    image: docker:dind
    failure: ignore
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
    commands:
      - docker rmi chiskat/paperplane.cc:previous-prod
      - docker rmi chiskat/paperplane.cc:${DRONE_COMMIT_SHA:0:8}

  - name: rollback-handle-docker
    image: docker:dind
    when:
      status:
        - failure
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
    commands:
      - docker stop paperplane.cc || true
      - docker rm paperplane.cc || true
      - docker rmi chiskat/paperplane.cc:production || true
      - docker rmi chiskat/paperplane.cc:${DRONE_COMMIT_SHA:0:8} || true

  - name: rollback-handle-ssh
    image: appleboy/drone-ssh
    when:
      status:
        - failure
    settings:
      host:
        from_secret: DEPLOY_SSH_HOST
      username:
        from_secret: DEPLOY_SSH_USER
      key:
        from_secret: DEPLOY_SSH_PRIKEY
      command_timeout: 20m
      script:
        - docker tag chiskat/paperplane.cc:previous-prod chiskat/paperplane.cc:production || true
        - docker rmi chiskat/paperplane.cc:previous-prod || true
        - cd /root/project-config/paperplane.cc
        - docker compose up -d
