allowBuilds:
  '@prisma/engines': true
  esbuild: true
  msw: false
  prisma: true
  protobufjs: true
  puppeteer: false
  sharp: true
  unrs-resolver: true
overrides:
  react-jsx-parser>@types/react: $@types/react
  react-jsx-parser>@types/react-dom: $@types/react-dom
