ignoredBuiltDependencies:
  - sharp
  - unrs-resolver
onlyBuiltDependencies:
  - '@prisma/engines'
  - msw
  - prisma
overrides:
  react-jsx-parser>@types/react: $@types/react
  react-jsx-parser>@types/react-dom: $@types/react-dom
