/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck
/*
 * This file should be your main import to use Prisma-related types and utilities in a browser.
 * Use it to get access to models, enums, and input types.
 *
 * This file does not contain a `PrismaClient` class, nor several other helpers that are intended as server-side only.
 * See `client.ts` for the standard, server-side entry point.
 *
 * 🟢 You can import this file directly.
 */

import * as Prisma from './internal/prismaNamespaceBrowser'

export { Prisma }
export * as $Enums from './enums'
export * from './enums'
/**
 * Model AwesomeCatelog
 * Awesome 类别，存在父子级别
 */
export type AwesomeCatelog = Prisma.AwesomeCatelogModel
/**
 * Model AwesomeTag
 * Awesome 的标签
 */
export type AwesomeTag = Prisma.AwesomeTagModel
/**
 * Model AwesomeItem
 * Awesome 项
 */
export type AwesomeItem = Prisma.AwesomeItemModel
/**
 * Model OARobotProfile
 * OA 机器人档案
 */
export type OARobotProfile = Prisma.OARobotProfileModel
/**
 * Model Short
 * 短网址记录
 */
export type Short = Prisma.ShortModel
/**
 * Model User
 * 用户（由 btter-auth 创建）
 */
export type User = Prisma.UserModel
/**
 * Model Session
 * 会话（由 btter-auth 创建）
 */
export type Session = Prisma.SessionModel
/**
 * Model Account
 * 账户（由 btter-auth 创建）
 */
export type Account = Prisma.AccountModel
/**
 * Model Verification
 * 验证（由 btter-auth 创建）
 */
export type Verification = Prisma.VerificationModel
/**
 * Model Apikey
 * 账号 API（由 btter-auth 创建）
 */
export type Apikey = Prisma.ApikeyModel
